import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createWorkerRuntime} from "../src/autonomy/worker-runtime.js";
import {createLocalWorkerHandoff} from "../src/autonomy/local-worker-handoff.js";
import {createSelfDevelopmentService} from "../src/autonomy/self-development.js";

const OWNER="owner",TASK="selfdev_10721df97b8cbc63c70d4171f6f4a440",REPOSITORY="hshanbour/nova-brain",BRANCH="feat/nova-brain-mvp-foundation",APPROVAL="b624260c-4cf2-4d4a-8e52-bf0efdede8dc",COMMIT="911c1bc472e6017fac65146dd14298966a11c26f",FIRST="c60e7dd036b8faa6ff655ec8eb0b702a7f671d20",SECOND="5818ce4a8b0eb13285971cfcede009c7ae0d5aad";
const now=()=>new Date("2026-09-11T16:45:00.000Z");
const templates=()=>Array.from({length:311},(_,index)=>index===308?{type:"integrate_commit",input:{tool:"git_integrate_reviewed_commit",arguments:{firstParentSha:FIRST,secondParentSha:SECOND}}}:index===309?{type:"review_commit",input:{tool:"repo_review_commit",arguments:{commitSha:"$CURRENT_COMMIT",firstParentSha:FIRST,secondParentSha:SECOND}}}:index===310?{type:"push",input:{tool:"git_push",arguments:{repository:REPOSITORY,branch:BRANCH,commitSha:"$CURRENT_COMMIT"}}}:{type:"inspect_repo",input:{tool:"repo_list",arguments:{}}});

async function v288Fixture({taskPatch={},approvalPatch={},remoteTip=FIRST,withRuntime=false,withPush=false,reviewedChangeSetPatch={},integrationResultPatch={}}={}){
  const storage=createInMemoryStorage({clock:now});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});
  await storage.createAutonomyTask({id:TASK,ownerId:OWNER,projectId:"nova-brain",title:"Approved integration",objective:"Deliver reviewed integration",taskType:"self_development",branch:BRANCH,startingCommit:SECOND,currentCommit:COMMIT,maxSteps:400,maxRuntimeMinutes:90,metadata:{steps:templates(),autoDispatch:true,selfDevelopment:{repository:REPOSITORY}}});
  await storage.recordAutonomyStep({taskId:TASK,stepId:"309:integrate_commit",stepType:"integrate_commit",capability:"repo_mutate_local",operationFingerprint:"integrate",status:"completed",result:{ok:true,commitSha:COMMIT,firstParentSha:FIRST,secondParentSha:SECOND,...integrationResultPatch}});
  await storage.recordAutonomyStep({taskId:TASK,stepId:"310:review_commit",stepType:"review_commit",capability:"repo_read_remote",operationFingerprint:"review",status:"completed",result:{ok:true,commitSha:COMMIT,reviewedChangeSet:{commitSha:COMMIT,reviewHash:"a".repeat(64),allowedPaths:["assets/voice-input.js"],firstParentSha:FIRST,secondParentSha:SECOND,...reviewedChangeSetPatch}}});
  if(withPush)await storage.recordAutonomyStep({taskId:TASK,stepId:"311:push",stepType:"push",capability:"github_write",operationFingerprint:"push",status:"completed",result:{ok:true,commitSha:COMMIT,branch:BRANCH}});
  await storage.createApproval({id:APPROVAL,ownerId:OWNER,projectId:"nova-brain",runId:TASK,tool:"git_push",reason:"Exact integration",riskLevel:"SENSITIVE",arguments:{repository:REPOSITORY,branch:BRANCH,commitSha:COMMIT,approvedStateVersion:287,...approvalPatch}});await storage.decideApproval(APPROVAL,OWNER,"approved");
  let task=await storage.getAutonomyTask(TASK,OWNER);while(task.stateVersion<287)task=await storage.updateAutonomyTask(TASK,OWNER,{},task.stateVersion);
  const approvalState={approvalId:APPROVAL,approved:true,tool:"git_push",stepId:"311:push",repository:REPOSITORY,branch:BRANCH,commitSha:COMMIT,arguments:{repository:REPOSITORY,branch:BRANCH,commitSha:COMMIT,approvedStateVersion:287},approvedStateVersion:287,deliveryStateVersion:288,bindingSource:"approval_contract"};
  task=await storage.updateAutonomyTask(TASK,OWNER,{status:"queued",currentStep:310,currentPhase:"review_commit",currentCommit:COMMIT,approvalState,...taskPatch,metadata:{...task.metadata,...(withRuntime?{approvedDeliveryRuntime:{existing:true}}:{}),...(taskPatch.metadata||{})}},task.stateVersion);assert.equal(task.stateVersion,288);
  const runtime=createWorkerRuntime({storage,ownerId:OWNER,approvedBranch:BRANCH,clock:now,capabilities:["repo_read_remote"],toolRegistry:{async execute(){throw new Error("server must not execute");}}});
  const service=createSelfDevelopmentService({runtime,storage,ownerId:OWNER,approvedBranch:BRANCH,currentCommit:FIRST,clock:now,verifyRemote:async()=>({currentTip:remoteTip,ancestors:{[FIRST]:remoteTip===FIRST}})});
  return{storage,runtime,service,task};
}

test("exact v288 approval contract receives one bounded compatibility runtime without recreating approval",async()=>{const f=await v288Fixture(),before=(await f.storage.listApprovals(OWNER)).length,result=await f.service.recoverApprovedContractDeliveryRuntime(TASK,{expectedVersion:288}),task=result.task;assert.equal(task.stateVersion,289);assert.equal(task.status,"queued");assert.equal(task.approvalState.approvalId,APPROVAL);assert.equal(task.approvalState.deliveryStateVersion,289);assert.deepEqual([result.recovery.firstParentSha,result.recovery.secondParentSha],[FIRST,SECOND]);assert.equal(result.recovery.maxAdditionalDeliverySteps,1);assert.equal(result.recovery.runtimeMinutes,5);assert.equal(result.recovery.consumed,false);assert.equal((await f.storage.listApprovals(OWNER)).length,before);assert.equal((await f.storage.listAutonomySteps(TASK)).some(step=>step.stepId==="311:push"),false);});

test("v288 compatibility recovery fails closed for altered state, approval, commit, remote, runtime, or completed push",async()=>{for(const options of [{taskPatch:{status:"failed"}},{taskPatch:{approvalState:{approvalId:"wrong"}}},{taskPatch:{currentCommit:"f".repeat(40)}},{remoteTip:"e".repeat(40)},{withRuntime:true},{withPush:true}]){const f=await v288Fixture(options);await assert.rejects(()=>f.service.recoverApprovedContractDeliveryRuntime(TASK,{expectedVersion:288}),error=>["approval_contract_delivery_runtime_recovery_precondition_failed","approval_contract_delivery_runtime_remote_changed"].includes(error.code));}});

test("v288 compatibility recovery requires exact durable review and integration parent evidence",async()=>{const wrong="f".repeat(40),cases=[{reviewedChangeSetPatch:{firstParentSha:undefined}},{reviewedChangeSetPatch:{secondParentSha:undefined}},{reviewedChangeSetPatch:{firstParentSha:wrong}},{reviewedChangeSetPatch:{secondParentSha:wrong}},{integrationResultPatch:{firstParentSha:undefined}},{integrationResultPatch:{secondParentSha:undefined}},{integrationResultPatch:{firstParentSha:wrong}},{integrationResultPatch:{secondParentSha:wrong}},{integrationResultPatch:{firstParentSha:undefined,secondParentSha:undefined,parents:[FIRST,SECOND]}}];for(const options of cases){const f=await v288Fixture(options);await assert.rejects(()=>f.service.recoverApprovedContractDeliveryRuntime(TASK,{expectedVersion:288}),error=>error.code==="approval_contract_delivery_runtime_recovery_precondition_failed");}});

test("normal approval contract creates exactly one five-minute delivery runtime",async()=>{const storage=createInMemoryStorage({clock:now});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});await storage.createAutonomyTask({id:"normal",ownerId:OWNER,projectId:"nova-brain",title:"Normal approval",objective:"Push reviewed commit",taskType:"self_development",branch:BRANCH,startingCommit:COMMIT,currentCommit:COMMIT,maxSteps:5,maxRuntimeMinutes:1,metadata:{steps:[{type:"review_commit"},{type:"push",input:{tool:"git_push",arguments:{repository:REPOSITORY,branch:BRANCH,commitSha:COMMIT}}}],selfDevelopment:{repository:REPOSITORY}}});const args={repository:REPOSITORY,branch:BRANCH,commitSha:COMMIT,approvedStateVersion:2},approval=await storage.createApproval({id:"normal-approval",ownerId:OWNER,projectId:"nova-brain",runId:"normal",tool:"git_push",reason:"Exact push",riskLevel:"SENSITIVE",arguments:args});await storage.decideApproval(approval.id,OWNER,"approved");let task=await storage.getAutonomyTask("normal",OWNER);task=await storage.updateAutonomyTask("normal",OWNER,{status:"waiting_for_approval",currentStep:1,currentPhase:"review_commit",approvalState:{approvalId:approval.id,approved:false,tool:"git_push",stepId:"2:push",repository:REPOSITORY,branch:BRANCH,commitSha:COMMIT,arguments:args,approvedStateVersion:2,bindingSource:"approval_contract"}},task.stateVersion);assert.equal(task.stateVersion,2);const runtime=createWorkerRuntime({storage,ownerId:OWNER,approvedBranch:BRANCH,clock:now,toolRegistry:{async execute(){throw new Error("unused");}}}),updated=await runtime.resumeApproval(task.id,await storage.getApproval(approval.id,OWNER)),delivery=updated.metadata.approvedDeliveryRuntime;assert.equal(updated.stateVersion,3);assert.equal(updated.approvalState.deliveryStateVersion,3);assert.equal(delivery.recoveryClass,"approval_contract_delivery_runtime");assert.equal(delivery.maxAdditionalDeliverySteps,1);assert.equal(delivery.consumed,false);assert.equal(new Date(delivery.deadline)-new Date(delivery.startedAt),5*60000);assert.equal(delivery.deliveryStepId,"2:push");});

test("planned exact approved push uses approved-delivery runtime and cannot be claimed twice",async()=>{const f=await v288Fixture(),recovered=await f.service.recoverApprovedContractDeliveryRuntime(TASK,{expectedVersion:288}),handoffs=createLocalWorkerHandoff({storage:f.storage,ownerId:OWNER,approvedBranch:BRANCH,clock:now}),input={workerId:"worker",capabilities:["approved_delivery_git_push"],expectedBranch:BRANCH,expectedCommit:COMMIT,taskId:TASK,idempotencyKey:"exact-push"},claimed=await handoffs.claim(input);assert.equal(claimed.claimed,true,JSON.stringify(claimed));assert.equal(claimed.handoff.stepId,"311:push");assert.equal(claimed.handoff.tool,"git_push");await handoffs.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker",idempotencyKey:"exact-push",result:{ok:true,branch:BRANCH,commitSha:COMMIT}});const task=await f.storage.getAutonomyTask(TASK,OWNER);assert.equal(task.metadata.approvedDeliveryRuntime.consumed,true);assert.equal((await handoffs.claim({...input,idempotencyKey:"second"})).claimed,false);assert.equal(recovered.recovery.maxAdditionalDeliverySteps,1);});
