import test from "node:test";
import assert from "node:assert/strict";
import {readFile} from "node:fs/promises";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createAutoDispatchService} from "../src/autonomy/auto-dispatch.js";
import {createPersistentLocalWorker} from "../src/autonomy/persistent-local-worker.js";
import {createWorkerRuntime} from "../src/autonomy/worker-runtime.js";
import {createSelfDevelopmentService} from "../src/autonomy/self-development.js";
import {createToolRegistry} from "../src/tools/tool-registry.js";

const OWNER="owner",BRANCH="feat/nova-brain-mvp-foundation",SHA="a".repeat(40);
const step=(type)=>({type,input:{tool:type==="apply_patch"?"repo_apply_patch":"repo_list",arguments:type==="apply_patch"?{files:[{path:"docs/acceptance.md",content:"safe"}]}:{path:"."}}});
async function fixture(){const storage=createInMemoryStorage({clock:()=>new Date("2026-09-06T12:00:00Z")});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});const service=createAutoDispatchService({storage,ownerId:OWNER,approvedBranch:BRANCH,clock:()=>new Date("2026-09-06T12:00:00Z")});return{storage,service};}
async function add(storage,id,{status="queued",type="inspect_repo",autoDispatch=true,branch=BRANCH,nextRunAt=null,approvalState=null,leaseToken=null}={}){const task=await storage.createAutonomyTask({id,ownerId:OWNER,projectId:"nova-brain",title:id,objective:"Harmless dispatch acceptance",taskType:"self_development",branch,startingCommit:SHA,maxRuntimeMinutes:90,metadata:{steps:[step(type)],autoDispatch}});if(status!=="queued"||nextRunAt||approvalState||leaseToken)await storage.updateAutonomyTask(id,OWNER,{status,nextRunAt,approvalState,leaseToken,leaseOwner:leaseToken?"other":null,leaseExpiresAt:leaseToken?"2026-09-06T12:10:00Z":null});return task;}
async function approvedDelivery(storage,id="approved-delivery"){
  await storage.createAutonomyTask({id,ownerId:OWNER,projectId:"nova-brain",title:id,objective:"Deliver reviewed commit",taskType:"self_development",branch:BRANCH,startingCommit:SHA,currentCommit:SHA,maxSteps:10,maxRuntimeMinutes:90,metadata:{steps:[],autoDispatch:true}});
  await storage.recordAutonomyStep({taskId:id,stepId:"1:commit",stepType:"commit",capability:"repo_mutate_local",operationFingerprint:"commit",status:"completed",result:{ok:true,commitSha:SHA}});
  await storage.recordAutonomyStep({taskId:id,stepId:"2:review_commit",stepType:"review_commit",capability:"repo_read_remote",operationFingerprint:"review",status:"completed",result:{ok:true,commitSha:SHA,reviewedChangeSet:{reviewHash:"reviewed"}}});
  const approval=await storage.createApproval({id:`${id}-approval`,ownerId:OWNER,projectId:"nova-brain",runId:id,tool:"git_push",reason:"Exact delivery",riskLevel:"SENSITIVE",arguments:{branch:BRANCH,commitSha:SHA}});await storage.decideApproval(approval.id,OWNER,"approved");
  const task=await storage.getAutonomyTask(id,OWNER);return storage.updateAutonomyTask(id,OWNER,{status:"queued",currentStep:2,currentPhase:"review_commit",currentCommit:SHA,approvalState:{approvalId:approval.id,approved:true,tool:"git_push",stepId:"3:push",branch:BRANCH,commitSha:SHA,arguments:{branch:BRANCH,commitSha:SHA}}},task.stateVersion);
}

test("chat-created queued Self-Development task is durably auto-dispatch eligible",async()=>{const f=await fixture();await add(f.storage,"chat-task",{});const result=await f.service.next({workerId:"windows-worker",branch:BRANCH});assert.equal(result.dispatched,true);assert.equal(result.task.id,"chat-task");assert.equal(result.task.mode,"task_tick");});
test("legacy queued Self-Development task is eligible unless explicitly opted out",async()=>{const f=await fixture();await add(f.storage,"existing",{autoDispatch:undefined});delete f.storage;const result=await f.service.next({workerId:"windows-worker",branch:BRANCH});assert.equal(result.task.id,"existing");});
test("local capability step routes only to bounded handoff",async()=>{const f=await fixture();await add(f.storage,"local",{type:"apply_patch",status:"waiting_for_worker"});assert.equal((await f.service.next({workerId:"w"})).task.mode,"local_handoff");});
test("approval blocked terminal leased paused incompatible and opted-out tasks are never dispatched",async()=>{for(const config of[{status:"waiting_for_approval",approvalState:{approvalId:"a"}},{status:"completed"},{leaseToken:"lease"},{status:"waiting"},{autoDispatch:false},{branch:"main"}]){const f=await fixture();await add(f.storage,"blocked",config);assert.deepEqual(await f.service.next({workerId:"w"}),{dispatched:false});}});
test("only an exact approved immutable delivery is auto-dispatched",async()=>{const f=await fixture();await approvedDelivery(f.storage);const result=await f.service.next({workerId:"w"});assert.equal(result.dispatched,true);assert.deepEqual([result.task.mode,result.task.stepType,result.task.expectedCommit],["task_tick","push",SHA]);});
test("approved delivery fails closed for revoked approval and mismatched bindings",async()=>{for(const mutate of [async(f,t)=>f.storage.updateAutonomyTask(t.id,OWNER,{currentCommit:"b".repeat(40)}),async(f,t)=>f.storage.updateAutonomyTask(t.id,OWNER,{approvalState:{...t.approvalState,approvalId:"wrong"}}),async(f,t)=>f.storage.updateAutonomyTask(t.id,OWNER,{approvalState:{...t.approvalState,approved:false}}),async(f,t)=>f.storage.updateAutonomyTask(t.id,OWNER,{approvalState:{...t.approvalState,stepId:"4:push"}}),async(f,t)=>f.storage.recordAutonomyStep({taskId:t.id,stepId:"3:apply_patch",stepType:"apply_patch",capability:"repo_mutate_local",operationFingerprint:"late-mutation",status:"completed",result:{ok:true}})]){const f=await fixture(),task=await approvedDelivery(f.storage);await mutate(f,task);assert.deepEqual(await f.service.next({workerId:"w"}),{dispatched:false});}});
test("approved delivery cannot dispatch an unrelated or broadened action",async()=>{const f=await fixture(),task=await approvedDelivery(f.storage);await f.storage.updateAutonomyTask(task.id,OWNER,{approvalState:{...task.approvalState,tool:"preview_deploy",arguments:{branch:BRANCH,commitSha:SHA}}});assert.deepEqual(await f.service.next({workerId:"w"}),{dispatched:false});});
test("runtime executes only the exact synthetic post-approval push and clears its grant",async()=>{const f=await fixture(),task=await approvedDelivery(f.storage),calls=[],runtime=createWorkerRuntime({storage:f.storage,ownerId:OWNER,approvedBranch:BRANCH,clock:()=>new Date("2026-09-06T12:00:00Z"),capabilities:["github_write"],toolRegistry:{async execute(name,input,context){calls.push({name,input,approvalId:context.approvalId});return{ok:true,commitSha:input.commitSha,branch:input.branch};}}});const result=await runtime.tickTask(task.id,{idempotencyKey:"approved-delivery"}),updated=await runtime.get(task.id);assert.equal(result.stepType,"push");assert.deepEqual(calls,[{name:"git_push",input:{branch:BRANCH,commitSha:SHA},approvalId:`${task.id}-approval`}]);assert.equal(updated.approvalState,null);assert.equal(updated.currentCommit,SHA);});
test("scheduled wait becomes eligible only when due",async()=>{const f=await fixture();await add(f.storage,"future",{status:"waiting",nextRunAt:"2026-09-06T12:01:00Z"});assert.equal((await f.service.next({workerId:"w"})).dispatched,false);const g=await fixture();await add(g.storage,"due",{status:"waiting",nextRunAt:"2026-09-06T11:59:00Z"});assert.equal((await g.service.next({workerId:"w"})).task.id,"due");});
test("dispatch requires bounded worker identity and approved branch",async()=>{const f=await fixture();await assert.rejects(()=>f.service.next({}),e=>e.code==="invalid_dispatch_request");await assert.rejects(()=>f.service.next({workerId:"w",branch:"main"}),e=>e.code==="branch_not_allowed");});
test("persistent runner advances only the exact server-selected task-bound tick",async()=>{const calls=[],client={async request(path,body){calls.push({path,body});if(path.endsWith("/next"))return{dispatched:true,task:{id:"selected",status:"queued",branch:BRANCH,expectedCommit:SHA,stateVersion:4,mode:"task_tick",stepType:"inspect_repo"}};return{claimed:true,status:"queued",stepType:"inspect_repo"};}};const worker=createPersistentLocalWorker({client,branch:BRANCH,registry:{execute(){throw new Error("unused");}}}),result=await worker.runOnce();assert.equal(result.taskId,"selected");assert.match(calls[1].path,/\/tasks\/selected\/tick$/);assert.equal(calls.some(call=>call.path==="/api/autonomy/worker/tick"),false);});
test("persistent runner executes only allowlisted server-issued local tools and carries versioned context",async()=>{const calls=[],client={async request(path,body){calls.push({path,body});if(path.endsWith("/next"))return{dispatched:true,task:{id:"local",status:"waiting_for_worker",branch:BRANCH,expectedCommit:SHA,stateVersion:7,mode:"local_handoff",stepType:"apply_patch"}};if(path.endsWith("/claim"))return{claimed:true,handoff:{handoffId:"h",taskId:"local",branch:BRANCH,expectedCommit:SHA,tool:"repo_apply_patch",arguments:{files:[{path:"docs/acceptance.md",content:"safe"}]}}};return{status:"queued"};}},registry={async execute(name,input,context){assert.equal(name,"repo_apply_patch");assert.deepEqual(context.repositoryContext,{version:1,source:"persistent_worker_handoff",repository:"hshanbour/nova-brain",root:"C:/controlled/nova",branch:BRANCH,expectedHead:SHA});return{ok:true,files:["docs/acceptance.md"]};}};const result=await createPersistentLocalWorker({client,root:"C:/controlled/nova",branch:BRANCH,registry,workerId:"stable"}).runOnce();assert.equal(result.worked,true);assert.ok(calls.some(call=>call.path.endsWith("/complete")));assert.doesNotMatch(JSON.stringify(calls),/password|databaseUrl/i);});
test("repository context is reconstructed after a persistent worker restart",async()=>{const contexts=[],makeClient=()=>({async request(path){if(path.endsWith("/next"))return{dispatched:true,task:{id:"recovered",status:"waiting_for_worker",branch:BRANCH,expectedCommit:SHA,stateVersion:9,mode:"local_handoff",stepType:"apply_patch"}};if(path.endsWith("/claim"))return{claimed:true,handoff:{handoffId:"h",taskId:"recovered",branch:BRANCH,expectedCommit:SHA,tool:"repo_apply_patch",arguments:{files:[{path:"docs/a.md",content:"safe"}]}}};return{status:"queued"};}}),registry={async execute(_name,_input,context){contexts.push(context.repositoryContext);return{ok:true,files:["docs/a.md"]};}};await createPersistentLocalWorker({client:makeClient(),root:"C:/controlled/nova",branch:BRANCH,registry,workerId:"before-restart"}).runOnce();await createPersistentLocalWorker({client:makeClient(),root:"C:/controlled/nova",branch:BRANCH,registry,workerId:"after-restart"}).runOnce();assert.equal(contexts.length,2);assert.deepEqual(contexts[0],contexts[1]);});
test("persistent runner fails closed on unbounded tool and never submits it",async()=>{const calls=[],client={async request(path){calls.push(path);if(path.endsWith("/next"))return{dispatched:true,task:{id:"local",branch:BRANCH,expectedCommit:SHA,stateVersion:1,mode:"local_handoff",stepType:"apply_patch"}};return{claimed:true,handoff:{handoffId:"h",taskId:"local",branch:BRANCH,expectedCommit:SHA,tool:"shell_exec",arguments:{}}};}};await assert.rejects(()=>createPersistentLocalWorker({client,branch:BRANCH,registry:{}}).runOnce(),e=>e.code==="invalid_handoff");assert.equal(calls.some(path=>path.endsWith("/complete")),false);});
test("browser/chat completion is not part of persistent runner lifetime",async()=>{let calls=0;const worker=createPersistentLocalWorker({client:{async request(path){calls++;return path.endsWith("/next")?{dispatched:false}:{}}},registry:{}});assert.deepEqual(await worker.runOnce(),{worked:false});assert.deepEqual(await worker.runOnce(),{worked:false});assert.equal(calls,2);});
test("Windows persistent launcher uses Scheduled Task and Credential Manager-backed runner without secrets",async()=>{const [launcher,runner,startup,credentials]=await Promise.all([readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8"),readFile(new URL("../scripts/persistent-local-worker.js",import.meta.url),"utf8"),readFile(new URL("../src/autonomy/persistent-worker-startup.js",import.meta.url),"utf8"),readFile(new URL("../src/autonomy/local-worker-credentials.js",import.meta.url),"utf8")]);assert.match(launcher,/New-ScheduledTaskTrigger -AtLogOn/);assert.match(launcher,/RestartCount 999/);assert.match(runner,/runPersistentWorkerService/);assert.match(startup,/loadLocalWorkerCredentials/);assert.match(credentials,/WindowsCredentialStore|CredentialStore/);assert.doesNotMatch(launcher,/NOVA_LOCAL_WORKER_TOKEN|VERCEL_AUTOMATION_BYPASS_SECRET/);});
test("Windows scheduler supervises Node directly with deterministic paths instead of a detachable cmd wrapper",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/New-ScheduledTaskAction -Execute \$node/);assert.match(source,/-WorkingDirectory \$root/);assert.match(source,/--preview-url/);assert.doesNotMatch(source,/cmd\.exe|set \"NOVA_LOCAL_WORKER_URL/);});
test("Windows persistent worker starts and remains running on battery power",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/New-ScheduledTaskSettingsSet[^\r\n]+-AllowStartIfOnBatteries/);assert.match(source,/New-ScheduledTaskSettingsSet[^\r\n]+-DontStopIfGoingOnBatteries/);assert.match(source,/RestartCount 999/);assert.match(source,/MultipleInstances IgnoreNew/);});
test("Windows launcher resolves one absolute Git executable and passes it without a shell",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/\$git=\(Get-Command git\.exe -ErrorAction Stop\)\.Source/);assert.match(source,/IsPathRooted\(\$git\)/);assert.match(source,/--git-executable "'\+\$git\+'"/);assert.match(source,/New-ScheduledTaskAction -Execute \$node/);assert.doesNotMatch(source,/cmd\.exe|powershell\.exe/);});
test("persistent runner proves repository identity before starting the service",async()=>{const source=await readFile(new URL("../scripts/persistent-local-worker.js",import.meta.url),"utf8");assert.match(source,/resolveGitExecutable\(\{explicit:gitArgument\}\)/);assert.match(source,/resolveRepositoryContext\(\{root:repositoryRoot/);assert.match(source,/expectedBranch:"feat\/nova-brain-mvp-foundation"/);assert.match(source,/startupMetadata:\{repositoryProof:/);});
test("battery settings preserve current-user Limited direct-Node execution",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/New-ScheduledTaskTrigger -AtLogOn -User \$env:USERNAME/);assert.doesNotMatch(source,/-RunLevel Highest|SYSTEM|New-ScheduledTaskPrincipal/);assert.match(source,/New-ScheduledTaskAction -Execute \$node/);assert.doesNotMatch(source,/NOVA_LOCAL_WORKER_TOKEN|VERCEL_AUTOMATION_BYPASS_SECRET/);});
test("Windows installer preserves the validated Action command parameter",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/ValidateSet\('install','uninstall','status'\)\]\[string\]\$Action/);assert.match(source,/\$Action -eq 'status'/);assert.match(source,/\$Action -eq 'uninstall'/);assert.doesNotMatch(source,/\$action\s*=\s*New-ScheduledTaskAction/i);});
test("Windows install builds and registers only the renamed task action object",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/\$taskAction=New-ScheduledTaskAction/);assert.match(source,/Register-ScheduledTask[^\r\n]+-Action \$taskAction/);assert.equal((source.match(/Register-ScheduledTask/g)||[]).length,1);});
test("Windows installer binds one stable prevalidated native helper outside the repository",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/LOCALAPPDATA[^\r\n]+NovaBrain\\PersistentWorker/);assert.match(source,/NovaCredentialHelper\.exe/);assert.match(source,/prevalidated Windows credential helper/);assert.match(source,/--credential-helper/);assert.doesNotMatch(source,/NOVA_LOCAL_WORKER_TOKEN|VERCEL_AUTOMATION_BYPASS_SECRET/);});
test("Windows Preview rebinding never compiles stages or replaces executable code",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/Test-Path -LiteralPath \$helper -PathType Leaf/);assert.match(source,/\$helper status \$novaTarget/);assert.match(source,/\$helper status \$vercelTarget/);assert.doesNotMatch(source,/csc\.exe|stagedHelper|\.new\.exe|Move-Item[^\r\n]+\$helper|Remove-Item[^\r\n]+\$helper/);});
test("Windows installer preserves a working helper and fails closed on either bounded probe",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/\$LASTEXITCODE -ne 0 -or \$novaStatus -notin @\('configured','missing'\)/);assert.match(source,/\$LASTEXITCODE -ne 0 -or \$vercelStatus -notin @\('configured','missing'\)/);assert.match(source,/stable Windows credential helper failed its bounded status probe/);});
test("Windows installer reads back and rejects a stale Scheduled Task action",async()=>{const source=await readFile(new URL("../scripts/windows-local-worker-service.ps1",import.meta.url),"utf8");assert.match(source,/Register-ScheduledTask[^\r\n]+-Force/);assert.match(source,/\$installedAction=\(Get-ScheduledTask/);assert.match(source,/installedAction\.Arguments[^\r\n]+--credential-helper/);assert.match(source,/credential-helper binding could not be verified/);});
test("Windows installer tests are static and cannot install or start a task",async()=>{const source=await readFile(new URL("../test/auto-dispatch.test.js",import.meta.url),"utf8");assert.doesNotMatch(source,/from ["']node:child_process["']/);assert.doesNotMatch(source,/powershell\.exe|pwsh\.exe/);});
test("dispatch endpoint is separately Nova-authenticated",async()=>{const source=await readFile(new URL("../src/http/api.js",import.meta.url),"utf8");assert.match(source,/\/api\/admin\/worker\/auto-dispatch\/next/);assert.match(source,/authorizeLocalWorker\(\s*request,\s*config\.localWorkerToken,?\s*\)/);});
test("harmless chat task progresses through inspection without manual tick and leaves unrelated task untouched",async()=>{const f=await fixture(),executed=[],clock=()=>new Date("2026-09-06T12:00:00Z"),runtime=createWorkerRuntime({storage:f.storage,ownerId:OWNER,approvedBranch:BRANCH,clock,capabilities:["repo_read_remote","reasoning","scheduler","vercel_preview"],toolRegistry:{async execute(name){executed.push(name);return{ok:true,files:[]};}}}),self=createSelfDevelopmentService({runtime,storage:f.storage,ownerId:OWNER,currentCommit:SHA,clock}),created=await self.create({userGoal:"Document harmless automatic dispatch acceptance",scope:{discovery:{paths:["src/autonomy"]},patch:{files:[{path:"docs/auto-dispatch-acceptance.md",content:"harmless"}]},focusedTests:["test/auto-dispatch.test.js"]}});await add(f.storage,"unrelated",{autoDispatch:false});const client={async request(path,body){if(path.endsWith("/next"))return f.service.next(body);const match=path.match(/\/tasks\/([^/]+)\/tick$/);if(match)return runtime.tickTask(decodeURIComponent(match[1]),body);throw new Error("unexpected path");}},worker=createPersistentLocalWorker({client,branch:BRANCH,registry:{}});await worker.runOnce();await worker.runOnce();const task=await runtime.get(created.task.id),other=await runtime.get("unrelated");assert.ok(task.currentStep>=2);assert.deepEqual(executed,["repo_list","repo_search"]);assert.equal(other.currentStep,0);assert.equal(task.maxRuntimeMinutes,60);assert.equal(task.metadata.maxRepairIterations,3);});
test("persistent runner derives and passes its repository root explicitly",async()=>{const [runner,startup]=await Promise.all([readFile(new URL("../scripts/persistent-local-worker.js",import.meta.url),"utf8"),readFile(new URL("../src/autonomy/persistent-worker-startup.js",import.meta.url),"utf8")]);assert.match(runner,/const repositoryRoot=resolve\(dirname\(fileURLToPath\(import\.meta\.url\)\),"\.\."\)/);assert.match(runner,/repositoryRoot,intervalMs/);assert.match(startup,/workerFactory\(\{client,root:repositoryRoot\}\)/);});

test("Worker-layer schema mismatch serializes an exact safe handoff diagnostic",async()=>{const calls=[],client={async request(path,body){calls.push({path,body});if(path.endsWith("/next"))return{dispatched:true,task:{id:"worker-schema",branch:BRANCH,expectedCommit:SHA,stateVersion:1,mode:"local_handoff",stepType:"apply_patch"}};if(path.endsWith("/claim"))return{claimed:true,handoff:{handoffId:"worker-handoff",taskId:"worker-schema",stepId:"4:apply_patch",stepType:"apply_patch",branch:BRANCH,expectedCommit:SHA,tool:"repo_apply_patch",arguments:[]}};return{status:"failed"};}};await assert.rejects(()=>createPersistentLocalWorker({client,root:"C:/controlled/nova",branch:BRANCH,registry:{execute(){throw new Error("unused");}}}).runOnce(),error=>error.code==="schema_mismatch"&&error.localDiagnostic.validationLayer==="local_worker");const diagnostic=calls.find(call=>call.path.endsWith("/fail")).body.error.diagnostics;assert.deepEqual([diagnostic.tool,diagnostic.fieldPath,diagnostic.schemaVersion,diagnostic.validationLayer,diagnostic.payloadProvenance],["repo_apply_patch","handoff.arguments","1","local_worker","server_handoff"]);assert.deepEqual(diagnostic.expected,{type:"object"});assert.deepEqual(diagnostic.received,{type:"array"});});

test("Hands registry mismatch preserves canonical context through failure serialization",async()=>{const calls=[],registry=createToolRegistry();registry.register({name:"repo_apply_patch",inputSchema:{type:"object",properties:{files:{type:"array"}},required:["files"],additionalProperties:false},execute:async()=>({ok:true})});const client={async request(path,body){calls.push({path,body});if(path.endsWith("/next"))return{dispatched:true,task:{id:"hands-schema",branch:BRANCH,expectedCommit:SHA,stateVersion:2,mode:"local_handoff",stepType:"apply_patch"}};if(path.endsWith("/claim"))return{claimed:true,handoff:{handoffId:"hands-handoff",taskId:"hands-schema",stepId:"9:apply_patch",stepType:"apply_patch",branch:BRANCH,expectedCommit:SHA,tool:"repo_apply_patch",arguments:{files:"secret-value"}}};return{status:"failed"};}};await assert.rejects(()=>createPersistentLocalWorker({client,root:"C:/controlled/nova",branch:BRANCH,registry}).runOnce(),error=>error.code==="schema_mismatch"&&error.localDiagnostic.validationLayer==="hands_tool_registry");const diagnostic=calls.find(call=>call.path.endsWith("/fail")).body.error.diagnostics;assert.deepEqual([diagnostic.tool,diagnostic.fieldPath,diagnostic.schemaVersion,diagnostic.validationLayer,diagnostic.payloadProvenance],["repo_apply_patch","repo_apply_patch.files","1","hands_tool_registry","server_handoff_arguments"]);assert.deepEqual(diagnostic.received,{type:"string"});assert.doesNotMatch(JSON.stringify(diagnostic),/secret-value/);});
