import test from "node:test";
import assert from "node:assert/strict";
import {canonicalContentHash} from "../src/autonomy/self-development-plan-lifecycle.js";
import {createEvidenceBoundReviewReplanFixture,EVIDENCE_BOUND_CLASS,EVIDENCE_BOUND_HISTORY,EVIDENCE_BOUND_BOUNDARY,assertEvidenceBoundHistoriesPreserved} from "./evidence-bound-review-replan-fixture.js";
import {PLANNING_PATHS} from "./planning-scope-fixture.js";
import {REJECTED_REVIEW_EVIDENCE_BYTE_LIMIT} from "../src/autonomy/rejected-review-evidence.js";

const record=task=>task.metadata[EVIDENCE_BOUND_HISTORY]?.at(-1);
const boundary=task=>task.metadata[EVIDENCE_BOUND_BOUNDARY];
const newSteps=async f=>(await f.steps()).filter(step=>Number.parseInt(step.stepId,10)>f.sourceTask.metadata.steps.length);
async function originalStepsPreserved(f){const current=await f.steps();for(const original of f.sourceSteps)assert.deepEqual(current.find(step=>step.stepId===original.stepId),original);}
const noDelivery=f=>assert.equal(f.commands.some(command=>command.args.some(arg=>["commit","push","fetch","pull","clone","install","ci","deploy"].includes(arg))),false);

test("complete v307 evidence-bound successor runs eight fresh reads one model plan preflight apply focused/full to unresolved review_ready",async t=>{
  const f=await createEvidenceBoundReviewReplanFixture(t,{subset:true,verboseFull:true}),before=await f.current(),manifests=await Promise.all(["package.json","package-lock.json"].map(path=>f.read(path)));
  assert.equal(before.stateVersion,307);assert.equal(before.metadata.sourceBoundReviewReplanHistory[0].consumed,true);assert.equal(before.metadata.rejectedReviewPlanContinuationHistory[0].consumed,true);assert.equal(before.metadata.reviewRemediationHistory[0].consumed,true);assert.equal(before.metadata.escalatedRepairHistory.length,1);assert.equal(f.sourceRejectedStep.status,"failed");
  const approval=await f.authorize();assert.equal(approval.approval.tool,"self_development_evidence_bound_review_replan");assert.equal(approval.approval.arguments.maxSteps,13);assert.equal(approval.approval.arguments.runtimeMinutes,15);
  const recovered=await f.recover(),generation=record(recovered.task);assert.equal(recovered.task.stateVersion,308);assert.equal(generation.recoveryClass,EVIDENCE_BOUND_CLASS);assert.equal(generation.fromStateVersion,307);assert.notEqual(generation.activeContinuation.generationId,before.metadata.sourceBoundReviewReplanHistory[0].activeContinuation.generationId);assertEvidenceBoundHistoriesPreserved(before,recovered.task);await f.verifySourceUnchanged();
  await f.runSteps(8);assert.deepEqual(f.executions.map(item=>item.name),Array(8).fill("repo_read_task_owned_local"));assert.deepEqual(f.executions.map(item=>item.args.path),PLANNING_PATHS);assert.equal(f.prompts.length,0);assert.deepEqual((await newSteps(f)).map(step=>step.stepId),generation.readStepIds);assert.ok(generation.readStepIds.every(id=>!f.sourceReads.some(step=>step.stepId===id)));await f.verifySourceUnchanged();await originalStepsPreserved(f);
  for(const item of f.executions){assert.equal(item.result.content,f.afterContents.get(item.args.path));assert.equal(item.context.reviewRemediationScope.recoveryClass,EVIDENCE_BOUND_CLASS);assert.equal(item.result.reviewRemediationEvidence.generationId,generation.activeContinuation.generationId);assert.equal(item.result.reviewRemediationEvidence.entries.length,8);}
  await f.runSteps(1);assert.equal(f.prompts.length,1);assert.equal(f.proposedPlans.length,1);assert.equal(f.prompts[0].reviewRemediation,true);assert.equal(f.prompts[0].scopeExpansionAllowed,false);assert.deepEqual(f.prompts[0].structuredReview,f.review);for(const key of["acceptanceMapping","focusedTestPath","mutationPath","nonMutatedUnresolvedSource","reviewConstraint","reviewCoverage","sourceFinding"])assert.ok(f.prompts[0].inputDistinctions[key]);assert.match(f.prompts[0].inputDistinctions.nonMutatedUnresolvedSource,/current evidence proves/);assert.deepEqual(f.prompts[0].candidateFiles.map(item=>({path:item.path,content:item.content})),PLANNING_PATHS.map(path=>({path,content:f.afterContents.get(path)})));assert.deepEqual(f.prompts[0].availableEvidenceExpansionTests,[]);
  const baselines=new Map(f.prompts[0].committedBaselineFiles.map(item=>[item.path,item.content]));assert.equal(baselines.size,7);for(const path of PLANNING_PATHS.filter(path=>path!=="test/composer-voice-console.integration.test.js"))assert.equal(baselines.get(path)?.trim(),await f.git("show",`HEAD:${path}`));
  const planned=await f.current(),plan=planned.metadata.selfDevelopmentImplementationPlan;assert.equal(plan.files.length,6);assert.equal(plan.reviewCoverage.length,5);assert.notEqual(plan.planHash,f.plan.planHash);assert.deepEqual(plan.evidencePaths,PLANNING_PATHS);for(const file of plan.files)assert.equal(file.expectedContent,f.afterContents.get(file.path));for(const mapping of plan.reviewCoverage)assert.equal(mapping.sourceHash,canonicalContentHash(plan.files.find(file=>file.path===mapping.testPath)?.content||f.afterContents.get(mapping.testPath)));
  await f.verifySourceUnchanged();await f.runSteps(1);assert.equal(f.executions.at(-1).name,"repo_validate_patch");assert.equal(f.executions.at(-1).result.preMutationValidated,true);assert.equal(f.executions.at(-1).result.mutationApplied,false);await f.verifySourceUnchanged();
  await f.runSteps(1);const apply=f.executions.at(-1);assert.equal(apply.name,"repo_apply_patch");assert.equal(apply.args.files.length,6);assert.equal(apply.result.taskOwnedDirtyLineage.entries.length,8);await f.verifyCandidate();
  await f.runSteps(1);const focused=f.executions.at(-1);assert.equal(focused.name,"test_run");assert.match(focused.result.output,/pass 7/);assert.equal(focused.result.outputTruncated,false);
  await f.runSteps(1);const full=f.executions.at(-1);assert.equal(full.name,"test_run_full");assert.match(full.result.output,/tests 8/);assert.match(full.result.output,/pass 8/);assert.equal(full.result.outputTruncated,true);assert.equal(full.result.output.length,20000);assert.equal(full.result.dependencyPreflight.resolved,true);assert.deepEqual(full.result.dependencyPreflight.packages,[{name:"@neondatabase/serverless",version:"1.1.0"}]);
  const final=await f.current();assert.equal(final.status,"blocked");assert.equal(boundary(final).kind,"review_ready");assert.equal(boundary(final).executionAuthorized,false);assert.equal(boundary(final).findingsResolved,false);assert.equal(record(final).consumed,true);assert.equal(record(final).afterEntries.length,8);assert.deepEqual(record(final).unresolvedFindingIds,f.review.findings.filter(item=>item.severity==="blocking").map(item=>item.id));assertEvidenceBoundHistoriesPreserved(before,final);await originalStepsPreserved(f);
  assert.deepEqual((await newSteps(f)).map(step=>step.stepType),[...Array(8).fill("read_files"),"plan_repair","validate_patch","apply_patch","run_focused_tests","run_full_tests"]);assert.ok((await newSteps(f)).every(step=>step.status==="completed"));assert.equal(f.executions.filter(item=>item.name==="repo_apply_patch").length,1);assert.deepEqual(await Promise.all(["package.json","package-lock.json"].map(path=>f.read(path))),manifests);await f.verifyCandidate();noDelivery(f);
  assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());await assert.rejects(()=>f.previousSourceBoundRecover());await assert.rejects(()=>f.previousRejectedRecover());await assert.rejects(()=>f.oldReviewRecover());await assert.rejects(()=>f.previousRetryRecover());await assert.rejects(()=>f.taskWorker.control(f.taskId,"resume"));assert.deepEqual(await f.current(),final);
  await assert.rejects(()=>f.hands.execute(apply.name,apply.args,apply.context));await assert.rejects(()=>f.hands.execute(full.name,full.args,full.context));assert.deepEqual(await f.current(),final);await f.verifyCandidate();
});

test("rejected v307 successor retains only bounded private source-bound evidence and no execution authority",async t=>{
  const canary="UNRESTRICTED_MODEL_RATIONALE_MUST_NEVER_BE_RETAINED",missingName="Synthetic audit named declaration not present in the excerpt";
  const f=await createEvidenceBoundReviewReplanFixture(t,{output:value=>{value.summary=canary;value.files[0].reason=canary;value.reviewCoverage[0].testName=missingName;return value;}}),before=await f.current();
  await f.authorize();await f.recover();await f.runSteps(9);
  const final=await f.current(),failed=(await newSteps(f)).at(-1),diagnostics=failed.result.diagnostics.coverageDiagnostics,proof=failed.result.diagnostics.rejectedPlanEvidence,mapping=f.proposedPlans[0].reviewCoverage[0];
  assert.equal(failed.stepType,"plan_repair");assert.equal(failed.status,"failed");assert.equal(failed.attempt,1);assert.equal(failed.result.diagnostics.predicate,"source_bound_behavioral_coverage");assert.equal(failed.result.diagnostics.mutationApplied,false);
  assert.deepEqual(diagnostics.firstFailure,{predicate:"source_bound_behavioral_coverage",constraintId:"A",subclause:"excerpt_contains_test_name"});
  const reference=failed.result.rejectedReviewEvidence;assert.equal(reference.persisted,true);assert.match(reference.id,/^[a-f0-9-]{36}$/);assert.deepEqual(Object.keys(reference).sort(),["id","persisted"]);
  const evidence=await f.storage.getRejectedReviewEvidence(reference.id,f.ownerId,f.taskId),envelope=evidence.envelope;
  assert.equal(evidence.ownerId,f.ownerId);assert.equal(evidence.taskId,f.taskId);assert.equal(envelope.taskId,f.taskId);assert.equal(envelope.stateVersion,proof.taskStateVersion);assert.equal(envelope.executionId,failed.stepId);assert.equal(envelope.attempt,1);
  assert.equal(envelope.continuationGenerationId,record(final).activeContinuation.generationId);assert.equal(envelope.planFingerprint,proof.planFingerprint);assert.equal(envelope.diagnosticOnly,true);assert.equal(envelope.executionAuthorized,false);assert.equal(envelope.mutationApplied,false);assert.equal(envelope.rejectionPredicate,"source_bound_behavioral_coverage");
  assert.deepEqual(envelope.proposedMutationPaths,PLANNING_PATHS);assert.equal(envelope.selectedFocusedTestPaths.length,4);assert.equal(envelope.coverage.length,5);
  const constraint=envelope.coverage.find(item=>item.constraintId==="A"),expectedHash=canonicalContentHash(f.candidate.after.get(mapping.testPath));
  assert.deepEqual(constraint.findingIds,["console-preservation"]);assert.deepEqual(constraint.sourcePaths,["index.html"]);assert.equal(constraint.testPath,mapping.testPath);assert.equal(constraint.testName,missingName);assert.equal(constraint.sourceExcerpt,mapping.sourceExcerpt);assert.equal(constraint.assertion,mapping.assertion);assert.equal(constraint.stimulus,mapping.stimulus);assert.equal(constraint.observable,mapping.observable);
  assert.equal(constraint.expectedSourceHash,expectedHash);assert.equal(constraint.suppliedSourceHash,expectedHash);assert.equal(constraint.firstFailedSubclause,"excerpt_contains_test_name");assert.equal(constraint.evaluated,true);assert.ok(constraint.clauses.some(item=>item.passed));assert.deepEqual(constraint.clauses.at(-1),{predicate:"source_bound_behavioral_coverage",subclause:"excerpt_contains_test_name",passed:false});assert.ok(envelope.coverage.slice(1).every(item=>item.evaluated===false&&item.clauses.length===0));
  const privateText=JSON.stringify(envelope);assert.ok(Buffer.byteLength(privateText)<=REJECTED_REVIEW_EVIDENCE_BYTE_LIMIT);assert.doesNotMatch(privateText,new RegExp(canary));for(const key of["rawResponse","providerResponse","reasoning","chainOfThought","summary","reason","files"])assert.equal(Object.hasOwn(envelope,key),false);
  const publicText=JSON.stringify({task:final,steps:await f.steps(),activities:await f.storage.listActivity(f.ownerId,{runId:f.taskId,limit:1000})});assert.doesNotMatch(publicText,new RegExp(missingName));assert.doesNotMatch(publicText,new RegExp(canary));assert.equal(Object.hasOwn(failed.result.diagnostics,"privateEvidence"),false);
  assert.equal(await f.storage.getRejectedReviewEvidence(reference.id,"another-owner",f.taskId),null);assert.equal(await f.storage.getRejectedReviewEvidence(reference.id,f.ownerId,"another-task"),null);
  assert.equal(f.prompts.length,1);assert.equal(f.executions.length,8);assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assert.equal(final.status,"blocked");assert.equal(final.repairIteration,3);assertEvidenceBoundHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifySourceUnchanged();noDelivery(f);
  assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());await assert.rejects(()=>f.service.recoverEvidenceBoundReviewReplan(f.taskId,{...f.input,approvalId:reference.id},f.actor));assert.deepEqual(await f.current(),final);assert.deepEqual(await f.storage.getRejectedReviewEvidence(reference.id,f.ownerId,f.taskId),evidence);
});

for(const[name,options,completed]of[["focused",{failingFocused:true},11],["full",{failingFull:true},12]])test(`evidence-bound ${name} failure consumes its own authority and never retries or adds a repair extension`,async t=>{
  const f=await createEvidenceBoundReviewReplanFixture(t,options),before=await f.current();await f.authorize();await f.recover();await f.runSteps(completed);await assert.rejects(()=>f.worker.runOnce(),error=>error.code==="test_failed");
  const final=await f.current(),failed=(await newSteps(f)).at(-1);assert.equal(final.status,"blocked");assert.equal(boundary(final).kind,"product_repair_decision");assert.equal(boundary(final).executionAuthorized,false);assert.equal(record(final).consumed,true);assert.equal(failed.status,"failed");assert.equal(failed.attempt,1);assert.equal(failed.errorCode,"test_failed");assert.ok(failed.result.diagnostics.counts.failed>0);assert.equal(f.executions.filter(item=>item.name==="repo_apply_patch").length,1);assert.equal(f.executions.filter(item=>item.name==="test_run_full").length,name==="focused"?0:1);assertEvidenceBoundHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifyCandidate();noDelivery(f);assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());assert.deepEqual(await f.current(),final);
});

test("evidence-bound reasoning cannot add a ninth path or automatically replace a rejected plan",async t=>{
  const f=await createEvidenceBoundReviewReplanFixture(t,{output:value=>{value.files[7]={...value.files[7],path:"test/ninth.test.js",operation:"create"};return value;}}),before=await f.current();await f.authorize();await f.recover();await f.runSteps(9);
  const final=await f.current(),failed=(await newSteps(f)).at(-1);assert.equal(failed.status,"failed");assert.equal(failed.attempt,1);assert.equal(f.prompts.length,1);assert.equal(f.executions.length,8);assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assert.match(boundary(final).kind,/authorization/);assertEvidenceBoundHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifySourceUnchanged();noDelivery(f);assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());
});

test("evidence-bound current-byte verification rejects canonical-equivalent raw drift despite eight successful historical reads",async t=>{
  const f=await createEvidenceBoundReviewReplanFixture(t),before=await f.current();await f.authorize();await f.recover();const original=await f.read("assets/console.css"),changed=original.replaceAll("\n","\r\n");assert.equal(canonicalContentHash(original),canonicalContentHash(changed));await f.drift("assets/console.css",changed);
  await assert.rejects(()=>f.worker.runOnce());const final=await f.current();assert.equal(f.prompts.length,0);assert.equal(f.executions.some(item=>item.name==="repo_apply_patch"),false);assert.equal(await f.read("assets/console.css"),changed);assertEvidenceBoundHistoriesPreserved(before,final);await originalStepsPreserved(f);assert.equal(final.status,"blocked");assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assert.deepEqual(await f.worker.runOnce(),{worked:false});
});

test("evidence-bound Hands rejects an injected ninth mutation after approved planning and preflight",async t=>{
  const f=await createEvidenceBoundReviewReplanFixture(t),before=await f.current();await f.authorize();await f.recover();await f.runSteps(10);f.hooks.execution=(name,args)=>{if(name==="repo_apply_patch")args.files.push({path:"test/ninth.test.js",operation:"create",content:"export const forbidden=true;\n"});};
  await assert.rejects(()=>f.worker.runOnce());const final=await f.current();assert.equal(final.status,"blocked");assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assertEvidenceBoundHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifySourceUnchanged();await assert.rejects(()=>f.read("test/ninth.test.js"),error=>error.code==="ENOENT");assert.deepEqual(await f.worker.runOnce(),{worked:false});
});
