import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createExecutionTruthService,projectExecutionTruth} from "../src/autonomy/execution-truth.js";
import {createLocalWorkerHandoff} from "../src/autonomy/local-worker-handoff.js";
import {createPersistentLocalWorker} from "../src/autonomy/persistent-local-worker.js";
import {SCHEMA_STATEMENTS,SCHEMA_VERSION} from "../src/storage/schema.js";

const OWNER="owner",TASK="coding_"+"a".repeat(32),BRANCH="feature",SHA="b".repeat(40);
test("schema twelve persists one fenced active attempt per task",()=>{assert.equal(SCHEMA_VERSION,12);const table=SCHEMA_STATEMENTS.find(statement=>statement.includes("CREATE TABLE IF NOT EXISTS nova_execution_attempts")),unique=SCHEMA_STATEMENTS.find(statement=>statement.includes("nova_execution_attempts_one_active_idx"));assert.match(table,/fence_token text NOT NULL/);assert.match(table,/executor_started boolean NOT NULL/);assert.match(table,/UNIQUE\(task_id,generation\)/);assert.match(unique,/WHERE status IN \('preparing','executing'\)/);});
async function fixture(){let ms=Date.parse("2026-09-28T12:00:00Z");const clock=()=>new Date(ms),storage=createInMemoryStorage({clock});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});const truth=createExecutionTruthService({storage,ownerId:OWNER,clock,leaseMs:60000});let task=await storage.createAutonomyTask({id:TASK,ownerId:OWNER,projectId:"nova-brain",title:"Coding",objective:"Bounded work",taskType:"coding_delegation",branch:BRANCH,startingCommit:SHA,currentCommit:SHA,maxSteps:3,maxRuntimeMinutes:120,metadata:{steps:[{type:"delegate_coding"}]}});task=await storage.updateAutonomyTask(TASK,OWNER,{status:"running",leaseOwner:"local:worker-one",leaseToken:"lease",leaseExpiresAt:new Date(ms+60000).toISOString(),metadata:{...task.metadata,localHandoff:{id:"handoff-one",workerId:"worker-one",stepId:"1:delegate_coding",stepType:"delegate_coding"}}},task.stateVersion);await storage.recordAutonomyStep({taskId:TASK,stepId:"1:delegate_coding",stepType:"delegate_coding",capability:"codex_local",operationFingerprint:"one",status:"running"});return{storage,truth,clock,advance:value=>{ms+=value;},task:()=>storage.getAutonomyTask(TASK,OWNER)};}

test("fresh fenced heartbeat is the only active execution truth and long runs renew it",async()=>{const f=await fixture(),task=await f.task(),attempt=await f.truth.start({task,handoff:task.metadata.localHandoff,workerId:"worker-one"});let projected=await f.truth.project(await f.task());assert.equal(projected.executionTruth.state,"preparing");assert.equal(projected.executionTruth.active,true);f.advance(45000);await f.truth.heartbeat({id:attempt.id,taskId:TASK,handoffId:"handoff-one",workerId:"worker-one",generation:attempt.generation,fenceToken:attempt.fenceToken},{phase:"testing",executorStarted:true,progress:true});f.advance(45000);projected=await f.truth.project(await f.task());assert.equal(projected.executionTruth.state,"executing");assert.equal(projected.executionTruth.phase,"testing");assert.equal(projected.executionTruth.active,true);});

test("worker loss before executor launch requeues once and fences the old generation",async()=>{const f=await fixture(),task=await f.task(),attempt=await f.truth.start({task,handoff:task.metadata.localHandoff,workerId:"worker-one"});f.advance(60001);assert.equal((await f.truth.project(await f.task())).executionTruth.state,"recovering");const first=await f.truth.reconcile({workerId:"worker-two"}),second=await f.truth.reconcile({workerId:"worker-two"}),updated=await f.task();assert.equal(first.length,1);assert.equal(second.length,0);assert.equal(updated.status,"waiting_for_worker");assert.equal(updated.errorCode,"execution_owner_lost_before_start");await assert.rejects(()=>f.truth.heartbeat({id:attempt.id,taskId:TASK,handoffId:"handoff-one",workerId:"worker-one",generation:attempt.generation,fenceToken:attempt.fenceToken},{phase:"executing",executorStarted:true}),error=>error.code==="execution_attempt_stale");});

for(const phase of["inspecting","implementing","testing","commit_creation","retained_ref_publication"]){test(`worker loss during ${phase} fails closed without re-execution`,async()=>{const f=await fixture(),task=await f.task(),attempt=await f.truth.start({task,handoff:task.metadata.localHandoff,workerId:"worker-one"});await f.truth.heartbeat({id:attempt.id,taskId:TASK,handoffId:"handoff-one",workerId:"worker-one",generation:attempt.generation,fenceToken:attempt.fenceToken},{phase,executorStarted:true,progress:true});f.advance(60001);await f.truth.reconcile({workerId:"worker-two"});const updated=await f.task();assert.equal(updated.status,"failed");assert.equal(updated.errorCode,"execution_owner_lost_after_start");assert.match(updated.blockedReason,/fresh owner-approved retry/);});}

test("legacy foreign-owner running handoff is reconciled fail-closed and never shown working",async()=>{const f=await fixture();const before=await f.truth.project(await f.task());assert.equal(before.executionTruth.state,"stalled");assert.equal(before.executionTruth.active,false);const result=await f.truth.reconcile({workerId:"replacement"}),updated=await f.task();assert.equal(result[0].legacy,true);assert.equal(updated.status,"failed");assert.equal(updated.errorCode,"legacy_execution_liveness_unproven");assert.equal(updated.metadata.localHandoff,null);});

test("waiting and terminal states never become active from stale historical progress",()=>{const base={currentPhase:"delegate_coding",updatedAt:"2026-09-28T12:00:00Z"},stale={status:"executing",executorStarted:true,phase:"testing",leaseExpiresAt:"2026-09-28T11:59:00Z",lastHeartbeatAt:"2026-09-28T11:58:00Z",claimedAt:"2026-09-28T11:50:00Z"};for(const status of["waiting_for_approval","waiting_for_worker","waiting","retrying"]){const truth=projectExecutionTruth({...base,status},stale,{clock:()=>new Date("2026-09-28T12:00:00Z")});assert.equal(truth.active,false);}for(const status of["completed","failed","blocked","cancelled","expired"]){const truth=projectExecutionTruth({...base,status,completedAt:"2026-09-28T11:59:30Z"},stale,{clock:()=>new Date("2026-09-28T12:00:00Z")});assert.equal(truth.state,"terminal");assert.equal(truth.active,false);}});

test("real handoff generations fence a late old worker and permit exactly one replacement claim",async()=>{let ms=Date.parse("2026-09-28T12:00:00Z");const clock=()=>new Date(ms),storage=createInMemoryStorage({clock});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});const truth=createExecutionTruthService({storage,ownerId:OWNER,clock,leaseMs:60000}),handoffs=createLocalWorkerHandoff({storage,ownerId:OWNER,approvedBranch:BRANCH,clock,executionTruth:truth});await storage.createAutonomyTask({id:TASK,ownerId:OWNER,projectId:"nova-brain",title:"Inspect",objective:"Inspect",taskType:"self_development",branch:BRANCH,startingCommit:SHA,currentCommit:SHA,maxSteps:2,maxRuntimeMinutes:120,metadata:{steps:[{type:"inspect_diff",input:{tool:"repo_diff",arguments:{}}}],requiredCapability:"repo_read_remote"}});const input={capabilities:["repo_read_remote"],expectedBranch:BRANCH,expectedCommit:SHA,taskId:TASK,runtimeVersion:"c".repeat(40),repository:"hshanbour/nova-brain",repositoryRoot:"C:/bound",continuationGenerationId:null};const first=await handoffs.claim({...input,workerId:"worker-one",idempotencyKey:"one"});assert.equal(first.claimed,true);assert.equal((await truth.project(await storage.getAutonomyTask(TASK,OWNER))).executionTruth.state,"preparing");ms+=60001;await truth.reconcile({workerId:"worker-two"});const second=await handoffs.claim({...input,workerId:"worker-two",idempotencyKey:"two"});assert.equal(second.claimed,true);assert.equal(second.handoff.executionAttempt.generation,2);await assert.rejects(()=>handoffs.complete(first.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"one",executionAttempt:first.handoff.executionAttempt,result:{ok:true,exitCode:0}}),error=>["handoff_mismatch","execution_attempt_stale"].includes(error.code));await handoffs.complete(second.handoff.handoffId,{taskId:TASK,workerId:"worker-two",idempotencyKey:"two",executionAttempt:second.handoff.executionAttempt,result:{ok:true,exitCode:0}});assert.equal((await storage.getLatestExecutionAttempt(TASK,OWNER)).status,"completed");assert.equal((await storage.listAutonomySteps(TASK))[0].attempt,2);});

test("replayed claim returns the same fenced attempt and cannot create a duplicate generation",async()=>{let ms=Date.parse("2026-09-28T12:00:00Z");const clock=()=>new Date(ms),storage=createInMemoryStorage({clock});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});const truth=createExecutionTruthService({storage,ownerId:OWNER,clock}),handoffs=createLocalWorkerHandoff({storage,ownerId:OWNER,approvedBranch:BRANCH,clock,executionTruth:truth});await storage.createAutonomyTask({id:TASK,ownerId:OWNER,projectId:"nova-brain",title:"Inspect",objective:"Inspect",branch:BRANCH,startingCommit:SHA,currentCommit:SHA,maxSteps:1,metadata:{steps:[{type:"inspect_diff",input:{tool:"repo_diff",arguments:{}}}],requiredCapability:"repo_read_remote"}});const input={workerId:"worker-one",idempotencyKey:"stable",capabilities:["repo_read_remote"],expectedBranch:BRANCH,expectedCommit:SHA,taskId:TASK,runtimeVersion:"c".repeat(40),repository:"hshanbour/nova-brain",repositoryRoot:"C:/bound"},first=await handoffs.claim(input),replay=await handoffs.claim(input);assert.equal(replay.idempotent,true);assert.deepEqual(replay.handoff.executionAttempt,first.handoff.executionAttempt);assert.equal((await storage.listActiveExecutionAttempts(OWNER)).length,1);});

test("persistent worker carries the server-issued fence through heartbeat and terminal completion",async()=>{const attempt={id:"attempt-one",generation:1,fenceToken:"fence-one"},calls=[],client={async request(path,body){calls.push({path,body});if(path.endsWith("/next"))return{dispatched:true,task:{id:TASK,status:"waiting_for_worker",branch:BRANCH,expectedCommit:SHA,stateVersion:1,mode:"local_handoff",stepType:"inspect_diff"}};if(path.endsWith("/claim"))return{claimed:true,handoff:{handoffId:"handoff-one",taskId:TASK,stepId:"1:inspect_diff",stepType:"inspect_diff",branch:BRANCH,expectedCommit:SHA,tool:"repo_diff",arguments:{},executionAttempt:attempt}};return{status:"completed"};}},registry={async execute(_tool,_args,context){assert.deepEqual(context.executionAttempt,attempt);return{ok:true,files:[]};}},worker=createPersistentLocalWorker({client,root:"C:/bound",branch:BRANCH,workerId:"worker-one",registry});const result=await worker.runOnce();assert.equal(result.status,"completed");const heartbeats=calls.filter(call=>call.path.includes("/execution-attempts/"));assert.equal(heartbeats.length,2);assert.equal(heartbeats[0].body.phase,"preparing");assert.equal(heartbeats[1].body.phase,"executing");assert.deepEqual(calls.find(call=>call.path.endsWith("/complete")).body.executionAttempt,attempt);});

test("cancellation and terminal state stop active display even with a fresh attempt",async()=>{const f=await fixture(),attempt=await f.truth.start({task:await f.task(),handoffId:"handoff-one",handoff:(await f.task()).metadata.localHandoff,workerId:"worker-one"}),task=await f.task(),cancelled=await f.storage.updateAutonomyTask(TASK,OWNER,{status:"cancelled",completedAt:f.clock().toISOString()},task.stateVersion),projected=await f.truth.project(cancelled);assert.equal(projected.executionTruth.state,"terminal");assert.equal(projected.executionTruth.active,false);await f.truth.reconcile({workerId:"worker-one"});assert.equal((await f.storage.getLatestExecutionAttempt(TASK,OWNER)).status,"superseded");assert.ok(attempt.id);});
