import test from "node:test";
import assert from "node:assert/strict";
import {EventEmitter} from "node:events";
import {PassThrough} from "node:stream";
import {LOCAL_WORKER_CREDENTIALS,createLocalWorkerCredentialManager,createWindowsCredentialStore,loadLocalWorkerCredentials} from "../src/autonomy/local-worker-credentials.js";
import {parsePersistentWorkerArguments} from "../src/autonomy/persistent-worker-cli.js";

const secret=value=>`${value}-`.repeat(20),scope={environment:"preview",branch:"feat/nova-brain-mvp-foundation"};
function memoryStore(){const values=new Map();return{storage:"secure_os_store",async get(k){if(!values.has(k))throw Object.assign(new Error("credential_missing"),{code:"credential_missing"});return values.get(k);},async set(k,v){values.set(k,v);return{configured:true,storage:this.storage};},async delete(k){return{deleted:values.delete(k),storage:this.storage};},async status(k){return{configured:values.has(k),storage:this.storage};},values};}
function helperChild(pid=4242){const child=new EventEmitter();child.pid=pid;child.exitCode=null;child.stdin=new PassThrough();child.stdout=new PassThrough();child.stderr=new PassThrough();child.kill=()=>{child.killed=true;};return child;}
function successfulSpawn(values,calls=[]){return(file,args,options)=>{const child=helperChild(4200+calls.length);calls.push({file,args,options,child});queueMicrotask(()=>{child.stderr.write("NOVA_STAGE:powershell_started\nNOVA_STAGE:native_api_loaded\nNOVA_STAGE:credential_api_read\nNOVA_STAGE:credential_api_complete\n");const action=args.at(-3)==="get-pair"?"get-pair":args.at(-2),targets=action==="get-pair"?args.slice(-2):[args.at(-1)],found=targets.every(target=>values.has(target));const output=action==="get-pair"&&found?JSON.stringify(targets.map(target=>Buffer.from(values.get(target)).toString("base64"))):values.get(targets[0])||"";child.stdout.end(output);child.stderr.end();child.exitCode=found?0:3;child.emit("close",child.exitCode);});return child;};}
function failedSpawn({code=1,stage="powershell_started",safeError,stdout="",stderr=""}={}){return()=>{const child=helperChild(4600);queueMicrotask(()=>{child.stderr.write(`NOVA_STAGE:${stage}\n${safeError?`NOVA_ERROR:${safeError}\n`:""}${stderr}`);child.stdout.end(stdout);child.stderr.end();child.exitCode=code;child.emit("close",code);});return child;};}

test("secure initialization and restart load persistent separate credentials",async()=>{const store=memoryStore();await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("nova"));await store.set(LOCAL_WORKER_CREDENTIALS.vercel,secret("vercel"));const first=await loadLocalWorkerCredentials({environment:{},store});first.clear();assert.equal((await store.status(LOCAL_WORKER_CREDENTIALS.nova)).configured,true);const restarted=await loadLocalWorkerCredentials({environment:{},store});assert.notEqual(restarted.novaToken,restarted.vercelBypassToken);});
test("missing credentials fail closed and transient references clear",async()=>{const store=memoryStore();await assert.rejects(()=>loadLocalWorkerCredentials({environment:{},store}),e=>e.code==="credential_missing");await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("nova"));await store.set(LOCAL_WORKER_CREDENTIALS.vercel,secret("vercel"));const loaded=await loadLocalWorkerCredentials({environment:{},store});loaded.clear();assert.equal(loaded.novaToken,null);assert.equal(loaded.vercelBypassToken,null);});
test("rotation synchronizes server and store without exposing the value",async()=>{const store=memoryStore();let serverValue,verified;const manager=createLocalWorkerCredentialManager({store,generate:()=>secret("fresh"),serverSync:async value=>{serverValue=value;},verify:async value=>{verified=value===serverValue;}});const result=await manager.rotateNova(scope);assert.equal(verified,true);assert.deepEqual(result,{configured:true,storage:"secure_os_store",environment:"preview",branch:scope.branch});assert.doesNotMatch(JSON.stringify(result),/fresh/);assert.equal((await manager.status()).nova.configured,true);});
test("failed rotation deletes ambiguous local state and reports recovery side",async()=>{const store=memoryStore(),manager=createLocalWorkerCredentialManager({store,generate:()=>secret("fresh"),serverSync:async()=>{},verify:async()=>{throw new Error("invalid");}});await assert.rejects(()=>manager.rotateNova(scope),e=>e.code==="credential_rotation_incomplete"&&e.recovery==="local_secure_store");assert.equal((await manager.status()).nova.configured,false);});
test("delete revoke and metadata-only status never return raw credentials",async()=>{const store=memoryStore();await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("private"));const manager=createLocalWorkerCredentialManager({store});const status=await manager.status();assert.deepEqual(status.nova,{configured:true,storage:"secure_os_store"});assert.doesNotMatch(JSON.stringify(status),/private/);assert.equal((await manager.delete(LOCAL_WORKER_CREDENTIALS.nova)).deleted,true);});
test("main and Production credential scopes are rejected",async()=>{const store=memoryStore(),manager=createLocalWorkerCredentialManager({store,serverSync:async()=>{},verify:async()=>{}});for(const bad of [{environment:"production",branch:scope.branch},{environment:"preview",branch:"main"}])await assert.rejects(()=>manager.rotateNova(bad),e=>e.code==="credential_scope_forbidden");});
test("Windows helper uses absolute hidden noninteractive PowerShell without profile or read stdin",async()=>{const calls=[],values=new Map([["NovaBrain/LocalWorker/NOVA_LOCAL_WORKER_TOKEN",secret("nova")]]),store=createWindowsCredentialStore({platform:"win32",environment:{SystemRoot:"C:\\Windows"},spawn:successfulSpawn(values,calls)});assert.equal((await store.get(LOCAL_WORKER_CREDENTIALS.nova)).startsWith("nova-"),true);const call=calls[0];assert.equal(call.file,"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe");assert.deepEqual(call.args.slice(0,6),["-NoLogo","-NoProfile","-NonInteractive","-ExecutionPolicy","Bypass","-File"]);assert.equal(call.options.windowsHide,true);assert.equal(call.options.stdio[0],"ignore");});
test("both credential types use one noninteractive native helper initialization",async()=>{const calls=[],values=new Map([["NovaBrain/LocalWorker/NOVA_LOCAL_WORKER_TOKEN",secret("nova")],["NovaBrain/LocalWorker/VERCEL_AUTOMATION_BYPASS",secret("vercel")]]),store=createWindowsCredentialStore({platform:"win32",spawn:successfulSpawn(values,calls)}),loaded=await loadLocalWorkerCredentials({environment:{},store});assert.notEqual(loaded.novaToken,loaded.vercelBypassToken);assert.equal(calls.length,1);assert.deepEqual(calls[0].args.slice(-3),["get-pair","NovaBrain/LocalWorker/NOVA_LOCAL_WORKER_TOKEN","NovaBrain/LocalWorker/VERCEL_AUTOMATION_BYPASS"]);assert.equal(calls[0].options.stdio[0],"ignore");loaded.clear();});
test("installed native helper receives an exact shell-free combined argument vector",async()=>{const calls=[],values=new Map([["NovaBrain/LocalWorker/NOVA_LOCAL_WORKER_TOKEN",secret("nova")],["NovaBrain/LocalWorker/VERCEL_AUTOMATION_BYPASS",secret("vercel")]]),helper="C:\\Users\\owner\\AppData\\Local\\NovaBrain\\PersistentWorker\\NovaCredentialHelper.exe",store=createWindowsCredentialStore({platform:"win32",helperExecutable:helper,requireNativeHelper:true,exists:()=>true,spawn:successfulSpawn(values,calls)});await loadLocalWorkerCredentials({environment:{},store});assert.equal(calls[0].file,helper);assert.deepEqual(calls[0].args,["get-pair","NovaBrain/LocalWorker/NOVA_LOCAL_WORKER_TOKEN","NovaBrain/LocalWorker/VERCEL_AUTOMATION_BYPASS"]);assert.equal(calls[0].options.shell,false);assert.deepEqual(store.helper,{kind:"native",executable:helper,selectionSource:"worker_cli",nativeExists:true,fallbackUsed:false});});
test("native startup handshake advances through script native CredRead and output stages",async()=>{const child=helperChild(),store=createWindowsCredentialStore({platform:"win32",helperExecutable:"C:\\safe\\NovaCredentialHelper.exe",exists:()=>true,spawn:()=>{queueMicrotask(()=>{child.stderr.end("NOVA_STAGE:script_started\nNOVA_STAGE:native_api_loading\nNOVA_STAGE:native_api_loaded\nNOVA_STAGE:credread_start\nNOVA_STAGE:credread_complete\nNOVA_STAGE:output_complete\n");child.stdout.end(secret("nova"));child.exitCode=0;child.emit("close",0);});return child;}});assert.equal((await store.get(LOCAL_WORKER_CREDENTIALS.nova)).startsWith("nova-"),true);});
test("helper timeout identifies native stage, kills the process tree, and leaves no orphan",async()=>{const child=helperChild(7331),killed=[];let alive=true;const store=createWindowsCredentialStore({platform:"win32",helperTimeoutMs:5,spawn:()=>{queueMicrotask(()=>child.stderr.write("NOVA_STAGE:powershell_started\nNOVA_STAGE:native_api_loaded\n"));return child;},killTree:async pid=>{killed.push(pid);alive=false;},isAlive:()=>alive});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.nova),error=>{assert.equal(error.code,"credential_helper_timeout");assert.equal(error.safeDiagnostics.stage,"native_api_loaded_timeout");assert.equal(error.safeDiagnostics.childAliveAfterTimeout,false);assert.equal(error.safeDiagnostics.stdoutBytes,0);assert.ok(error.safeDiagnostics.stderrBytes>0);assert.doesNotMatch(JSON.stringify(error.safeDiagnostics),/nova-nova|vercel-vercel/);return true;});assert.deepEqual(killed,[7331]);assert.equal(child.killed,undefined);});
test("malformed helper stdout is rejected without returning material",async()=>{const values=new Map([["NovaBrain/LocalWorker/NOVA_LOCAL_WORKER_TOKEN","secret\nextra"]]),store=createWindowsCredentialStore({platform:"win32",spawn:successfulSpawn(values)});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.nova),error=>error.code==="credential_helper_output_invalid"&&!JSON.stringify(error.safeDiagnostics).includes("secret"));});
test("missing credential is distinct from helper timeout",async()=>{const store=createWindowsCredentialStore({platform:"win32",spawn:successfulSpawn(new Map())});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.vercel),error=>error.code==="credential_missing"&&error.safeDiagnostics.credentialType==="vercel_bypass");});
test("helper exit code one after PowerShell start is a native API load failure, not a timeout",async()=>{const store=createWindowsCredentialStore({platform:"win32",spawn:failedSpawn({code:1})});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.vercel),error=>error.code==="credential_native_api_load_failed"&&error.safeDiagnostics.stage==="powershell_started"&&error.safeDiagnostics.exitCode===1);});
test("explicit Add-Type and CredRead failures receive distinct safe classifications",async()=>{for(const input of[{safeError:"add_type_failed",expected:"credential_native_api_load_failed"},{stage:"credential_api_read",safeError:"credential_read_failed",expected:"credential_read_failed"}]){const store=createWindowsCredentialStore({platform:"win32",spawn:failedSpawn(input)});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.nova),error=>error.code===input.expected&&!JSON.stringify(error.safeDiagnostics).includes(secret("nova")));}});
test("malformed helper target arguments fail closed without exposing stderr",async()=>{const store=createWindowsCredentialStore({platform:"win32",spawn:failedSpawn({code:2,safeError:"invalid_arguments",stderr:"sensitive material must remain unread"})});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.vercel),error=>error.code==="credential_helper_arguments_invalid"&&error.safeDiagnostics.stderrBytes>0&&!JSON.stringify(error).includes("sensitive material"));});
test("empty stdout with bounded stderr and ordinary exit is not reported as timeout",async()=>{const store=createWindowsCredentialStore({platform:"win32",spawn:failedSpawn({code:1,stage:"native_api_loaded",stderr:"bounded diagnostic"})});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.vercel),error=>error.code==="credential_helper_process_failed"&&error.safeDiagnostics.stdoutBytes===0&&error.safeDiagnostics.stderrBytes>0);});
test("exit before startup handshake is script-not-entered and never timeout",async()=>{const store=createWindowsCredentialStore({platform:"win32",helperExecutable:"C:\\safe\\NovaCredentialHelper.exe",exists:()=>true,spawn:failedSpawn({code:1,stage:"process_start"})});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.vercel),error=>error.code==="credential_helper_script_not_entered"&&error.safeDiagnostics.helperKind==="native"&&error.safeDiagnostics.stage==="process_start");});
test("parameter binding failure is distinct and diagnostics expose only argv shape",async()=>{const store=createWindowsCredentialStore({platform:"win32",spawn:failedSpawn({code:2,safeError:"parameter_binding_failed"})});await assert.rejects(()=>store.get(LOCAL_WORKER_CREDENTIALS.nova),error=>error.code==="credential_helper_parameter_binding_failed"&&error.safeDiagnostics.helperArgvShape.includes("script")&&!JSON.stringify(error.safeDiagnostics).includes("NOVA_LOCAL_WORKER_TOKEN"));});
test("persistent worker CLI preserves the exact native helper binding across restart",()=>{const helper="C:\\Users\\owner\\AppData\\Local\\NovaBrain\\PersistentWorker\\NovaCredentialHelper.exe",parsed=parsePersistentWorkerArguments(["node","worker","--preview-url","https://preview.vercel.app","--git-executable","C:\\git.exe","--credential-helper",helper]);assert.equal(parsed.credentialHelper,helper);assert.equal(parsed.previewUrl,"https://preview.vercel.app");});
test("persistent worker fails closed when configured native helper is missing or malformed",()=>{for(const helperExecutable of["C:\\missing\\NovaCredentialHelper.exe","relative-helper.exe",""])assert.throws(()=>createWindowsCredentialStore({platform:"win32",helperExecutable,requireNativeHelper:true,exists:()=>false}),error=>error.code==="credential_native_helper_required"&&error.safeDiagnostics.fallbackUsed===false);});
test("credential loading reports each safe source and type without values",async()=>{const store=memoryStore(),stages=[];await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("nova"));await store.set(LOCAL_WORKER_CREDENTIALS.vercel,secret("vercel"));const loaded=await loadLocalWorkerCredentials({environment:{},store,onStage:async stage=>stages.push(stage)});assert.deepEqual(stages.map(({credentialType,stage})=>`${credentialType}:${stage}`),["nova_worker:loading","nova_worker:loaded","vercel_bypass:loading","vercel_bypass:loaded"]);assert.doesNotMatch(JSON.stringify(stages),/nova-|vercel-/);loaded.clear();});
