import test from "node:test";
import assert from "node:assert/strict";
import {LOCAL_WORKER_CREDENTIALS,createLocalWorkerCredentialManager,loadLocalWorkerCredentials} from "../src/autonomy/local-worker-credentials.js";

const secret=value=>`${value}-`.repeat(20),scope={environment:"preview",branch:"feat/nova-brain-mvp-foundation"};
function memoryStore(){const values=new Map();return{storage:"secure_os_store",async get(k){if(!values.has(k))throw Object.assign(new Error("credential_missing"),{code:"credential_missing"});return values.get(k);},async set(k,v){values.set(k,v);return{configured:true,storage:this.storage};},async delete(k){return{deleted:values.delete(k),storage:this.storage};},async status(k){return{configured:values.has(k),storage:this.storage};},values};}

test("secure initialization and restart load persistent separate credentials",async()=>{const store=memoryStore();await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("nova"));await store.set(LOCAL_WORKER_CREDENTIALS.vercel,secret("vercel"));const first=await loadLocalWorkerCredentials({environment:{},store});first.clear();assert.equal((await store.status(LOCAL_WORKER_CREDENTIALS.nova)).configured,true);const restarted=await loadLocalWorkerCredentials({environment:{},store});assert.notEqual(restarted.novaToken,restarted.vercelBypassToken);});
test("missing credentials fail closed and transient references clear",async()=>{const store=memoryStore();await assert.rejects(()=>loadLocalWorkerCredentials({environment:{},store}),e=>e.code==="credential_missing");await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("nova"));await store.set(LOCAL_WORKER_CREDENTIALS.vercel,secret("vercel"));const loaded=await loadLocalWorkerCredentials({environment:{},store});loaded.clear();assert.equal(loaded.novaToken,null);assert.equal(loaded.vercelBypassToken,null);});
test("rotation synchronizes server and store without exposing the value",async()=>{const store=memoryStore();let serverValue,verified;const manager=createLocalWorkerCredentialManager({store,generate:()=>secret("fresh"),serverSync:async value=>{serverValue=value;},verify:async value=>{verified=value===serverValue;}});const result=await manager.rotateNova(scope);assert.equal(verified,true);assert.deepEqual(result,{configured:true,storage:"secure_os_store",environment:"preview",branch:scope.branch});assert.doesNotMatch(JSON.stringify(result),/fresh/);assert.equal((await manager.status()).nova.configured,true);});
test("failed rotation deletes ambiguous local state and reports recovery side",async()=>{const store=memoryStore(),manager=createLocalWorkerCredentialManager({store,generate:()=>secret("fresh"),serverSync:async()=>{},verify:async()=>{throw new Error("invalid");}});await assert.rejects(()=>manager.rotateNova(scope),e=>e.code==="credential_rotation_incomplete"&&e.recovery==="local_secure_store");assert.equal((await manager.status()).nova.configured,false);});
test("delete revoke and metadata-only status never return raw credentials",async()=>{const store=memoryStore();await store.set(LOCAL_WORKER_CREDENTIALS.nova,secret("private"));const manager=createLocalWorkerCredentialManager({store});const status=await manager.status();assert.deepEqual(status.nova,{configured:true,storage:"secure_os_store"});assert.doesNotMatch(JSON.stringify(status),/private/);assert.equal((await manager.delete(LOCAL_WORKER_CREDENTIALS.nova)).deleted,true);});
test("main and Production credential scopes are rejected",async()=>{const store=memoryStore(),manager=createLocalWorkerCredentialManager({store,serverSync:async()=>{},verify:async()=>{}});for(const bad of [{environment:"production",branch:scope.branch},{environment:"preview",branch:"main"}])await assert.rejects(()=>manager.rotateNova(bad),e=>e.code==="credential_scope_forbidden");});
