import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {authorizeLocalWorker,createLocalWorkerHandoff} from "../src/autonomy/local-worker-handoff.js";
import {createLocalWorkerClient} from "../src/autonomy/local-worker-client.js";

const OWNER="owner",TASK="task",BRANCH="feat/nova-brain-mvp-foundation",SHA="a".repeat(40),TOKEN="local-secret";
const plans={patch:{type:"apply_patch",input:{tool:"repo_apply_patch",arguments:{branch:BRANCH,files:[{path:"docs/handoff.md",content:"safe"}]}}},test:{type:"run_focused_tests",input:{tool:"test_run",arguments:{files:["test/worker-runtime.test.js"],timeoutMs:1000}}},commit:{type:"commit",input:{tool:"git_commit",arguments:{branch:BRANCH,message:"safe",paths:["docs/handoff.md"]}}}};
async function fixture({plan=plans.patch,status="queued",deploymentEnvironment="preview"}={}){let instant=new Date("2026-09-06T01:00:00Z");const clock=()=>new Date(instant);const storage=createInMemoryStorage({clock});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova",name:"Nova"}]});await storage.createAutonomyTask({id:TASK,ownerId:OWNER,projectId:"nova",title:"Handoff",objective:"Test",branch:BRANCH,startingCommit:SHA,maxRuntimeMinutes:90,metadata:{steps:[plan],requiredCapability:plan.type==="run_focused_tests"?"test_local":"repo_mutate_local"}});if(status!=="queued")await storage.updateAutonomyTask(TASK,OWNER,{status});const service=createLocalWorkerHandoff({storage,ownerId:OWNER,approvedBranch:BRANCH,clock,leaseMs:30000,deploymentEnvironment});return{storage,service,advance:ms=>{instant=new Date(instant.getTime()+ms);}};}
const claim=(service,overrides={})=>service.claim({workerId:"worker-one",capabilities:["repo_mutate_local","test_local","repo_read_remote"],expectedBranch:BRANCH,expectedCommit:SHA,taskId:TASK,idempotencyKey:"claim-one",...overrides});

test("local Worker authentication is scoped and timing-safe",()=>{assert.deepEqual(authorizeLocalWorker({headers:{authorization:`Bearer ${TOKEN}`}},TOKEN),{actorType:"scoped_local_worker"});for(const header of [undefined,"Bearer wrong"])assert.throws(()=>authorizeLocalWorker({headers:{authorization:header}},TOKEN),error=>error.code==="unauthorized");assert.throws(()=>authorizeLocalWorker({headers:{}},null),error=>error.code==="handoff_not_configured");});

test("local client requires separate Vercel and Nova credentials",()=>{for(const input of [{baseUrl:"https://preview.example",novaToken:TOKEN},{baseUrl:"https://preview.example",novaToken:TOKEN,vercelBypassToken:TOKEN}])assert.throws(()=>createLocalWorkerClient(input));});

test("local client sends both authentication layers without returning them",async()=>{let request;const client=createLocalWorkerClient({baseUrl:"https://preview.example",novaToken:TOKEN,vercelBypassToken:"vercel-bypass",fetchImpl:async(_url,input)=>{request=input;return{ok:true,async json(){return{claimed:true};}};}});assert.deepEqual(await client.request("/claim",{taskId:TASK}),{claimed:true});assert.equal(request.headers.Authorization,`Bearer ${TOKEN}`);assert.equal(request.headers["x-vercel-protection-bypass"],"vercel-bypass");assert.doesNotMatch(JSON.stringify(await client.request("/claim",{})),new RegExp(`${TOKEN}|vercel-bypass`));});

test("missing Vercel bypass is rejected before Nova authorization",()=>{let novaReached=false;const gateway=({bypass,nova})=>{if(bypass!=="vercel-bypass")return{status:401,layer:"vercel"};novaReached=true;try{authorizeLocalWorker({headers:{authorization:nova}},TOKEN);return{status:200,layer:"nova"};}catch(error){return{status:error.statusCode,layer:"nova"};}};assert.deepEqual(gateway({nova:`Bearer ${TOKEN}`}),{status:401,layer:"vercel"});assert.equal(novaReached,false);});

test("valid Vercel bypass still requires the current Nova token",()=>{const gateway=nova=>{try{authorizeLocalWorker({headers:{authorization:nova}},TOKEN);return 200;}catch(error){return error.statusCode;}};assert.equal(gateway(undefined),401);assert.equal(gateway("Bearer compromised-old-token"),401);assert.equal(gateway(`Bearer ${TOKEN}`),200);});
test("authenticated exact-task claim returns one bounded server step without secrets",async()=>{const f=await fixture(),before=await f.storage.getAutonomyTask(TASK,OWNER),result=await claim(f.service);assert.equal(result.claimed,true);assert.equal(result.handoff.tool,"repo_apply_patch");assert.deepEqual(Object.keys(result.handoff).sort(),["arguments","branch","deadline","expectedCommit","handoffId","idempotencyKey","repository","stepId","stepType","taskId","tool"].sort());assert.doesNotMatch(JSON.stringify(result),/leaseToken|DATABASE_URL|password/);assert.ok((await f.storage.getAutonomyTask(TASK,OWNER)).stateVersion>before.stateVersion);});
test("capability mismatch and ineligible state return no task",async()=>{const f=await fixture();assert.equal((await claim(f.service,{capabilities:["test_local"]})).claimed,false);const blocked=await fixture({status:"completed"});assert.equal((await claim(blocked.service)).claimed,false);});
test("duplicate claim is idempotent while another worker cannot steal it",async()=>{const f=await fixture(),first=await claim(f.service),again=await claim(f.service),other=await claim(f.service,{workerId:"worker-two",idempotencyKey:"other"});assert.equal(again.idempotent,true);assert.equal(again.handoff.handoffId,first.handoff.handoffId);assert.equal(other.claimed,false);});
test("completion advances the exact step checkpoint and duplicate result is idempotent",async()=>{const f=await fixture(),claimed=await claim(f.service),before=(await f.storage.getAutonomyTask(TASK,OWNER)).stateVersion,input={taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,files:["docs/handoff.md"]}};const completed=await f.service.complete(claimed.handoff.handoffId,input);assert.equal(completed.task.currentStep,1);assert.ok(completed.task.stateVersion>before);assert.equal((await f.storage.listAutonomySteps(TASK))[0].status,"completed");assert.equal((await f.service.complete(claimed.handoff.handoffId,input)).idempotent,true);});
test("wrong handoff worker or idempotency key is rejected",async()=>{const f=await fixture(),claimed=await claim(f.service);for(const [id,input] of [["wrong",{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true}}],[claimed.handoff.handoffId,{taskId:TASK,workerId:"other",idempotencyKey:"claim-one",result:{ok:true}}],[claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"other",result:{ok:true}}]])await assert.rejects(()=>f.service.complete(id,input),error=>error.code==="handoff_mismatch");});
test("expired handoff is rejected requeued and can be reclaimed without rerunning completion",async()=>{const f=await fixture(),claimed=await claim(f.service);f.advance(30001);await assert.rejects(()=>f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true}}),error=>error.code==="handoff_expired");assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).status,"queued");assert.equal((await claim(f.service,{idempotencyKey:"claim-two"})).claimed,true);});
test("branch commit protected branches and Production fail closed",async()=>{for(const [overrides,code] of [[{expectedBranch:"main"},"branch_not_allowed"],[{expectedBranch:"master"},"branch_not_allowed"],[{expectedBranch:"other"},"branch_not_allowed"],[{expectedCommit:"b".repeat(40)},"commit_mismatch"]]){const f=await fixture();await assert.rejects(()=>claim(f.service,overrides),error=>error.code===code);}const production=await fixture({deploymentEnvironment:"production"});await assert.rejects(()=>claim(production.service),error=>error.code==="production_target_forbidden");});
test("invalid client result cannot mutate task state",async()=>{const f=await fixture(),claimed=await claim(f.service),before=await f.storage.getAutonomyTask(TASK,OWNER);await assert.rejects(()=>f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:false,databaseUrl:"secret"}}),error=>error.code==="invalid_handoff_result");assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).currentStep,before.currentStep);});
test("structured failure follows bounded retry policy without arbitrary status control",async()=>{const f=await fixture(),claimed=await claim(f.service),failed=await f.service.fail(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",error:{code:"worker_crash",message:"safe",status:"completed"}});assert.equal(failed.status,"retrying");assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).status,"retrying");});
test("local commit persists exact SHA and stops at public push approval",async()=>{const f=await fixture({plan:plans.commit}),claimed=await claim(f.service),next="b".repeat(40),completed=await f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,commitSha:next,files:["docs/handoff.md"]}}),task=await f.storage.getAutonomyTask(TASK,OWNER);assert.equal(completed.status,"waiting_for_approval");assert.equal(task.currentCommit,next);assert.equal(task.approvalState.tool,"git_push");assert.deepEqual(task.approvalState.arguments,{branch:BRANCH,commitSha:next});assert.equal((await f.storage.listApprovals(OWNER))[0].status,"pending");assert.equal((await f.storage.listActivity(OWNER,{runId:TASK})).some(item=>item.tool==="git_push"&&item.status==="completed"),false);});
test("handoff Activity is durable and redacts submitted secrets",async()=>{const f=await fixture(),claimed=await claim(f.service);await f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,files:["docs/handoff.md"],apiKey:"should-not-survive"}});const activity=await f.storage.listActivity(OWNER,{runId:TASK});assert.ok(activity.some(item=>item.action==="local_worker_handoff_created"));assert.ok(activity.some(item=>item.action==="local_worker_handoff_completed"));assert.doesNotMatch(JSON.stringify(activity),/should-not-survive/);});
test("completed handoff cannot rerun after reconnect",async()=>{const f=await fixture(),claimed=await claim(f.service),input={taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,files:["docs/handoff.md"]}};await f.service.complete(claimed.handoff.handoffId,input);assert.equal((await f.service.complete(claimed.handoff.handoffId,input)).idempotent,true);assert.equal((await f.storage.listAutonomySteps(TASK)).length,1);});
