import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {authorizeLocalWorker,createLocalWorkerHandoff} from "../src/autonomy/local-worker-handoff.js";
import {createLocalWorkerClient} from "../src/autonomy/local-worker-client.js";
import {bindImplementationPlan} from "../src/autonomy/self-development-plan-lifecycle.js";

const OWNER="owner",TASK="task",BRANCH="feat/nova-brain-mvp-foundation",SHA="a".repeat(40),TOKEN="local-secret";
const plans={patch:{type:"apply_patch",input:{tool:"repo_apply_patch",arguments:{branch:BRANCH,files:[{path:"docs/handoff.md",content:"safe"}]}}},test:{type:"run_focused_tests",input:{tool:"test_run",arguments:{files:["test/worker-runtime.test.js"],timeoutMs:1000}}},commit:{type:"commit",input:{tool:"git_commit",arguments:{branch:BRANCH,message:"safe",paths:["docs/handoff.md"]}}}};
async function fixture({plan=plans.patch,status="queued",deploymentEnvironment="preview"}={}){let instant=new Date("2026-09-06T01:00:00Z");const clock=()=>new Date(instant);const storage=createInMemoryStorage({clock});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova",name:"Nova"}]});await storage.createAutonomyTask({id:TASK,ownerId:OWNER,projectId:"nova",title:"Handoff",objective:"Test",branch:BRANCH,startingCommit:SHA,maxRuntimeMinutes:90,metadata:{steps:[plan],requiredCapability:plan.type==="run_focused_tests"?"test_local":"repo_mutate_local"}});if(status!=="queued")await storage.updateAutonomyTask(TASK,OWNER,{status});const service=createLocalWorkerHandoff({storage,ownerId:OWNER,approvedBranch:BRANCH,clock,leaseMs:30000,deploymentEnvironment});return{storage,service,advance:ms=>{instant=new Date(instant.getTime()+ms);}};}
const claim=(service,overrides={})=>service.claim({workerId:"worker-one",capabilities:["repo_mutate_local","test_local","repo_read_remote"],expectedBranch:BRANCH,expectedCommit:SHA,taskId:TASK,idempotencyKey:"claim-one",...overrides});

test("local Worker authentication is scoped and timing-safe",()=>{assert.deepEqual(authorizeLocalWorker({headers:{authorization:`Bearer ${TOKEN}`}},TOKEN),{actorType:"scoped_local_worker"});for(const header of [undefined,"Bearer wrong"])assert.throws(()=>authorizeLocalWorker({headers:{authorization:header}},TOKEN),error=>error.code==="unauthorized");assert.throws(()=>authorizeLocalWorker({headers:{}},null),error=>error.code==="handoff_not_configured");});

test("local client requires separate Vercel and Nova credentials",()=>{for(const input of [{baseUrl:"https://preview.example",novaToken:TOKEN},{baseUrl:"https://preview.example",novaToken:TOKEN,vercelBypassToken:TOKEN}])assert.throws(()=>createLocalWorkerClient(input));});

test("local client sends both authentication layers without returning them",async()=>{let request;const client=createLocalWorkerClient({baseUrl:"https://preview.example",novaToken:TOKEN,vercelBypassToken:"vercel-bypass",fetchImpl:async(_url,input)=>{request=input;return{ok:true,async json(){return{claimed:true};}};}});assert.deepEqual(await client.request("/claim",{taskId:TASK}),{claimed:true});assert.equal(request.headers.Authorization,`Bearer ${TOKEN}`);assert.equal(request.headers["x-vercel-protection-bypass"],"vercel-bypass");assert.doesNotMatch(JSON.stringify(await client.request("/claim",{})),new RegExp(`${TOKEN}|vercel-bypass`));});
test("local client applies a bounded abort signal to protected requests",async()=>{let signal;const client=createLocalWorkerClient({baseUrl:"https://preview.example",novaToken:TOKEN,vercelBypassToken:"vercel-bypass",requestTimeoutMs:1234,fetchImpl:async(_url,input)=>{signal=input.signal;return{ok:true,async json(){return{};}};}});await client.request("/probe",{});assert.equal(signal instanceof AbortSignal,true);assert.equal(signal.aborted,false);});

test("missing Vercel bypass is rejected before Nova authorization",()=>{let novaReached=false;const gateway=({bypass,nova})=>{if(bypass!=="vercel-bypass")return{status:401,layer:"vercel"};novaReached=true;try{authorizeLocalWorker({headers:{authorization:nova}},TOKEN);return{status:200,layer:"nova"};}catch(error){return{status:error.statusCode,layer:"nova"};}};assert.deepEqual(gateway({nova:`Bearer ${TOKEN}`}),{status:401,layer:"vercel"});assert.equal(novaReached,false);});

test("valid Vercel bypass still requires the current Nova token",()=>{const gateway=nova=>{try{authorizeLocalWorker({headers:{authorization:nova}},TOKEN);return 200;}catch(error){return error.statusCode;}};assert.equal(gateway(undefined),401);assert.equal(gateway("Bearer compromised-old-token"),401);assert.equal(gateway(`Bearer ${TOKEN}`),200);});

test("local worker client protocol accepts bounded successful results without a native ok field",async()=>{let submitted;const client=createLocalWorkerClient({baseUrl:"https://preview.example",novaToken:TOKEN,vercelBypassToken:"vercel-bypass",fetchImpl:async(_url,input)=>{submitted=JSON.parse(input.body);return{ok:true,async json(){return{status:"queued"};}};}});const raw={exitCode:0,output:"passed"},normalized=raw.ok===undefined?{...raw,ok:true}:raw;await client.request("/complete",{result:normalized});assert.equal(submitted.result.ok,true);assert.equal(submitted.result.exitCode,0);});
test("authenticated exact-task claim returns one bounded server step without secrets",async()=>{const f=await fixture(),before=await f.storage.getAutonomyTask(TASK,OWNER),result=await claim(f.service);assert.equal(result.claimed,true);assert.equal(result.handoff.tool,"repo_apply_patch");assert.deepEqual(Object.keys(result.handoff).sort(),["arguments","branch","deadline","expectedCommit","handoffId","idempotencyKey","repository","stepId","stepType","taskId","tool"].sort());assert.doesNotMatch(JSON.stringify(result),/leaseToken|DATABASE_URL|password/);assert.ok((await f.storage.getAutonomyTask(TASK,OWNER)).stateVersion>before.stateVersion);});
test("capability mismatch and ineligible state return no task",async()=>{const f=await fixture();assert.equal((await claim(f.service,{capabilities:["test_local"]})).claimed,false);const blocked=await fixture({status:"completed"});assert.equal((await claim(blocked.service)).claimed,false);});
test("waiting for worker is claimable only by the exact compatible local capability",async()=>{const f=await fixture({status:"waiting_for_worker"});await f.storage.updateAutonomyTask(TASK,OWNER,{metadata:{steps:[plans.patch],requiredCapability:"repo_mutate_local"}});assert.equal((await claim(f.service,{capabilities:["test_local"]})).claimed,false);const claimed=await claim(f.service,{idempotencyKey:"compatible-local",capabilities:["repo_mutate_local"]});assert.equal(claimed.claimed,true);assert.equal(claimed.handoff.taskId,TASK);});
test("duplicate claim is idempotent while another worker cannot steal it",async()=>{const f=await fixture(),first=await claim(f.service),again=await claim(f.service),other=await claim(f.service,{workerId:"worker-two",idempotencyKey:"other"});assert.equal(again.idempotent,true);assert.equal(again.handoff.handoffId,first.handoff.handoffId);assert.equal(other.claimed,false);});
test("completion advances the exact step checkpoint and duplicate result is idempotent",async()=>{const f=await fixture(),claimed=await claim(f.service),before=(await f.storage.getAutonomyTask(TASK,OWNER)).stateVersion,input={taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,files:["docs/handoff.md"]}};const completed=await f.service.complete(claimed.handoff.handoffId,input);assert.equal(completed.task.currentStep,1);assert.ok(completed.task.stateVersion>before);assert.equal((await f.storage.listAutonomySteps(TASK))[0].status,"completed");assert.equal((await f.service.complete(claimed.handoff.handoffId,input)).idempotent,true);});
test("wrong handoff worker or idempotency key is rejected",async()=>{const f=await fixture(),claimed=await claim(f.service);for(const [id,input] of [["wrong",{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true}}],[claimed.handoff.handoffId,{taskId:TASK,workerId:"other",idempotencyKey:"claim-one",result:{ok:true}}],[claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"other",result:{ok:true}}]])await assert.rejects(()=>f.service.complete(id,input),error=>error.code==="handoff_mismatch");});
test("expired handoff is rejected requeued and can be reclaimed without rerunning completion",async()=>{const f=await fixture(),claimed=await claim(f.service);f.advance(30001);await assert.rejects(()=>f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true}}),error=>error.code==="handoff_expired");assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).status,"queued");assert.equal((await claim(f.service,{idempotencyKey:"claim-two"})).claimed,true);});
test("fresh active continuation runtime allows claim after historical task runtime expired",async()=>{const f=await fixture();await f.storage.updateAutonomyTask(TASK,OWNER,{startedAt:"2026-09-01T00:00:00Z",metadata:{steps:[plans.patch],requiredCapability:"repo_mutate_local",activeContinuation:{version:2,generationId:"fresh",startStep:0,maxSteps:4,recoveryClass:"repair",runtimeStartedAt:"2026-09-06T00:59:00Z",runtimeMinutes:15,runtimeDeadline:"2026-09-06T01:14:00Z"}}});assert.equal((await claim(f.service)).claimed,true);});
test("expired active continuation fails closed with scope diagnostics before mutation",async()=>{const f=await fixture();await f.storage.updateAutonomyTask(TASK,OWNER,{metadata:{steps:[plans.patch],requiredCapability:"repo_mutate_local",activeContinuation:{version:2,generationId:"expired",startStep:0,maxSteps:4,recoveryClass:"repair",runtimeStartedAt:"2026-09-05T00:00:00Z",runtimeMinutes:5,runtimeDeadline:"2026-09-05T00:05:00Z"}}});await assert.rejects(()=>claim(f.service),error=>error.code==="max_runtime_reached"&&error.safeDiagnostics.scope==="active_continuation"&&error.safeDiagnostics.claimStage==="pre_claim_runtime");assert.equal((await f.storage.listAutonomySteps(TASK)).length,0);});
test("branch commit protected branches and Production fail closed",async()=>{for(const [overrides,code] of [[{expectedBranch:"main"},"branch_not_allowed"],[{expectedBranch:"master"},"branch_not_allowed"],[{expectedBranch:"other"},"branch_not_allowed"],[{expectedCommit:"b".repeat(40)},"commit_mismatch"]]){const f=await fixture();await assert.rejects(()=>claim(f.service,overrides),error=>error.code===code);}const production=await fixture({deploymentEnvironment:"production"});await assert.rejects(()=>claim(production.service),error=>error.code==="production_target_forbidden");});
test("invalid client result cannot mutate task state",async()=>{const f=await fixture(),claimed=await claim(f.service),before=await f.storage.getAutonomyTask(TASK,OWNER);await assert.rejects(()=>f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:false,databaseUrl:"secret"}}),error=>error.code==="invalid_handoff_result");assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).currentStep,before.currentStep);});
test("structured failure follows bounded retry policy without arbitrary status control",async()=>{const f=await fixture(),claimed=await claim(f.service),failed=await f.service.fail(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",error:{code:"worker_crash",message:"safe",status:"completed"}});assert.equal(failed.status,"retrying");assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).status,"retrying");});
test("structured full-suite evidence durably schedules one canonically task-bound repair",async()=>{const f=await fixture({plan:{type:"run_full_tests",input:{tool:"test_run_full",arguments:{}}}});await f.storage.updateAutonomyTask(TASK,OWNER,{taskType:"self_development",metadata:{steps:[{type:"run_full_tests",input:{tool:"test_run_full",arguments:{}}},{type:"inspect_diff",input:{tool:"repo_diff",arguments:{}}}],selfDevelopment:{repairLimit:2},selfDevelopmentImplementationPlan:{files:[{path:"assets/voice-input.js"}],focusedTests:[{path:"test/voice-input.test.js"}]},requiredCapability:"test_local"}});const claimed=await claim(f.service),evidence={version:1,fingerprint:"e".repeat(64),failedFiles:["test/composer-dictation.test.js"],errorClass:"AssertionError",errorMessage:"expected true",stdoutExcerpt:"",stderrExcerpt:""},failed=await f.service.fail(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",error:{code:"test_failed",message:"Allowlisted tests failed.",diagnostics:evidence}}),task=await f.storage.getAutonomyTask(TASK,OWNER),repair=task.metadata.steps[task.currentStep+1],focused=task.metadata.steps[task.currentStep+2];assert.equal(failed.status,"queued");assert.equal(task.metadata.steps[task.currentStep].type,"plan_repair");assert.deepEqual(repair.input.arguments,{branch:"$TASK_BRANCH",currentCommit:"$CURRENT_COMMIT",files:"$IMPLEMENTATION_FILES",planProvenance:"$IMPLEMENTATION_PLAN_PROVENANCE"});assert.deepEqual(focused.input,{tool:"test_run",arguments:{files:"$IMPLEMENTATION_TESTS"}});assert.equal(task.metadata.fullTestRepairHistory.length,1);assert.equal((await f.storage.listAutonomySteps(TASK))[0].result.diagnostics.fingerprint,evidence.fingerprint);assert.doesNotMatch(JSON.stringify(await f.storage.listActivity(OWNER,{runId:TASK})),/token=/);});

test("Self-Development patch handoff injects exact task bindings and rejects contradictory branch",async()=>{const f=await fixture(),task=await f.storage.getAutonomyTask(TASK,OWNER),files=[{path:"docs/handoff.md",operation:"create",content:"safe"}],basePlan={files,focusedTests:[],planHash:"p"},provenance=bindImplementationPlan({task,plan:basePlan,evidence:[]}),plan={...basePlan,provenance};await f.storage.updateAutonomyTask(TASK,OWNER,{taskType:"self_development",metadata:{steps:[{type:"apply_patch",input:{tool:"repo_apply_patch",arguments:{files:"$IMPLEMENTATION_FILES"}}}],requiredCapability:"repo_mutate_local",selfDevelopmentImplementationPlan:plan,activeImplementationPlanGeneration:provenance.generationId,implementationPlanGenerations:[{...provenance,planHash:"p"}]}});const claimed=await claim(f.service);assert.deepEqual(claimed.handoff.arguments,{branch:BRANCH,currentCommit:SHA,files,planProvenance:provenance});const wrong=await fixture({plan:{type:"apply_patch",input:{tool:"repo_apply_patch",arguments:{branch:"other",files:[]}}}});await wrong.storage.updateAutonomyTask(TASK,OWNER,{taskType:"self_development",metadata:{steps:[{type:"apply_patch",input:{tool:"repo_apply_patch",arguments:{branch:"other",files:[]}}}],requiredCapability:"repo_mutate_local",selfDevelopmentImplementationPlan:plan,activeImplementationPlanGeneration:provenance.generationId,implementationPlanGenerations:[{...provenance,planHash:"p"}]}});await assert.rejects(()=>claim(wrong.service),error=>error.code==="branch_mismatch");});
test("local commit persists exact SHA and stops at public push approval",async()=>{const f=await fixture({plan:plans.commit}),claimed=await claim(f.service),next="b".repeat(40),completed=await f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,commitSha:next,files:["docs/handoff.md"]}}),task=await f.storage.getAutonomyTask(TASK,OWNER);assert.equal(completed.status,"waiting_for_approval");assert.equal(task.currentCommit,next);assert.equal(task.approvalState.tool,"git_push");assert.deepEqual(task.approvalState.arguments,{branch:BRANCH,commitSha:next});assert.equal((await f.storage.listApprovals(OWNER))[0].status,"pending");assert.equal((await f.storage.listActivity(OWNER,{runId:TASK})).some(item=>item.tool==="git_push"&&item.status==="completed"),false);});
test("commit defers approval when exact post-commit review is planned",async()=>{const f=await fixture({plan:plans.commit});await f.storage.updateAutonomyTask(TASK,OWNER,{metadata:{steps:[plans.commit,{type:"review_commit",input:{tool:"repo_review_commit",arguments:{commitSha:"$CURRENT_COMMIT",paths:["docs/handoff.md"]}}}],requiredCapability:"repo_mutate_local"}});const claimed=await claim(f.service),next="b".repeat(40),completed=await f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,commitSha:next,files:["docs/handoff.md"]}});assert.equal(completed.status,"queued");assert.equal((await f.storage.listApprovals(OWNER)).length,0);assert.equal((await f.storage.getAutonomyTask(TASK,OWNER)).currentCommit,next);});
test("reviewed existing commit creates one fresh exact approval",async()=>{const f=await fixture({plan:{type:"review_commit",input:{tool:"repo_review_commit",arguments:{commitSha:SHA,paths:["docs/handoff.md"]}}}}),claimed=await claim(f.service),completed=await f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,exitCode:0,commitSha:SHA,files:["docs/handoff.md"],reviewedChangeSet:{reviewHash:"reviewed"}}});assert.equal(completed.status,"waiting_for_approval");assert.equal((await f.storage.listApprovals(OWNER)).length,1);});
test("handoff Activity is durable and redacts submitted secrets",async()=>{const f=await fixture(),claimed=await claim(f.service);await f.service.complete(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,files:["docs/handoff.md"],apiKey:"should-not-survive"}});const activity=await f.storage.listActivity(OWNER,{runId:TASK});assert.ok(activity.some(item=>item.action==="local_worker_handoff_created"));assert.ok(activity.some(item=>item.action==="local_worker_handoff_completed"));assert.doesNotMatch(JSON.stringify(activity),/should-not-survive/);});
test("completed handoff cannot rerun after reconnect",async()=>{const f=await fixture(),claimed=await claim(f.service),input={taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",result:{ok:true,files:["docs/handoff.md"]}};await f.service.complete(claimed.handoff.handoffId,input);assert.equal((await f.service.complete(claimed.handoff.handoffId,input)).idempotent,true);assert.equal((await f.storage.listAutonomySteps(TASK)).length,1);});
test("a migrated protocol-failed step is reclaimed as the same logical retry",async()=>{const f=await fixture({plan:plans.test});await f.storage.recordAutonomyStep({taskId:TASK,stepId:"1:run_focused_tests",stepType:"run_focused_tests",capability:"test_local",operationFingerprint:"old-binding",status:"failed",attempt:1,errorCode:"invalid_handoff_result"});const claimed=await claim(f.service),steps=await f.storage.listAutonomySteps(TASK);assert.equal(claimed.claimed,true);assert.equal(steps.length,1);assert.equal(steps[0].status,"running");assert.equal(steps[0].attempt,2);assert.equal(steps[0].errorCode,null);});

test("schema mismatch canonical diagnostic survives durable step reload and safe Activity",async()=>{const f=await fixture(),claimed=await claim(f.service),unsafe={taskId:TASK,handoffId:claimed.handoff.handoffId,stepId:claimed.handoff.stepId,stepType:"apply_patch",tool:"repo_apply_patch",schemaVersion:"1",fieldPath:"repo_apply_patch.files",expected:{type:"array"},received:{type:"string",literal:"private-token"},validationCode:"invalid_type",validationLayer:"hands_tool_registry",payloadProvenance:"server_handoff_arguments",rawPayload:"private-token"};await f.service.fail(claimed.handoff.handoffId,{taskId:TASK,workerId:"worker-one",idempotencyKey:"claim-one",error:{code:"schema_mismatch",message:"safe",diagnostics:unsafe}});const reloaded=(await f.storage.listAutonomySteps(TASK))[0].result.diagnostics,activity=(await f.storage.listActivity(OWNER,{runId:TASK})).find(item=>item.action==="local_worker_handoff_failed");assert.deepEqual([reloaded.stepId,reloaded.tool,reloaded.fieldPath,reloaded.validationLayer,reloaded.payloadProvenance],[claimed.handoff.stepId,"repo_apply_patch","repo_apply_patch.files","hands_tool_registry","server_handoff_arguments"]);assert.deepEqual(reloaded.received,{type:"string"});assert.deepEqual(activity.metadata.failureEvidence,reloaded);assert.doesNotMatch(JSON.stringify({reloaded,activity}),/private-token|rawPayload|literal/);});
