import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {acquirePersistentWorkerInstance,persistentWorkerPaths,writePersistentWorkerStatus} from "../src/autonomy/persistent-worker-process.js";
import {runPersistentWorkerLoop} from "../src/autonomy/persistent-local-worker.js";
import {runPersistentWorkerService} from "../src/autonomy/persistent-worker-startup.js";

test("persistent loop survives idle queues and transient failures",async()=>{let calls=0;const states=[],delays=[];const result=await runPersistentWorkerLoop({worker:{async runOnce(){calls++;if(calls===1)throw Object.assign(new Error("temporary"),{code:"network_error"});return{worked:false};}},maxIterations:3,delay:async ms=>delays.push(ms),onState:value=>states.push(value)});assert.equal(result.iterations,3);assert.deepEqual(states.map(x=>x.state),["polling","retrying","polling","idle","polling","idle"]);assert.equal(delays.length,2);});
test("runtime directory is deterministic current-user local application data",()=>{const paths=persistentWorkerPaths({environment:{LOCALAPPDATA:"C:\\Users\\owner\\AppData\\Local"},home:"C:\\Users\\ignored"});assert.equal(paths.dir,"C:\\Users\\owner\\AppData\\Local\\NovaBrain\\PersistentWorker");assert.doesNotMatch(paths.dir,/Temp/i);});
test("single-instance lock rejects a live duplicate and reclaims stale ownership",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")},first=await acquirePersistentWorkerInstance({paths,pid:111,isAlive:value=>value===111}),duplicate=await acquirePersistentWorkerInstance({paths,pid:222,isAlive:value=>value===111});assert.equal(first.acquired,true);assert.equal(duplicate.acquired,false);await first.release();const stale=await acquirePersistentWorkerInstance({paths,pid:333,isAlive:()=>false});assert.equal(stale.acquired,true);await stale.release();});
test("persistent status is bounded and cannot contain credential material",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-status-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")};await writePersistentWorkerStatus({state:"retrying",code:"network_error",token:"never",password:"never"},{paths});const value=await readFile(paths.status,"utf8");assert.doesNotMatch(value,/never|token|password/i);assert.equal(JSON.parse(value).state,"retrying");});

test("startup states, transient auth recovery, heartbeat, and no-work persistence are deterministic",async()=>{const states=[];let auth=0,released=false;const credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){this.novaToken=null;this.vercelBypassToken=null;}};const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",probeOnly:true,maxIterations:2,intervalMs:1000,delay:async()=>{},credentialLoader:async()=>credentials,acquireInstance:async()=>({acquired:true,release:async()=>{released=true;}}),statusWriter:async value=>states.push({...value}),clientFactory:()=>({async request(){auth++;if(auth===1)throw Object.assign(new Error("temporary"),{code:"network_error"});return{dispatched:false};}}),workerFactory:()=>({workerId:"safe-worker",runOnce:async()=>({worked:false})})});assert.equal(result.probeOnly,true);assert.equal(released,true);assert.deepEqual(states.map(x=>x.state),["starting","lock_acquired","credentials_loaded","authenticating","retrying","authenticated","polling","idle","stopped"]);assert.ok(states.every(x=>!JSON.stringify(x).includes("n".repeat(40))&&!JSON.stringify(x).includes("v".repeat(40))));});

test("credential startup timeout reports fatal safely and releases lock",async()=>{const states=[];let released=false;const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",credentialTimeoutMs:5,credentialLoader:()=>new Promise(()=>{}),acquireInstance:async()=>({acquired:true,release:async()=>{released=true;}}),statusWriter:async value=>states.push({...value})});assert.equal(result.reason,"credential_load_timeout");assert.equal(released,true);assert.deepEqual(states.map(x=>x.state),["starting","lock_acquired","fatal","stopped"]);});

test("fatal authentication configuration writes a safe state and exits",async()=>{const states=[];const credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){}};const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",credentialLoader:async()=>credentials,acquireInstance:async()=>({acquired:true,release:async()=>{}}),statusWriter:async value=>states.push({...value}),clientFactory:()=>({request:async()=>{throw Object.assign(new Error("denied"),{code:"unauthorized",statusCode:401});}}),workerFactory:()=>({workerId:"safe-worker",runOnce:async()=>({worked:false})})});assert.equal(result.reason,"unauthorized");assert.deepEqual(states.map(x=>x.state),["starting","lock_acquired","credentials_loaded","authenticating","fatal","stopped"]);});

test("active duplicate fails closed before status, credentials, or polling",async()=>{let loaded=false;const states=[];const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",credentialLoader:async()=>{loaded=true;},acquireInstance:async()=>({acquired:false,release:async()=>{}}),statusWriter:async value=>states.push({...value})});assert.equal(result.reason,"active_instance");assert.equal(loaded,false);assert.deepEqual(states,[]);});
test("startup passes the explicit controlled repository root despite a different process cwd",async()=>{let received;const credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){}};await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",repositoryRoot:"C:\\controlled\\nova-brain",probeOnly:true,maxIterations:1,credentialLoader:async()=>credentials,acquireInstance:async()=>({acquired:true,release:async()=>{}}),statusWriter:async()=>{},clientFactory:()=>({request:async()=>({dispatched:false})}),workerFactory:input=>{received=input.root;return{workerId:"explicit-root",runOnce:async()=>({worked:false})};}});assert.equal(received,"C:\\controlled\\nova-brain");});
