import test from "node:test";
import assert from "node:assert/strict";
import {mkdtemp,readFile,rm} from "node:fs/promises";
import {join} from "node:path";
import {tmpdir} from "node:os";
import {acquirePersistentWorkerInstance,classifyPersistentWorkerPathError,persistentWorkerPaths,writePersistentWorkerStatus} from "../src/autonomy/persistent-worker-process.js";
import {runPersistentWorkerLoop} from "../src/autonomy/persistent-local-worker.js";
import {runPersistentWorkerService} from "../src/autonomy/persistent-worker-startup.js";

test("persistent loop survives idle queues and transient failures",async()=>{let calls=0;const states=[],delays=[];const result=await runPersistentWorkerLoop({worker:{async runOnce(){calls++;if(calls===1)throw Object.assign(new Error("temporary"),{code:"network_error"});return{worked:false};}},maxIterations:3,delay:async ms=>delays.push(ms),onState:value=>states.push(value)});assert.equal(result.iterations,3);assert.deepEqual(states.map(x=>x.state),["polling","retrying","polling","idle","polling","idle"]);assert.equal(delays.length,2);});
test("runtime directory is deterministic current-user local application data",()=>{const paths=persistentWorkerPaths({environment:{LOCALAPPDATA:"C:\\Users\\owner\\AppData\\Local"},home:"C:\\Users\\ignored"});assert.equal(paths.dir,"C:\\Users\\owner\\AppData\\Local\\NovaBrain\\PersistentWorker");assert.doesNotMatch(paths.dir,/Temp/i);});
test("single-instance lock rejects a live duplicate and reclaims stale ownership",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")},first=await acquirePersistentWorkerInstance({paths,pid:111,isAlive:value=>value===111}),duplicate=await acquirePersistentWorkerInstance({paths,pid:222,isAlive:value=>value===111});assert.equal(first.acquired,true);assert.equal(duplicate.acquired,false);await first.release();const stale=await acquirePersistentWorkerInstance({paths,pid:333,isAlive:()=>false});assert.equal(stale.acquired,true);await stale.release();});
test("persistent status retains only allowlisted credential diagnostics and no material",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-status-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")};await writePersistentWorkerStatus({state:"credential_loading",code:"network_error",credentialSource:"windows_credential_manager",credentialType:"vercel_bypass",credentialStage:"helper_process",token:"never",password:"never"},{paths});const value=await readFile(paths.status,"utf8"),parsed=JSON.parse(value);assert.doesNotMatch(value,/never|token|password/i);assert.equal(parsed.state,"credential_loading");assert.deepEqual([parsed.credentialSource,parsed.credentialType,parsed.credentialStage],["windows_credential_manager","vercel_bypass","helper_process"]);});
test("persistent status records bounded helper lifecycle metadata but no stream contents",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-helper-status-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")};await writePersistentWorkerStatus({state:"fatal",code:"credential_helper_timeout",credentialSource:"windows_credential_manager",credentialType:"nova_worker",credentialStage:"credential_api_read_timeout",credentialHelperExecutable:"C:\\Windows\\System32\\WindowsPowerShell\\v1.0\\powershell.exe",credentialHelperPid:41056,credentialHelperStartedAt:"2026-09-08T00:00:00.000Z",credentialHelperExitCode:1,credentialHelperStdoutBytes:0,credentialHelperStderrBytes:41,credentialHelperAliveAfterTimeout:false,stdout:"never",stderr:"never"},{paths});const text=await readFile(paths.status,"utf8"),value=JSON.parse(text);assert.equal(value.credentialStage,"credential_api_read_timeout");assert.deepEqual([value.credentialHelperPid,value.credentialHelperStdoutBytes,value.credentialHelperStderrBytes,value.credentialHelperAliveAfterTimeout],[41056,0,41,false]);assert.doesNotMatch(text,/"stdout"|"stderr"|never/);});
test("persistent status proves native helper selection without exposing credentials",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-native-helper-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")},helper="C:\\Users\\owner\\AppData\\Local\\NovaBrain\\PersistentWorker\\NovaCredentialHelper.exe";await writePersistentWorkerStatus({state:"polling",credentialHelperExecutable:helper,credentialHelperKind:"native",credentialHelperSelectionSource:"worker_cli",credentialHelperNativeExists:true,credentialHelperFallbackUsed:false,secret:"never"},{paths});const text=await readFile(paths.status,"utf8"),value=JSON.parse(text);assert.deepEqual([value.credentialHelperKind,value.credentialHelperSelectionSource,value.credentialHelperNativeExists,value.credentialHelperFallbackUsed],["native","worker_cli",true,false]);assert.equal(value.credentialHelperExecutable,helper);assert.doesNotMatch(text,/never|secret/i);});
test("concurrent startup status transitions use serialized unique temporary files without ENOENT",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-status-race-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")};await Promise.all(Array.from({length:40},(_,index)=>writePersistentWorkerStatus({state:index%2?"authenticating":"credential_loading",startupStage:"authenticating"},{paths})));const value=JSON.parse(await readFile(paths.status,"utf8"));assert.ok(["authenticating","credential_loading"].includes(value.state));});
test("startup ENOENT classifications identify exact safe operation and path kind",()=>{const cases=[["node_launch","node_executable"],["git_probe","git_executable"],["repository_access","repository_root"],["credential_helper_launch","credential_helper"],["auth_probe","auth_endpoint"],["status_temp_write","status_temporary_file"]];for(const[operation,pathKind]of cases){const error=classifyPersistentWorkerPathError(Object.assign(new Error("secret must not survive"),{code:"ENOENT"}),{operation,pathKind,path:`C:\\safe\\${pathKind}`,startupStage:"authenticating",pathExisted:false,cwd:"C:\\safe\\repo",nodeExecutable:"C:\\node.exe",gitExecutable:"C:\\git.exe"});assert.equal(error.code,`${operation}_missing`);assert.deepEqual([error.safeDiagnostics.failureOperation,error.safeDiagnostics.failurePathKind,error.safeDiagnostics.pathExisted],[operation,pathKind,false]);assert.doesNotMatch(JSON.stringify(error.safeDiagnostics),/secret must not survive/);}});
test("restart status preserves absolute executable bindings without credential material",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-bindings-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")};await writePersistentWorkerStatus({state:"polling",startupStage:"polling",cwd:"C:\\controlled\\nova-brain",nodeExecutable:"C:\\runtime\\node.exe",gitExecutable:"C:\\runtime\\git.exe",credentialHelperExecutable:"C:\\runtime\\NovaCredentialHelper.exe",secret:"never"},{paths});const text=await readFile(paths.status,"utf8"),value=JSON.parse(text);assert.deepEqual([value.cwd,value.nodeExecutable,value.gitExecutable],["C:\\controlled\\nova-brain","C:\\runtime\\node.exe","C:\\runtime\\git.exe"]);assert.doesNotMatch(text,/never|secret/i);});

test("persistent status retains only the allowlisted local schema diagnostic subset",async t=>{const dir=await mkdtemp(join(tmpdir(),"nova-worker-schema-status-"));t.after(()=>rm(dir,{recursive:true,force:true}));const paths={dir,lock:join(dir,"worker.lock"),status:join(dir,"status.json")};await writePersistentWorkerStatus({state:"retrying",code:"schema_mismatch",schemaDiagnostic:{handoffId:"handoff-safe",validationCode:"invalid_type",tool:"repo_apply_patch",fieldPath:"repo_apply_patch.files",validationLayer:"hands_tool_registry",expected:{type:"array"},received:{type:"string",value:"never"},secret:"never"}},{paths});const text=await readFile(paths.status,"utf8"),value=JSON.parse(text);assert.deepEqual([value.latestHandoffId,value.latestValidationCode,value.latestTool,value.latestFieldPath,value.latestValidationLayer],["handoff-safe","invalid_type","repo_apply_patch","repo_apply_patch.files","hands_tool_registry"]);assert.doesNotMatch(text,/never|secret|expected|received/);});

test("startup states, transient auth recovery, heartbeat, and no-work persistence are deterministic",async()=>{const states=[];let auth=0,released=false;const credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){this.novaToken=null;this.vercelBypassToken=null;}};const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",probeOnly:true,maxIterations:2,intervalMs:1000,delay:async()=>{},credentialLoader:async()=>credentials,acquireInstance:async()=>({acquired:true,release:async()=>{released=true;}}),statusWriter:async value=>states.push({...value}),clientFactory:()=>({async request(){auth++;if(auth===1)throw Object.assign(new Error("temporary"),{code:"network_error"});return{dispatched:false};}}),workerFactory:()=>({workerId:"safe-worker",runOnce:async()=>({worked:false})})});assert.equal(result.probeOnly,true);assert.equal(released,true);assert.deepEqual(states.map(x=>x.state),["starting","lock_acquired","credentials_loaded","authenticating","retrying","authenticated","polling","idle","stopped"]);assert.ok(states.every(x=>!JSON.stringify(x).includes("n".repeat(40))&&!JSON.stringify(x).includes("v".repeat(40))));});

test("credential startup timeout reports the active safe stage and releases lock",async()=>{const states=[];let released=false;const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",credentialTimeoutMs:5,credentialLoader:async({onStage})=>{await onStage({source:"windows_credential_manager",credentialType:"vercel_bypass",stage:"loading"});return new Promise(()=>{});},acquireInstance:async()=>({acquired:true,release:async()=>{released=true;}}),statusWriter:async value=>states.push({...value})});assert.equal(result.reason,"credential_load_timeout");assert.equal(released,true);assert.deepEqual(states.map(x=>x.state),["starting","lock_acquired","credential_loading","fatal","stopped"]);assert.equal(states.at(-2).credentialType,"vercel_bypass");assert.doesNotMatch(JSON.stringify(states),/token|secret/i);});
test("credential launch failure preserves configured native helper identity in fatal status",async()=>{const states=[],helper="C:\\runtime\\NovaCredentialHelper.exe",result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",startupMetadata:{credentialHelperExecutable:helper,credentialHelperKind:"native",credentialHelperSelectionSource:"worker_cli",credentialHelperNativeExists:true,credentialHelperFallbackUsed:false},credentialLoader:async()=>{throw Object.assign(new Error("credential_helper_start_failed"),{code:"credential_helper_start_failed",safeDiagnostics:{source:"windows_credential_manager",credentialType:"credential_set",stage:"process_start"}});},acquireInstance:async()=>({acquired:true,release:async()=>{}}),statusWriter:async value=>states.push({...value})});assert.equal(result.reason,"credential_helper_start_failed");const fatal=states.find(value=>value.state==="fatal");assert.equal(fatal.credentialHelperExecutable,helper);assert.equal(fatal.credentialHelperKind,"native");});

test("cold sequential Credential Manager reads complete inside the aggregate startup envelope",async()=>{const states=[],credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){}};const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",probeOnly:true,maxIterations:1,credentialTimeoutMs:80,credentialLoader:async({onStage})=>{for(const credentialType of["nova_worker","vercel_bypass"]){await onStage({source:"windows_credential_manager",credentialType,stage:"loading"});await new Promise(resolve=>setTimeout(resolve,20));await onStage({source:"windows_credential_manager",credentialType,stage:"loaded"});}return credentials;},acquireInstance:async()=>({acquired:true,release:async()=>{}}),statusWriter:async value=>states.push({...value}),clientFactory:()=>({request:async()=>({dispatched:false})}),workerFactory:()=>({workerId:"cold-start",runOnce:async()=>({worked:false})})});assert.equal(result.started,true);assert.ok(states.some(x=>x.state==="authenticated"));assert.deepEqual(states.filter(x=>x.state==="credential_loading").map(x=>`${x.credentialType}:${x.credentialStage}`),["nova_worker:loading","nova_worker:loaded","vercel_bypass:loading","vercel_bypass:loaded"]);});

test("fatal authentication configuration writes a safe state and exits",async()=>{const states=[];const credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){}};const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",credentialLoader:async()=>credentials,acquireInstance:async()=>({acquired:true,release:async()=>{}}),statusWriter:async value=>states.push({...value}),clientFactory:()=>({request:async()=>{throw Object.assign(new Error("denied"),{code:"unauthorized",statusCode:401});}}),workerFactory:()=>({workerId:"safe-worker",runOnce:async()=>({worked:false})})});assert.equal(result.reason,"unauthorized");assert.deepEqual(states.map(x=>x.state),["starting","lock_acquired","credentials_loaded","authenticating","fatal","stopped"]);});

test("active duplicate fails closed before status, credentials, or polling",async()=>{let loaded=false;const states=[];const result=await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",credentialLoader:async()=>{loaded=true;},acquireInstance:async()=>({acquired:false,release:async()=>{}}),statusWriter:async value=>states.push({...value})});assert.equal(result.reason,"active_instance");assert.equal(loaded,false);assert.deepEqual(states,[]);});
test("startup passes the explicit controlled repository root despite a different process cwd",async()=>{let received;const credentials={novaToken:"n".repeat(40),vercelBypassToken:"v".repeat(40),clear(){}};await runPersistentWorkerService({baseUrl:"https://preview.vercel.app",repositoryRoot:"C:\\controlled\\nova-brain",probeOnly:true,maxIterations:1,credentialLoader:async()=>credentials,acquireInstance:async()=>({acquired:true,release:async()=>{}}),statusWriter:async()=>{},clientFactory:()=>({request:async()=>({dispatched:false})}),workerFactory:input=>{received=input.root;return{workerId:"explicit-root",runOnce:async()=>({worked:false})};}});assert.equal(received,"C:\\controlled\\nova-brain");});
