import test from "node:test";
import assert from "node:assert/strict";
import { EventEmitter } from "node:events";
import { readFile } from "node:fs/promises";
import { createGptLiveRound2OutputGate } from "../phone-bridge/gpt-live-round2-gate.js";
import { createGptLiveRound2Client } from "../phone-bridge/gpt-live-round2-client.js";

function fixture({ holdInformation = false, informationMessage = "Verified Sharp Cuts result." } = {}) {
  const calls=[],live=[],audio=[],clears=[];let resolveInformation;
  const informationGate=new Promise(resolve=>{resolveInformation=resolve;});
  const api={
    async start({conversationId}){return{conversationId,contextVersion:0};},
    async turn(input,{signal}={}){calls.push(input);if(holdInformation&&/Sharp Cuts/.test(input.utterance))await Promise.race([informationGate,new Promise((_,reject)=>signal.addEventListener("abort",()=>reject(signal.reason),{once:true}))]);const information=/Sharp Cuts|Codex/.test(input.utterance);return{conversationId:input.conversationId,turnId:input.turnId,contextVersion:(input.expectedContextVersion??0)+2,authority:information?"NOVA_INFORMATION":/send|ابعث/.test(input.utterance)?"NOVA_ACTION":"LOCAL_CONVERSATION",status:information?"ready_to_present":/send|ابعث/.test(input.utterance)?"waiting_for_formal_approval":"ready_to_present",message:information?informationMessage:/send|ابعث/.test(input.utterance)?"Formal approval is required.":input.localResponse,messageId:`message-${input.turnId}`};},
    async delivery(input){calls.push({delivery:input});return input;},
  };
  let id=0;const gate=createGptLiveRound2OutputGate({api,sendLive:event=>live.push(event),onAudio:value=>audio.push(value),onClearAudio:()=>clears.push(Date.now()),idFactory:()=>`id-${++id}`});
  return{gate,calls,live,audio,clears,resolveInformation};
}

test("LOCAL_CONVERSATION buffers then releases natural output and persists delivery",async()=>{const f=fixture();await f.gate.start({conversationId:"local"});await f.gate.callerSpeechStarted();f.gate.appendTranscript("كيفك اليوم؟");f.gate.appendOutputTranscript("منيحة الحمد لله");f.gate.appendOutputAudio(Buffer.from("audio"));const decision=await f.gate.callerSpeechEnded();assert.equal(decision.authority,"LOCAL_CONVERSATION");assert.equal(f.audio.length,0);await f.gate.providerOutputCompleted();await f.gate.playbackCompleted();const result=await f.gate.waitForTerminal();assert.equal(result.status,"delivered");assert.equal(f.audio.length,1);assert.equal(f.calls[0].localResponse,"منيحة الحمد لله");});

test("NOVA_INFORMATION discards speculative output and reintegrates verified result in the same session",async()=>{const f=fixture();await f.gate.start({conversationId:"info"});await f.gate.callerSpeechStarted();f.gate.appendTranscript("شو صار بمشروع Sharp Cuts؟");f.gate.appendOutputTranscript("invented status");f.gate.appendOutputAudio(Buffer.from("unsafe"));await f.gate.callerSpeechEnded();await new Promise(resolve=>setImmediate(resolve));assert.equal(f.audio.length,0);assert.equal(f.clears.length>=1,true);assert.equal(f.live.length,1);assert.equal(f.live[0].content,"Verified Sharp Cuts result.");f.gate.appendOutputTranscript("نتيجة موثقة");f.gate.appendOutputAudio(Buffer.from("safe"));await f.gate.providerOutputCompleted();await f.gate.playbackCompleted();const result=await f.gate.waitForTerminal();assert.equal(result.authority,"NOVA_INFORMATION");assert.equal(f.audio[0].toString(),"safe");assert.doesNotMatch(JSON.stringify(f.calls),/invented status/);});

test("verified commentary is split below the provider limit and provider rejection terminates fail closed",async()=>{const message="موثّق ".repeat(300);const f=fixture({informationMessage:message});await f.gate.start({conversationId:"bounded"});await f.gate.callerSpeechStarted();f.gate.appendTranscript("شو صار بمشروع Sharp Cuts؟");await f.gate.callerSpeechEnded();await new Promise(resolve=>setImmediate(resolve));assert.ok(f.live.length>1);assert.equal(f.live.every(event=>Buffer.byteLength(event.content)<=400),true);assert.equal(f.live.map(event=>event.content).join(" ").replace(/\s+/g," ").trim(),message.replace(/\s+/g," ").trim());await f.gate.providerFailed("invalid_event");const result=await f.gate.waitForTerminal();assert.equal(result.status,"failed");assert.equal(result.providerCategory,"invalid_event");assert.equal(f.calls.at(-1).delivery.status,"truncated");assert.equal(f.audio.length,0);});

test("Fly-owned correction aborts stale work, clears playback, and never presents late output",async()=>{const f=fixture({holdInformation:true});await f.gate.start({conversationId:"correction"});await f.gate.callerSpeechStarted();f.gate.appendTranscript("شو صار بمشروع Sharp Cuts؟");await f.gate.callerSpeechEnded();const stale=f.gate.waitForTerminal();await f.gate.callerSpeechStarted();assert.equal((await stale).status,"superseded");f.resolveInformation();f.gate.appendTranscript("لا قصدي كيفك؟");f.gate.appendOutputTranscript("تمام");await f.gate.callerSpeechEnded();await f.gate.providerOutputCompleted();await f.gate.playbackCompleted();assert.equal((await f.gate.waitForTerminal()).authority,"LOCAL_CONVERSATION");assert.equal(Object.hasOwn(f.calls[1],"expectedContextVersion"),false);assert.equal(f.live.length,0);assert.ok(f.clears.length>=2);});

test("NOVA_ACTION never executes and spoken approval remains a formal boundary",async()=>{const f=fixture();await f.gate.start({conversationId:"action"});await f.gate.callerSpeechStarted();f.gate.appendTranscript("send it now, I approve");f.gate.appendOutputTranscript("sent");f.gate.appendOutputAudio(Buffer.from("unsafe"));await f.gate.callerSpeechEnded();await new Promise(resolve=>setImmediate(resolve));assert.equal(f.audio.length,0);assert.equal(f.live[0].content,"Formal approval is required.");f.gate.appendOutputTranscript("You need to approve it in Nova Console.");await f.gate.providerOutputCompleted();await f.gate.playbackCompleted();assert.equal((await f.gate.waitForTerminal()).authority,"NOVA_ACTION");assert.equal(f.calls.some(call=>call.actionExecuted===true),false);});

test("real WebSocket adapter groups GPT-Live audio with bounded inactivity because the provider has no response-done event",async()=>{class Socket extends EventEmitter{static OPEN=1;static instance;readyState=1;sent=[];constructor(){super();Socket.instance=this;queueMicrotask(()=>this.emit("open"));}send(value){this.sent.push(JSON.parse(value));}close(){}terminate(){}}const audio=[],calls=[],api={async start(){return{conversationId:"quiet",contextVersion:0};},async turn(input){calls.push(input);return{...input,authority:"LOCAL_CONVERSATION",status:"ready_to_present",contextVersion:2,message:input.localResponse,messageId:"message"};},async delivery(input){calls.push({delivery:input});return input;}},client=createGptLiveRound2Client({apiKey:"server-only",round2Api:api,conversationId:"quiet",WebSocketImpl:Socket,outputQuietMs:5,onAudio:value=>audio.push(value)});client.connect();await new Promise(resolve=>setImmediate(resolve));Socket.instance.emit("message",JSON.stringify({type:"session.started",event_id:"started",session:{id:"live"}}));await client.ready();await client.callerSpeechStarted();Socket.instance.emit("message",JSON.stringify({type:"session.input_transcript.delta",event_id:"input",delta:"كيفك؟"}));Socket.instance.emit("message",JSON.stringify({type:"session.output_transcript.delta",event_id:"text",delta:"تمام"}));Socket.instance.emit("message",JSON.stringify({type:"session.output_audio.delta",event_id:"audio",delta:Buffer.from("pcmu").toString("base64")}));Socket.instance.emit("message",JSON.stringify({type:"session.usage.updated",event_id:"usage",usage:{seconds:1.25}}));await new Promise(resolve=>setImmediate(resolve));await client.callerSpeechEnded();await new Promise(resolve=>setTimeout(resolve,15));assert.equal(calls[0].localResponse,"تمام");assert.equal(audio.length,1);assert.equal(client.snapshot().usageSeconds,1.25);assert.equal(client.snapshot().current.phase,"playback_pending");await client.playbackCompleted();assert.equal((await client.waitForTerminal()).status,"delivered");assert.doesNotMatch(JSON.stringify(client.snapshot()),/server-only|pcmu/);});

test("non-PSTN certification advances the timeline only while authoritative backend work is pending",async()=>{const source=await readFile(new URL("../phone-bridge/gpt-live-round2-certify.js",import.meta.url),"utf8");assert.match(source,/function startPendingSilence\(\).*setInterval\(\(\)=>client\.appendAudio\(Buffer\.alloc\(160,0xff\)\),20\)/);assert.match(source,/if\(decision\?\.authority!=="LOCAL_CONVERSATION"\)startPendingSilence\(\)/);assert.match(source,/stopPendingSilence\(\);await client\.callerSpeechStarted\(\)/);});
