import test from "node:test";
import assert from "node:assert/strict";
import { createGptLivePstnSession } from "../phone-bridge/gpt-live-pstn-session.js";
import { createGptLiveRound2OutputGate } from "../phone-bridge/gpt-live-round2-gate.js";
import { createInMemoryStorage } from "../src/storage/in-memory-storage.js";
import { createOwnerContactPolicy } from "../src/phone/owner-contact-policy.js";
import { projectCallTimeline, summarizeCall } from "../src/phone/call-projection.js";
import { INITIAL_OWNER_PROFILE } from "../src/identity/initial-context.js";
import { createSpeakerIdentity } from "../src/voice/speaker-identity.js";

const SPEECH=Buffer.alloc(160,0x00).toString("base64"),SILENCE=Buffer.alloc(160,0xff).toString("base64"),CALL_SID=`CA${"a".repeat(32)}`,STREAM_SID=`MZ${"b".repeat(32)}`;
const authorization={bridgeSessionToken:"bridge",callIntentId:"phone_fixture",callConversationId:"phone-session-phone_fixture",maximumDurationSeconds:600,mediaProfile:"gpt_live_round2_preview",liveVoice:"gleam"};
const media=payload=>({event:"media",streamSid:STREAM_SID,media:{payload}});

test("bounded endpoint grace keeps 500 ms, 700 ms, and about one-second hesitations in one caller turn",async()=>{
  const timers=[];let starts=0,ends=0,resumes=0;
  const client={connect(){},async ready(){return{};},async beginGreeting(){},async callerSpeechStarted(){starts+=1;},resumeCallerSpeech(){resumes+=1;},appendAudio(){},async callerSpeechEnded({speakerAudio}={}){ends+=1;assert.equal(speakerAudio.mimeType,"audio/wav");return{};},async close(){},snapshot(){return{current:{turnId:"t1",phase:"capturing",terminal:null,transcriptCharacters:20},rawAudioPersisted:false};}};
  const setTimer=(callback,delay)=>{const value={callback,delay,cleared:false,unref(){}};timers.push(value);return value;},clearTimer=value=>{if(value)value.cleared=true;};
  const runtime=createGptLivePstnSession({sendTwilio(){},novaClient:{async event(){}},authorization,callIntentId:"phone_fixture",maximumDurationSeconds:600,callSid:CALL_SID,streamSid:STREAM_SID,apiKey:"x",round2Api:{},createClient(){return client;},setTimer,clearTimer,endpointGraceMs:900});await runtime.start();
  for(const pause of [500,700,1000]){for(let i=0;i<3;i++)runtime.handle(media(SPEECH));for(let i=0;i<50;i++)runtime.handle(media(SILENCE));const grace=timers.filter(item=>item.delay===900).at(-1);assert.ok(grace);for(let i=0;i<3;i++)runtime.handle(media(SPEECH));assert.equal(grace.cleared,true,`${pause} ms resume cancels endpoint`);}
  assert.equal(starts,1);assert.equal(ends,0);assert.equal(resumes,3);for(let i=0;i<50;i++)runtime.handle(media(SILENCE));timers.filter(item=>item.delay===900&&!item.cleared).at(-1).callback();await new Promise(resolve=>setImmediate(resolve));assert.equal(ends,1);await runtime.stop("completed","fixture",{hangupSocket:false});
});

test("segment marks monotonically confirm only returned transcript prefixes and cleared marks cannot advance truth",async()=>{
  const deliveries=[],playback=[];const gate=createGptLiveRound2OutputGate({api:{async start(){return{conversationId:"ledger",contextVersion:0};},async turn(input){return{...input,authority:"LOCAL_CONVERSATION",contextVersion:1,message:input.localResponse,messageId:"m1"};},async delivery(input){deliveries.push(input);},async playback(input){playback.push(input);}},sendLive(){},onAudio(){}});
  await gate.start({conversationId:"ledger"});const turnId=await gate.callerSpeechStarted();gate.appendTranscript("مرحبا");gate.appendOutputTranscript("أهلين، ");gate.appendOutputAudio(Buffer.alloc(4000));gate.appendOutputTranscript("كيفك؟");gate.appendOutputAudio(Buffer.alloc(4000));await gate.callerSpeechEnded();await gate.providerOutputCompleted();
  assert.equal(await gate.playbackCheckpoint({turnId,checkpointId:"one",outputKind:"final",byteStart:0,byteEnd:4000,durationStartMs:0,durationEndMs:500,textPrefix:"أهلين، ",acknowledgedAt:10}),true);assert.equal(await gate.playbackCheckpoint({turnId,checkpointId:"cleared",outputKind:"final",textPrefix:"أهلين، كيفك؟",cleared:true}),false);await gate.supersede("caller_barge_in");assert.equal(deliveries.at(-1).deliveredText,"أهلين، ");assert.equal(deliveries.at(-1).status,"partially_delivered");assert.equal(playback.find(item=>item.stage==="playback_checkpoint").checkpointId,"one");
});

test("initial greeting has canonical output identity without a fabricated caller turn",async()=>{const live=[];const gate=createGptLiveRound2OutputGate({api:{async start(){return{conversationId:"greet",contextVersion:0};},async greeting(){return{conversationId:"greet",contextVersion:0,turnId:"greeting-1",messageId:"greeting-message",message:"أهلين، معك نوفا."};}},sendLive:event=>live.push(event)});await gate.start({conversationId:"greet"});assert.equal(await gate.beginGreeting(),"greeting-1");assert.equal(gate.snapshot().current.phase,"verified_waiting_ack");assert.equal(live[0].content,"أهلين، معك نوفا.");});

test("Calls projection shows confirmed speech and keeps unheard output out of spoken content",()=>{const messages=[{id:"u1",role:"user",content:"مرحبا",createdAt:"2026-01-01T00:00:01Z"}],events=[{id:"c",turnId:"t1",eventType:"authority_classified",status:"LOCAL_CONVERSATION",createdAt:"2026-01-01T00:00:01Z",metadata:{userMessageId:"u1",speaker:{authenticatedIdentity:"none"}}},{id:"d1",messageId:"a1",turnId:"t1",eventType:"assistant_output_delivery",status:"partially_delivered",createdAt:"2026-01-01T00:00:02Z",metadata:{outputKind:"final",intendedText:"أهلين، كيفك؟",deliveredText:"أهلين"}},{id:"d2",messageId:"a2",turnId:"t2",eventType:"assistant_output_delivery",status:"generated_not_released",createdAt:"2026-01-01T00:00:03Z",metadata:{outputKind:"final",intendedText:"secret full answer",deliveredText:""}}];const timeline=projectCallTimeline(messages,events);assert.deepEqual(timeline.map(item=>item.content),["مرحبا","أهلين",""]);assert.equal(timeline.at(-1).heard,false);assert.equal(summarizeCall("completed",events,messages).counts.partial,1);});

test("Preview owner-contact policy is default-off, exact-contact bounded, auditable, and atomic",async()=>{let now=new Date("2026-10-06T12:00:00Z");const storage=createInMemoryStorage({clock:()=>now});await storage.initialize({owner:INITIAL_OWNER_PROFILE});const policy=createOwnerContactPolicy({storage,ownerId:INITIAL_OWNER_PROFILE.id,ownerNumber:"+447700900123",deploymentEnvironment:"preview",clock:()=>now});assert.equal((await policy.status()).enabled,false);const enabled=await policy.configure({enabled:true,allowedReasons:["preview_owner_test"],maximumCalls:2,dailyLimit:2,cooldownMinutes:10,expiresAt:"2026-10-06T13:00:00Z"});assert.equal(enabled.enabled,true);assert.equal((await policy.authorize({destination:"+447700900999",reason:"preview_owner_test"})).authorized,false);const grant=await policy.authorize({destination:"+447700900123",reason:"preview_owner_test"});assert.equal(grant.authorized,true);await policy.consume(grant.policyVersion);assert.equal((await policy.status()).remainingCalls,1);assert.equal((await storage.listActivity(INITIAL_OWNER_PROFILE.id)).some(item=>item.action==="owner_contact_policy_enabled"),true);assert.equal((await policy.disable()).enabled,false);});

test("PSTN calibration is separate from browser enrollment and supplies channel-specific thresholds only after consent",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:INITIAL_OWNER_PROFILE});const identity=createSpeakerIdentity({storage,ownerId:INITIAL_OWNER_PROFILE.id});const profile=await identity.enroll({displayName:"Mohammad",relation:"owner",scope:"owner",consent:true,consentActor:"owner",sampleRepresentations:[[1,0],[1,0],[1,0]],representationVersion:"ecapa-browser-v1",enrollmentAttemptId:"browser-enrollment"});assert.equal(await storage.getSpeakerChannelCalibration(INITIAL_OWNER_PROFILE.id,"pstn_8khz_v1"),null);await storage.saveSpeakerChannelCalibration({ownerId:INITIAL_OWNER_PROFILE.id,speakerProfileId:profile.id,channel:"pstn_8khz_v1",status:"ready",representationVersion:"ecapa-pstn-v1",ownerMatchThreshold:0.93,ambiguityMargin:0.08,sampleCount:6,sessionCount:2,conditions:["handset","mixed_language"],consentAt:"2026-10-06T12:00:00Z"});const calibration=await storage.getSpeakerChannelCalibration(INITIAL_OWNER_PROFILE.id,"pstn_8khz_v1");assert.deepEqual([calibration.ownerMatchThreshold,calibration.ambiguityMargin,calibration.sampleCount,calibration.sessionCount],[0.93,0.08,6,2]);const strict=await identity.recognizeMany([{label:"pstn",representation:[0.9,0.435]}],{threshold:0.99,ambiguityMargin:0.08});assert.notEqual(strict.state,"confirmed");});

test("owner callback authority requires a real task state and cannot be reset around the rolling daily limit",async()=>{let now=new Date("2026-10-06T12:00:00Z");const storage=createInMemoryStorage({clock:()=>now});await storage.initialize({owner:INITIAL_OWNER_PROFILE});const policy=createOwnerContactPolicy({storage,ownerId:INITIAL_OWNER_PROFILE.id,ownerNumber:"+447700900123",deploymentEnvironment:"preview",clock:()=>now});await policy.configure({enabled:true,allowedReasons:["task_completed"],maximumCalls:3,dailyLimit:1,cooldownMinutes:1,expiresAt:"2026-10-06T13:00:00Z"});assert.equal((await policy.authorize({destination:"+447700900123",reason:"task_completed",sourceTaskId:"invented"})).reason,"grounded_source_invalid");let task=await storage.createAutonomyTask({id:"task-grounded",ownerId:INITIAL_OWNER_PROFILE.id,title:"Grounded",objective:"Complete real work",taskType:"public_web_research"});task=await storage.updateAutonomyTask(task.id,INITIAL_OWNER_PROFILE.id,{status:"completed"},task.stateVersion);assert.equal((await policy.authorize({destination:"+447700900123",reason:"task_completed",sourceTaskId:task.id})).authorized,true);});

test("terminal tasks create one durable callback eligibility without creating a call intent or dialing",async()=>{const now=new Date("2026-10-06T12:00:00Z"),storage=createInMemoryStorage({clock:()=>now});await storage.initialize({owner:INITIAL_OWNER_PROFILE});await storage.ensureConversation({id:"callback-conversation",ownerId:INITIAL_OWNER_PROFILE.id});const policy=createOwnerContactPolicy({storage,ownerId:INITIAL_OWNER_PROFILE.id,ownerNumber:"+447700900123",deploymentEnvironment:"preview",clock:()=>now});await policy.configure({enabled:true,allowedReasons:["task_completed","task_blocked_owner_required"],maximumCalls:3,dailyLimit:3,cooldownMinutes:1,expiresAt:"2026-10-06T13:00:00Z"});
  let completed=await storage.createAutonomyTask({id:"task-callback-complete",ownerId:INITIAL_OWNER_PROFILE.id,title:"Complete",objective:"Complete work",taskType:"public_web_research",metadata:{terminalReporting:{version:1,conversationId:"callback-conversation"}}});completed=await storage.updateAutonomyTask(completed.id,INITIAL_OWNER_PROFILE.id,{status:"completed"},completed.stateVersion);
  let blocked=await storage.createAutonomyTask({id:"task-callback-blocked",ownerId:INITIAL_OWNER_PROFILE.id,title:"Blocked",objective:"Need owner",taskType:"public_web_research",metadata:{terminalReporting:{version:1,conversationId:"callback-conversation"}}});blocked=await storage.updateAutonomyTask(blocked.id,INITIAL_OWNER_PROFILE.id,{status:"blocked"},blocked.stateVersion);
  assert.deepEqual(await policy.reconcileTerminalTasks(),{recorded:2,eligible:2,callIntentsCreated:0,dials:0});assert.deepEqual(await policy.reconcileTerminalTasks(),{recorded:0,eligible:0,callIntentsCreated:0,dials:0});
  const records=await storage.listOwnerCallbackEligibilities(INITIAL_OWNER_PROFILE.id);assert.equal(records.length,2);assert.deepEqual(new Set(records.map(item=>item.reason)),new Set(["task_completed","task_blocked_owner_required"]));assert.equal((await storage.listPhoneCalls(INITIAL_OWNER_PROFILE.id)).length,0);assert.equal(records.every(item=>item.status==="eligible"&&item.conversationId==="callback-conversation"),true);
});

test("disabled standing policy records terminal callback ineligibility once and never grants dial authority",async()=>{const now=new Date("2026-10-06T12:00:00Z"),storage=createInMemoryStorage({clock:()=>now});await storage.initialize({owner:INITIAL_OWNER_PROFILE});const policy=createOwnerContactPolicy({storage,ownerId:INITIAL_OWNER_PROFILE.id,ownerNumber:"+447700900123",deploymentEnvironment:"preview",clock:()=>now});let task=await storage.createAutonomyTask({id:"task-callback-disabled",ownerId:INITIAL_OWNER_PROFILE.id,title:"Complete",objective:"Complete work",taskType:"public_web_research",metadata:{terminalReporting:{version:1,conversationId:"callback-conversation"}}});task=await storage.updateAutonomyTask(task.id,INITIAL_OWNER_PROFILE.id,{status:"completed"},task.stateVersion);assert.deepEqual(await policy.reconcileTerminalTasks(),{recorded:1,eligible:0,callIntentsCreated:0,dials:0});const [record]=await storage.listOwnerCallbackEligibilities(INITIAL_OWNER_PROFILE.id);assert.equal(record.status,"ineligible");assert.equal(record.decisionCode,"inactive");assert.equal((await storage.listPhoneCalls(INITIAL_OWNER_PROFILE.id)).length,0);});
