import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createGithubWriteAttestation,LIVE_PUSH_ATTESTATION,REQUIRED_BLOCKER_SHA} from "../src/autonomy/github-write-attestation.js";
import {createPostAttestationRecovery,LIVE_EXPIRY_RECOVERY} from "../src/autonomy/post-attestation-recovery.js";

const OWNER="owner",completed=["1:inspect_repo","2:apply_patch","3:run_focused_tests","4:run_full_tests","5:inspect_diff","6:commit"],request=()=>({...LIVE_EXPIRY_RECOVERY});
const deployment=(overrides={})=>({id:LIVE_PUSH_ATTESTATION.deploymentId,url:LIVE_PUSH_ATTESTATION.deploymentUrl,status:"READY",target:null,sha:LIVE_PUSH_ATTESTATION.sha,branch:LIVE_PUSH_ATTESTATION.branch,...overrides});
async function fixture({deploymentOverrides={},taskPatch={},storageWrap}={}){let now=Date.parse("2026-09-06T18:00:00Z");const base=createInMemoryStorage({clock:()=>new Date(now)});await base.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});await base.createAutonomyTask({id:LIVE_PUSH_ATTESTATION.taskId,ownerId:OWNER,projectId:"nova-brain",title:"Acceptance",objective:"Complete verification",branch:LIVE_PUSH_ATTESTATION.branch,startingCommit:LIVE_PUSH_ATTESTATION.sha,maxSteps:13,maxRuntimeMinutes:90,metadata:{steps:Array.from({length:11},(_,index)=>({type:index===8?"wait":"existing"}))}});await base.updateAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER,{status:"waiting_for_worker",currentStep:6,currentCommit:LIVE_PUSH_ATTESTATION.sha,checkpoint:{completedSteps:completed},metadata:{steps:Array.from({length:11},(_,index)=>({type:index===8?"wait":"existing"})),requiredCapability:"github_write"},approvalState:{approvalId:LIVE_PUSH_ATTESTATION.approvalId,approved:true}});await base.createApproval({id:LIVE_PUSH_ATTESTATION.approvalId,ownerId:OWNER,projectId:"nova-brain",runId:LIVE_PUSH_ATTESTATION.taskId,tool:"git_push",reason:"Exact push",riskLevel:"SENSITIVE",arguments:{branch:LIVE_PUSH_ATTESTATION.branch,commitSha:LIVE_PUSH_ATTESTATION.sha}});await base.decideApproval(LIVE_PUSH_ATTESTATION.approvalId,OWNER,"approved");const attestation=createGithubWriteAttestation({storage:base,ownerId:OWNER,verifyRemote:async()=>({currentTip:"d".repeat(40),ancestors:{[LIVE_PUSH_ATTESTATION.sha]:true,[REQUIRED_BLOCKER_SHA]:true}}),verifyDeployment:async()=>deployment()});await attestation.attest({...LIVE_PUSH_ATTESTATION});await base.updateAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER,{status:"expired",errorCode:"max_runtime_reached",completedAt:new Date(now).toISOString(),...taskPatch});const storage=storageWrap?storageWrap(base):base,service=createPostAttestationRecovery({storage,ownerId:OWNER,verifyDeployment:async()=>deployment(deploymentOverrides),clock:()=>new Date(now)});return{base,storage,service,advance(ms){now+=ms;}};}
async function rejects(code,options={},input=request()){const f=await fixture(options),before=await f.base.getAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER);await assert.rejects(()=>f.service.recover(input),error=>error.code===code);assert.equal((await f.base.getAutonomyTask(before.id,OWNER)).stateVersion,before.stateVersion);return f;}

test("exact post-attestation max-runtime expiry recovers",async()=>{const f=await fixture(),before=await f.base.getAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER),result=await f.service.recover(request());assert.equal(result.task.status,"queued");assert.equal(result.task.stateVersion,before.stateVersion+1);});
test("unrelated expired task id is rejected",()=>rejects("task_mismatch",{}, {...request(),taskId:"other"}));
test("wrong expiry reason is rejected",()=>rejects("task_state_mismatch",{taskPatch:{errorCode:"other"}}));
test("missing push checkpoint is rejected",()=>rejects("checkpoint_mismatch",{taskPatch:{checkpoint:{completedSteps:[...completed,"8:deploy_preview"]}}}));
test("missing deploy checkpoint is rejected",()=>rejects("checkpoint_mismatch",{taskPatch:{checkpoint:{completedSteps:[...completed,"7:push"]}}}));
test("duplicate push checkpoint is rejected",()=>rejects("duplicate_push_checkpoint",{storageWrap:base=>Object.freeze({...base,listAutonomySteps:async id=>{const steps=await base.listAutonomySteps(id),push=steps.find(x=>x.stepId==="7:push");return[...steps,{...push,operationFingerprint:"duplicate"}];}})}));
test("duplicate deploy checkpoint is rejected",()=>rejects("duplicate_deploy_checkpoint",{storageWrap:base=>Object.freeze({...base,listAutonomySteps:async id=>{const steps=await base.listAutonomySteps(id),deploy=steps.find(x=>x.stepId==="8:deploy_preview");return[...steps,{...deploy,operationFingerprint:"duplicate"}];}})}));
test("wrong acceptance SHA is rejected",()=>rejects("sha_mismatch",{taskPatch:{currentCommit:"a".repeat(40)}}));
test("wrong approval action is rejected",()=>rejects("approval_mismatch",{storageWrap:base=>Object.freeze({...base,getApproval:async(...args)=>({...await base.getApproval(...args),tool:"other"})})}));
test("wrong deployment is rejected",()=>rejects("deployment_mismatch",{deploymentOverrides:{id:"other"}}));
test("deployment not READY is rejected",()=>rejects("deployment_not_ready",{deploymentOverrides:{status:"BUILDING"}}));
test("deployment SHA mismatch is rejected",()=>rejects("deployment_sha_mismatch",{deploymentOverrides:{sha:"b".repeat(40)}}));
test("deployment branch mismatch is rejected",()=>rejects("deployment_branch_mismatch",{deploymentOverrides:{branch:"main"}}));
test("active lease is rejected",()=>rejects("active_lease_conflict",{taskPatch:{leaseOwner:"worker",leaseToken:"lease",leaseExpiresAt:"2099-01-01T00:00:00Z"}}));
test("state-version conflict is rejected",async()=>{const f=await fixture({storageWrap:base=>Object.freeze({...base,recoverExpiredAutonomyTask:async input=>{await base.updateAutonomyTask(input.taskId,input.ownerId,{resultSummary:"race"});return null;}})});const before=await f.base.getAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER);await assert.rejects(()=>f.service.recover(request()),e=>e.code==="version_conflict");const after=await f.base.getAutonomyTask(before.id,OWNER);assert.equal(after.stateVersion,before.stateVersion+1);assert.equal(after.status,"expired");});
test("main target is rejected",()=>rejects("branch_mismatch",{taskPatch:{branch:"main"}}));
test("prior checkpoints are preserved",async()=>{const f=await fixture(),result=await f.service.recover(request());assert.deepEqual(result.task.checkpoint.completedSteps,[...completed,"7:push","8:deploy_preview"]);});
test("prior attempts and step history are preserved",async()=>{const f=await fixture(),before=await f.base.listAutonomySteps(LIVE_PUSH_ATTESTATION.taskId);await f.service.recover(request());assert.equal((await f.base.listAutonomySteps(LIVE_PUSH_ATTESTATION.taskId)).length,before.length);});
test("original expiry remains auditable",async()=>{const f=await fixture();await f.service.recover(request());const task=await f.base.getAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER),activity=await f.base.listActivity(OWNER,{runId:task.id});assert.equal(task.metadata.postAttestationRecovery.previousStatus,"expired");assert.equal(activity[0].action,"autonomy_post_attestation_expiry_recovered");});
test("fresh continuation runtime budget is exact and bounded",async()=>{const f=await fixture(),result=await f.service.recover(request());assert.equal(result.task.maxRuntimeMinutes,15);await assert.rejects(()=>f.service.recover({...request(),runtimeMinutes:120}),e=>e.code==="runtime_budget_mismatch");});
test("completed steps are not repeated and no push or deployment is planned",async()=>{const f=await fixture();await f.service.recover(request());const task=await f.base.getAutonomyTask(LIVE_PUSH_ATTESTATION.taskId,OWNER),remaining=task.metadata.steps.slice(task.currentStep);assert.deepEqual(remaining.map(x=>x.input?.tool||x.type),["deployment_status_existing","preview_verify_existing","summarize"]);assert.equal(remaining.some(x=>["git_push","preview_deploy"].includes(x.input?.tool)),false);});
test("terminal success is impossible until both remaining verification steps pass",async()=>{const f=await fixture(),result=await f.service.recover(request());assert.equal(result.task.status,"queued");assert.equal(result.task.currentStep,9);assert.equal(result.task.checkpoint.completedSteps.includes("10:verify_preview"),false);assert.equal(result.task.checkpoint.completedSteps.includes("11:verify_preview"),false);});
