import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createPstnSpeakerEnrollment,PSTN_ENROLLMENT_CONSENT_VERSION} from "../src/voice/pstn-speaker-enrollment.js";
import {immutableCallEnvelope,callStartArguments} from "../src/phone/call-envelope.js";
import {approvalViewModel} from "../assets/approval-presenter.js";
import {createSpeakerEnrollmentSession,speakerEnrollmentCompletionMessage} from "../phone-bridge/speaker-enrollment-session.js";
import {SCHEMA_STATEMENTS,SCHEMA_VERSION} from "../src/storage/schema.js";

const OWNER="owner",DESTINATION="+447960672981";
const cosine=(left,right)=>left.reduce((sum,value,index)=>sum+value*right[index],0)/(Math.hypot(...left)*Math.hypot(...right));
async function fixture({ownerNumber=DESTINATION,extract=async()=>({sufficient:true,representation:Array.from({length:64},(_,i)=>i===0?1:0),extractorVersion:"ecapa-v1",speechSeconds:2,silenceRatio:.2,clippingRatio:0,peakToNoiseDb:20}),identity:providedIdentity}={}){
  let n=0;const idFactory=()=>`00000000-0000-4000-8000-${String(++n).padStart(12,"0")}`,storage=createInMemoryStorage({clock:()=>new Date("2026-10-07T09:00:00Z")});await storage.initialize({owner:{id:OWNER,fullName:"Mohammad"}});
  let dialed=0;const phoneService={async prepare(input,context){const immutable=immutableCallEnvelope(input,{now:new Date("2026-10-07T09:00:00Z")}),{envelopeHash,...envelope}=immutable,id=`phone_${String(++n).padStart(32,"0")}`,call=await storage.createPhoneCallIntent({id,ownerId:OWNER,conversationId:context.conversationId,preparedRunId:context.runId,callConversationId:`phone-session-${id}`,envelope,envelopeHash,expiresAt:envelope.expiresAt});return callStartArguments(call);},async approvalRequired(input,approval){return storage.bindPhoneCallApproval(input.callIntentId,OWNER,{approvalId:approval.id,status:"waiting_for_approval"});},async approvalDecision(approval,decision){const call=await storage.getPhoneCallIntent(approval.arguments.callIntentId,OWNER);if(decision==="rejected"&&call.status==="waiting_for_approval"){const updated=await storage.updatePhoneCallIntent(call.id,OWNER,{status:"failed",outcome:"owner_rejected",errorCode:"phone_owner_rejected",endedAt:"2026-10-07T09:00:00Z"});await storage.updateSpeakerEnrollmentSession(call.envelope.enrollmentSessionId,OWNER,{status:"failed"});return updated;}return call;},async start(){dialed++;}};
  const identity=providedIdentity||{protectRepresentation:value=>value,revealRepresentation:value=>value,similarity:cosine,async enroll(){throw new Error("Calibration enrollment must be explicit.");}};
  const service=createPstnSpeakerEnrollment({storage,ownerId:OWNER,phoneService,speakerExtractor:{extract},speakerIdentity:identity,ownerNumber,clock:()=>new Date("2026-10-07T09:00:00Z"),idFactory});return{storage,service,get dialed(){return dialed;}};
}
const consent=service=>service.recordConsent({actor:"Mohammad",explicitConsent:true,consentVersion:PSTN_ENROLLMENT_CONSENT_VERSION});

test("PSTN enrollment fails closed without active consent and after revocation",async()=>{const f=await fixture();await assert.rejects(()=>f.service.prepareSession({sessionNumber:1}),error=>error.code==="pstn_enrollment_consent_required");const record=await consent(f.service);await f.service.revokeConsent(record.id);await assert.rejects(()=>f.service.prepareSession({sessionNumber:1}),error=>error.code==="pstn_enrollment_consent_required");});
test("consent is durable metadata but never dial authority",async()=>{const f=await fixture();const record=await consent(f.service),status=await f.service.status();assert.equal(record.status,"active");assert.equal(status.consent.version,PSTN_ENROLLMENT_CONSENT_VERSION);assert.equal(f.dialed,0);assert.doesNotMatch(JSON.stringify(record),/explicitly consent|transcript/i);});
test("Session 1 creates one immutable intent and one formal approval without dialing",async()=>{const f=await fixture();await consent(f.service);const first=await f.service.prepareSession({sessionNumber:1}),again=await f.service.prepareSession({sessionNumber:1});assert.equal(first.session.status,"waiting_for_approval");assert.deepEqual(first.session.phrasePlan.map(item=>item.language),["arabic","english","mixed"]);assert.equal(first.call.envelope.destination,DESTINATION);assert.equal(first.call.envelope.recordingPolicy,"disabled");assert.equal(first.call.envelope.mediaProfile,"speaker_enrollment_v1");assert.equal(first.approval.status,"pending");assert.equal(again.idempotent,true);assert.equal(again.approval.id,first.approval.id);assert.equal((await f.storage.listApprovals(OWNER,{status:"pending"})).length,1);assert.equal((await f.storage.getPhoneCallIntent(first.call.callIntentId,OWNER)).attemptCount,0);assert.equal(f.dialed,0);const view=approvalViewModel(first.approval);assert.equal(view.title,"Approve owner voice enrollment call");assert.match(JSON.stringify(view.fields),/Raw audio persistence.*disabled/);});
test("server-resolved wrong destination is denied",async()=>{const f=await fixture({ownerNumber:"+447700900123"});await consent(f.service);await assert.rejects(()=>f.service.prepareSession({sessionNumber:1}),error=>error.code==="pstn_enrollment_destination_invalid");});
test("schema 19 keeps consent sessions and temporary derived samples owner-scoped",()=>{assert.ok(SCHEMA_VERSION>=19);const schema=SCHEMA_STATEMENTS.join("\n");assert.match(schema,/nova_speaker_enrollment_consents/);assert.match(schema,/nova_speaker_enrollment_sessions/);assert.match(schema,/nova_speaker_enrollment_samples/);assert.match(schema,/encrypted_representation/);assert.doesNotMatch(schema,/raw_audio|audio_base64|recording_blob/i);});
test("quality rejection, idempotency and three samples cannot create six-sample calibration",async()=>{let calls=0;const f=await fixture({extract:async()=>{calls++;return calls===1?{sufficient:false,reason:"insufficient_speech",speechSeconds:.3,extractorVersion:"ecapa-v1"}:{sufficient:true,representation:Array.from({length:64},(_,i)=>i===0?1:0),extractorVersion:"ecapa-v1",speechSeconds:2,silenceRatio:.1,clippingRatio:0,peakToNoiseDb:20};}});await consent(f.service);const prepared=await f.service.prepareSession({sessionNumber:1}),id=prepared.session.id;await f.storage.updateSpeakerEnrollmentSession(id,OWNER,{status:"collecting"});const phrase=prepared.session.phrasePlan[0],bad=await f.service.submitSample({sessionId:id,submissionKey:"sample:bad:0001",ordinal:1,promptId:phrase.id,audioBase64:"AA==",mimeType:"audio/wav",durationSeconds:.3});assert.equal(bad.retry,true);assert.equal(bad.acceptedCount,0);const goodInput={sessionId:id,submissionKey:"sample:good:0001",ordinal:1,promptId:phrase.id,audioBase64:"AA==",mimeType:"audio/wav",durationSeconds:2},good=await f.service.submitSample(goodInput),replay=await f.service.submitSample(goodInput);assert.equal(good.acceptedCount,1);assert.equal(replay.idempotent,true);assert.equal(replay.acceptedCount,1);for(let ordinal=2;ordinal<=3;ordinal++){const item=prepared.session.phrasePlan[ordinal-1];await f.service.submitSample({sessionId:id,submissionKey:`sample:good:000${ordinal}`,ordinal,promptId:item.id,audioBase64:"AA==",mimeType:"audio/wav",durationSeconds:2});}assert.equal((await f.service.status()).sessions[0].status,"completed");assert.equal(await f.storage.getSpeakerChannelCalibration(OWNER,"pstn_8khz_v1"),null);const samples=await f.storage.listSpeakerEnrollmentSamples(OWNER,id);assert.equal(samples.filter(item=>item.status==="accepted").length,3);assert.ok(samples.every(item=>!("encryptedRepresentation" in item)));});
test("bridge enrollment gates capture on prompt acknowledgement, gives explicit speakerphone guidance, and retains no raw audio",async()=>{const sent=[],samples=[],spoken=[],authorization={bridgeSessionToken:"bridge",enrollment:{sessionId:"session",sessionNumber:2,expectedSamples:3,conditionLabel:"speakerphone",phrasePlan:[{id:"a",language:"arabic",text:"عبارة"},{id:"e",language:"english",text:"phrase"},{id:"m",language:"mixed",text:"عبارة phrase"}]}};const runtime=createSpeakerEnrollmentSession({sendTwilio:value=>sent.push(value),hangup(){},tts:{async *stream(text){spoken.push(text);yield Buffer.from([1,2,3]);}},novaClient:{async enrollmentSample(input){samples.push(input);return{retry:false};},async event(){}},authorization,callIntentId:"phone",callSid:"CA"+"1".repeat(32),streamSid:"MZ"+"2".repeat(32),maximumDurationSeconds:600,setTimer:()=>1,clearTimer(){}});await runtime.start();assert.equal(samples.length,0);assert.match(spoken[0],/السبيكر.*مسافة طبيعية.*صوتك الطبيعي/);const mark=sent.findLast(item=>item.event==="mark").mark.name;runtime.handle({event:"mark",streamSid:"MZ",mark:{name:mark}});assert.equal(runtime.metrics().rawAudioPersisted,false);await runtime.stop("completed","test",{hangupSocket:false});assert.equal(runtime.metrics().rawAudioPersisted,false);});
test("trusted session number renders distinct Session 1 and Session 2 completion wording",()=>{assert.match(speakerEnrollmentCompletionMessage(1),/الجلسة الأولى/);assert.match(speakerEnrollmentCompletionMessage(2),/الجلسة الثانية/);assert.doesNotMatch(speakerEnrollmentCompletionMessage(2),/الجلسة الأولى/);});
test("a zero-attempt pending Session 2 can be superseded once and replaced with unique speakerphone-bound authority",async()=>{const f=await fixture();await consent(f.service);const first=await f.service.prepareSession({sessionNumber:1});await f.storage.decideApproval(first.approval.id,OWNER,"approved");await f.storage.updateSpeakerEnrollmentSession(first.session.id,OWNER,{status:"collecting"});for(let ordinal=1;ordinal<=3;ordinal++){const item=first.session.phrasePlan[ordinal-1];await f.service.submitSample({sessionId:first.session.id,submissionKey:`session-1-sample-${ordinal}`,ordinal,promptId:item.id,audioBase64:"AA==",mimeType:"audio/wav",durationSeconds:2});}const old=await f.service.prepareSession({sessionNumber:2}),replacement=await f.service.replacePendingSession({sessionId:old.session.id,callIntentId:old.call.callIntentId,approvalId:old.approval.id}),again=await f.service.replacePendingSession({sessionId:old.session.id,callIntentId:old.call.callIntentId,approvalId:old.approval.id});assert.equal((await f.storage.getSpeakerEnrollmentSession(old.session.id,OWNER)).status,"failed");assert.equal((await f.storage.getPhoneCallIntent(old.call.callIntentId,OWNER)).attemptCount,0);assert.equal((await f.storage.getApproval(old.approval.id,OWNER)).status,"rejected");assert.equal(replacement.session.conditionLabel,"speakerphone");assert.equal(replacement.session.status,"waiting_for_approval");assert.equal(replacement.call.envelope.approvedContext.includes("acoustic condition: speakerphone"),true);assert.equal(replacement.call.envelope.permittedDisclosures.some(value=>value.includes("normal realistic distance")),true);const firstTexts=new Set(first.session.phrasePlan.map(item=>item.text));assert.ok(replacement.session.phrasePlan.every(item=>!firstTexts.has(item.text)));assert.equal(replacement.approval.status,"pending");assert.equal((await f.storage.getPhoneCallIntent(replacement.call.callIntentId,OWNER)).attemptCount,0);assert.equal(again.idempotent,true);assert.equal(again.session.id,replacement.session.id);assert.equal((await f.storage.listApprovals(OWNER,{status:"pending"})).length,1);assert.equal(f.dialed,0);const activity=await f.storage.listActivity(OWNER,{limit:20});assert.deepEqual(activity.find(item=>item.action==="pstn_speaker_enrollment_session_superseded").metadata.replacementReasonCodes,["repeated_enrollment_phrase","speakerphone_condition_not_explicit"]);});
test("six accepted samples complete evidence but never auto-create calibration or purge representations",async()=>{const f=await fixture();await consent(f.service);let firstPlan;for(const sessionNumber of[1,2]){const prepared=await f.service.prepareSession({sessionNumber}),id=prepared.session.id;assert.equal(prepared.session.conditionLabel,sessionNumber===1?"quiet_normal_handset":"speakerphone");if(sessionNumber===1)firstPlan=prepared.session.phrasePlan;else assert.ok(prepared.session.phrasePlan.every(item=>!new Set(firstPlan.map(value=>value.text)).has(item.text)));await f.storage.updateSpeakerEnrollmentSession(id,OWNER,{status:"collecting"});for(let ordinal=1;ordinal<=3;ordinal++){const item=prepared.session.phrasePlan[ordinal-1];await f.service.submitSample({sessionId:id,submissionKey:`session-${sessionNumber}-sample-${ordinal}`,ordinal,promptId:item.id,audioBase64:"AA==",mimeType:"audio/wav",durationSeconds:2});}}assert.equal(await f.storage.getSpeakerChannelCalibration(OWNER,"pstn_8khz_v1"),null);for(const session of(await f.service.status()).sessions)assert.ok((await f.storage.listSpeakerEnrollmentSamples(OWNER,session.id,{includeRepresentation:true})).every(item=>Array.isArray(item.encryptedRepresentation)));const readiness=await f.service.evaluateCalibrationReadiness();assert.equal(readiness.status,"ready");assert.equal(readiness.reason,"ready");assert.equal(readiness.calibrationCreated,false);assert.equal(readiness.ownerModeEnabled,false);assert.deepEqual(readiness.heldout.scores.map(item=>item.score),[1,1]);assert.equal(await f.storage.getSpeakerChannelCalibration(OWNER,"pstn_8khz_v1"),null);const activity=await f.storage.listActivity(OWNER,{limit:20});assert.equal(activity.filter(item=>item.action==="pstn_speaker_calibration_readiness_evaluated").length,1);});

test("readiness persists a safe held-out failure reason without profile creation",async()=>{const vectors=[[1,0],[1,0],[0,1],[1,0],[1,0],[0,1]],queue=[...Array(6).keys()];const f=await fixture({extract:async()=>({sufficient:true,representation:vectors[queue.shift()],extractorVersion:"ecapa-v1",speechSeconds:2,silenceRatio:.2,clippingRatio:0,peakToNoiseDb:20})});await consent(f.service);for(const sessionNumber of[1,2]){const prepared=await f.service.prepareSession({sessionNumber});await f.storage.updateSpeakerEnrollmentSession(prepared.session.id,OWNER,{status:"collecting"});for(let ordinal=1;ordinal<=3;ordinal++){const item=prepared.session.phrasePlan[ordinal-1];await f.service.submitSample({sessionId:prepared.session.id,submissionKey:`failed-heldout-${sessionNumber}-${ordinal}`,ordinal,promptId:item.id,audioBase64:"AA==",mimeType:"audio/wav",durationSeconds:2});}}const result=await f.service.evaluateCalibrationReadiness();assert.equal(result.status,"not_ready");assert.equal(result.reason,"heldout_score_below_threshold");assert.equal(result.heldout.minimum,0);assert.equal(await f.storage.getSpeakerChannelCalibration(OWNER,"pstn_8khz_v1"),null);assert.equal((await f.storage.listSpeakerProfiles(OWNER)).length,0);assert.equal(JSON.stringify(result).includes("encryptedRepresentation"),false);const diagnostic=(await f.storage.listActivity(OWNER,{limit:20})).find(item=>item.action==="pstn_speaker_calibration_readiness_evaluated");assert.equal(JSON.stringify(diagnostic).includes("encryptedRepresentation"),false);assert.equal(JSON.stringify(diagnostic).includes("ciphertext"),false);});
