import test from "node:test";
import assert from "node:assert/strict";
import {canonicalContentHash} from "../src/autonomy/self-development-plan-lifecycle.js";
import {createRejectedReviewPlanFixture,REJECTED_REVIEW_CLASS,REJECTED_REVIEW_HISTORY,REJECTED_REVIEW_BOUNDARY,assertRejectedReviewHistoriesPreserved} from "./rejected-review-plan-fixture.js";
import {PLANNING_PATHS} from "./planning-scope-fixture.js";

const record=task=>task.metadata[REJECTED_REVIEW_HISTORY]?.at(-1);
const boundary=task=>task.metadata[REJECTED_REVIEW_BOUNDARY];
const newSteps=async f=>(await f.steps()).filter(step=>Number.parseInt(step.stepId,10)>f.sourceTask.metadata.steps.length);
async function originalStepsPreserved(f){const current=await f.steps();for(const original of f.sourceSteps)assert.deepEqual(current.find(step=>step.stepId===original.stepId),original);}
const noDelivery=f=>assert.equal(f.commands.some(command=>command.args.some(arg=>["push","fetch","pull","clone","install","ci"].includes(arg))),false);

test("complete rejected v251 continuation revalidates eight current files, plans once and executes actual preflight apply focused/full to a new unresolved review boundary",async t=>{
  const f=await createRejectedReviewPlanFixture(t,{subset:true,verboseFull:true}),before=await f.current(),manifests=await Promise.all(["package.json","package-lock.json"].map(path=>f.read(path)));
  assert.equal(before.stateVersion,251);assert.equal(before.metadata.reviewRemediationHistory[0].consumed,true);assert.equal(before.metadata.escalatedRepairHistory.length,1);assert.equal(f.sourceRejectedStep.status,"failed");
  const approval=await f.authorize();assert.equal(approval.approval.tool,"self_development_rejected_review_plan_continuation");assert.equal(approval.approval.arguments.maxSteps,13);assert.equal(approval.approval.arguments.runtimeMinutes,15);
  const recovered=await f.recover(),generation=record(recovered.task);assert.equal(recovered.task.stateVersion,252);assert.equal(generation.recoveryClass,REJECTED_REVIEW_CLASS);assert.equal(generation.fromStateVersion,251);assert.notEqual(generation.activeContinuation.generationId,before.metadata.reviewRemediationHistory[0].activeContinuation.generationId);assertRejectedReviewHistoriesPreserved(before,recovered.task);await f.verifySourceUnchanged();
  await f.runSteps(8);assert.deepEqual(f.executions.map(item=>item.name),Array(8).fill("repo_read_task_owned_local"));assert.deepEqual(f.executions.map(item=>item.args.path),PLANNING_PATHS);assert.equal(f.prompts.length,0);assert.deepEqual((await newSteps(f)).map(step=>step.stepId),generation.readStepIds);assert.ok(generation.readStepIds.every(id=>!f.sourceReads.some(step=>step.stepId===id)));await f.verifySourceUnchanged();await originalStepsPreserved(f);
  for(const item of f.executions){assert.equal(item.result.content,f.afterContents.get(item.args.path));assert.equal(item.context.reviewRemediationScope.recoveryClass,REJECTED_REVIEW_CLASS);assert.equal(item.result.reviewRemediationEvidence.generationId,generation.activeContinuation.generationId);assert.equal(item.result.reviewRemediationEvidence.entries.length,8);}
  await f.runSteps(1);assert.equal(f.prompts.length,1);assert.equal(f.proposedPlans.length,1);assert.equal(f.prompts[0].reviewRemediation,true);assert.equal(f.prompts[0].scopeExpansionAllowed,false);assert.deepEqual(f.prompts[0].structuredReview,f.review);assert.deepEqual(f.prompts[0].candidateFiles.map(item=>({path:item.path,content:item.content})),PLANNING_PATHS.map(path=>({path,content:f.afterContents.get(path)})));assert.deepEqual(f.prompts[0].availableEvidenceExpansionTests,[]);
  assert.deepEqual(f.prompts[0].workspaceEvidence,{continuationGenerationId:generation.activeContinuation.generationId,sourcePlanStepId:generation.sourcePlanStepId,sourceApplyStepId:generation.sourceApplyStepId,sourceApplyFingerprint:generation.sourceApplyFingerprint,entries:generation.beforeEntries});
  const baselines=new Map(f.prompts[0].committedBaselineFiles.map(item=>[item.path,item.content]));assert.equal(baselines.size,7);for(const path of PLANNING_PATHS.filter(path=>path!=="test/composer-voice-console.integration.test.js"))assert.equal(baselines.get(path)?.trim(),await f.git("show",`HEAD:${path}`));
  const planned=await f.current(),plan=planned.metadata.selfDevelopmentImplementationPlan;assert.equal(plan.files.length,6);assert.equal(plan.reviewCoverage.length,5);assert.notEqual(plan.planHash,f.plan.planHash);assert.deepEqual(plan.evidencePaths,PLANNING_PATHS);for(const file of plan.files)assert.equal(file.expectedContent,f.afterContents.get(file.path));for(const mapping of plan.reviewCoverage)assert.equal(mapping.sourceHash,canonicalContentHash(plan.files.find(file=>file.path===mapping.testPath)?.content||f.afterContents.get(mapping.testPath)));
  await f.verifySourceUnchanged();await f.runSteps(1);assert.equal(f.executions.at(-1).name,"repo_validate_patch");assert.equal(f.executions.at(-1).result.preMutationValidated,true);assert.equal(f.executions.at(-1).result.mutationApplied,false);await f.verifySourceUnchanged();
  await f.runSteps(1);const apply=f.executions.at(-1);assert.equal(apply.name,"repo_apply_patch");assert.equal(apply.args.files.length,6);assert.equal(apply.result.taskOwnedDirtyLineage.entries.length,8);await f.verifyCandidate();
  await f.runSteps(1);const focused=f.executions.at(-1);assert.equal(focused.name,"test_run");assert.match(focused.result.output,/pass 7/);assert.equal(focused.result.outputTruncated,false);
  await f.runSteps(1);const full=f.executions.at(-1);assert.equal(full.name,"test_run_full");assert.match(full.result.output,/tests 8/);assert.match(full.result.output,/pass 8/);assert.equal(full.result.outputTruncated,true);assert.equal(full.result.output.length,20000);assert.equal(full.result.dependencyPreflight.resolved,true);assert.equal(full.result.dependencyPreflight.cwd,record(await f.current()).workspaceRoot);assert.deepEqual(full.result.dependencyPreflight.packages,[{name:"@neondatabase/serverless",version:"1.1.0"}]);
  const final=await f.current();assert.equal(final.status,"blocked");assert.equal(boundary(final).kind,"review_ready");assert.equal(boundary(final).executionAuthorized,false);assert.equal(boundary(final).findingsResolved,false);assert.equal(record(final).consumed,true);assert.equal(record(final).afterEntries.length,8);assert.deepEqual(record(final).unresolvedFindingIds,f.review.findings.filter(item=>item.severity==="blocking").map(item=>item.id));assertRejectedReviewHistoriesPreserved(before,final);await originalStepsPreserved(f);
  assert.deepEqual((await newSteps(f)).map(step=>step.stepType),[...Array(8).fill("read_files"),"plan_repair","validate_patch","apply_patch","run_focused_tests","run_full_tests"]);assert.ok((await newSteps(f)).every(step=>step.status==="completed"));assert.equal(f.executions.filter(item=>item.name==="repo_apply_patch").length,1);assert.deepEqual(await Promise.all(["package.json","package-lock.json"].map(path=>f.read(path))),manifests);await f.verifyCandidate();noDelivery(f);
  assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());await assert.rejects(()=>f.oldReviewRecover());await assert.rejects(()=>f.previousRetryRecover());await assert.rejects(()=>f.taskWorker.control(f.taskId,"resume"));assert.deepEqual(await f.current(),final);
  await assert.rejects(()=>f.hands.execute(apply.name,apply.args,apply.context));await assert.rejects(()=>f.hands.execute(full.name,full.args,full.context));assert.deepEqual(await f.current(),final);await f.verifyCandidate();
});

for(const[name,options,completed]of[["focused",{failingFocused:true},11],["full",{failingFull:true},12]])test(`new rejected-plan ${name} failure consumes only its new authority with no retry or repair extension`,async t=>{
  const f=await createRejectedReviewPlanFixture(t,options),before=await f.current();await f.authorize();await f.recover();await f.runSteps(completed);await assert.rejects(()=>f.worker.runOnce(),error=>error.code==="test_failed");
  const final=await f.current(),failed=(await newSteps(f)).at(-1);assert.equal(final.status,"blocked");assert.equal(boundary(final).kind,"product_repair_decision");assert.equal(boundary(final).executionAuthorized,false);assert.equal(record(final).consumed,true);assert.equal(failed.status,"failed");assert.equal(failed.attempt,1);assert.equal(failed.errorCode,"test_failed");assert.ok(failed.result.diagnostics.counts.failed>0);assert.equal(f.executions.filter(item=>item.name==="repo_apply_patch").length,1);assert.equal(f.executions.filter(item=>item.name==="test_run_full").length,name==="focused"?0:1);assertRejectedReviewHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifyCandidate();noDelivery(f);
  assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());assert.deepEqual(await f.current(),final);
});

for(const[name,alter,predicate]of[
  ["duplicate constraint coverage",value=>{value.reviewCoverage[4].constraintId=value.reviewCoverage[0].constraintId;},"complete_behavioral_coverage"],
  ["missing coverage",value=>{value.reviewCoverage.pop();},null],
  ["ninth mutation path",value=>{value.files[7]={...value.files[7],path:"test/ninth.test.js",operation:"create"};},null],
])test(`new reasoning plan rejects ${name} without autofill, replan or product mutation`,async t=>{
  const f=await createRejectedReviewPlanFixture(t,{output:value=>{alter(value);return value;}}),before=await f.current();await f.authorize();await f.recover();await f.runSteps(9);
  const final=await f.current(),failed=(await newSteps(f)).at(-1);assert.equal(failed.stepType,"plan_repair");assert.equal(failed.status,"failed");assert.equal(failed.attempt,1);assert.equal(f.prompts.length,1);assert.equal(f.proposedPlans.length,1);assert.equal(f.executions.length,8);assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assert.equal(final.status,"blocked");if(predicate)assert.equal(failed.result.diagnostics.predicate,predicate);if(name==="ninth mutation path")assert.match(boundary(final).kind,/authorization/);assertRejectedReviewHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifySourceUnchanged();noDelivery(f);assert.deepEqual(await f.worker.runOnce(),{worked:false});await assert.rejects(()=>f.recover());
});

test("historical eight reads cannot authorize current bytes after a canonical-equivalent raw drift",async t=>{
  const f=await createRejectedReviewPlanFixture(t),before=await f.current();await f.authorize();await f.recover();const original=await f.read("assets/console.css"),changed=original.replaceAll("\n","\r\n");assert.equal(canonicalContentHash(original),canonicalContentHash(changed));await f.drift("assets/console.css",changed);
  await assert.rejects(()=>f.worker.runOnce());const final=await f.current();assert.equal(f.prompts.length,0);assert.equal(f.executions.some(item=>item.name==="repo_apply_patch"),false);assert.equal(await f.read("assets/console.css"),changed);assertRejectedReviewHistoriesPreserved(before,final);await originalStepsPreserved(f);assert.equal(final.status,"blocked");assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assert.deepEqual(await f.worker.runOnce(),{worked:false});
});

test("successor Hands rejects a ninth-file injection after valid reasoning and preflight",async t=>{
  const f=await createRejectedReviewPlanFixture(t),before=await f.current();await f.authorize();await f.recover();await f.runSteps(10);f.hooks.execution=(name,args)=>{if(name==="repo_apply_patch")args.files.push({path:"test/ninth.test.js",operation:"create",content:"export const forbidden=true;\n"});};
  await assert.rejects(()=>f.worker.runOnce());const final=await f.current();assert.equal(final.status,"blocked");assert.equal(record(final).consumed,true);assert.equal(boundary(final).executionAuthorized,false);assertRejectedReviewHistoriesPreserved(before,final);await originalStepsPreserved(f);await f.verifySourceUnchanged();await assert.rejects(()=>f.read("test/ninth.test.js"),error=>error.code==="ENOENT");assert.deepEqual(await f.worker.runOnce(),{worked:false});
});

test("successor passing focused counts cannot hide an approved test that never registered",async t=>{
  const f=await createRejectedReviewPlanFixture(t,{output:value=>{const mapping=value.reviewCoverage[0],file=value.files.find(item=>item.path===mapping.testPath);file.content=file.content.replace(mapping.sourceExcerpt,`if (false) { ${mapping.sourceExcerpt} }`);return value;}}),before=await f.current();await f.authorize();await f.recover();await f.runSteps(11);await assert.rejects(()=>f.worker.runOnce());
  const final=await f.current(),focused=f.executions.find(item=>item.name==="test_run");assert.equal(focused.result.ok,true);assert.match(focused.result.output,/pass 6/);assert.match(focused.result.output,/fail 0/);assert.equal(final.status,"blocked");assert.equal(record(final).consumed,true);assert.equal(f.executions.some(item=>item.name==="test_run_full"),false);assertRejectedReviewHistoriesPreserved(before,final);await originalStepsPreserved(f);assert.deepEqual(await f.worker.runOnce(),{worked:false});
});
