import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createSelfDevelopmentExpiryRecovery,LIVE_SELF_DEVELOPMENT_RECOVERY as LIVE} from "../src/autonomy/self-development-expiry-recovery.js";
const OWNER="owner",types=["inspect_failure","inspect_repo","search_code","plan_patch","apply_patch","run_focused_tests","run_full_tests","inspect_diff","commit","review_commit","apply_patch","inspect_diff","commit","review_commit","push","deploy_preview"],completed=types.map((type,index)=>`${index+1}:${type}`);
const deployment=(patch={})=>({id:LIVE.deploymentId,url:LIVE.deploymentUrl,status:"READY",target:null,sha:LIVE.sha,branch:LIVE.branch,...patch});
async function fixture({task={},deploymentPatch={},wrap}={}){const base=createInMemoryStorage();await base.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});await base.createAutonomyTask({id:LIVE.taskId,ownerId:OWNER,projectId:"nova-brain",title:"Self Development",objective:"Acceptance",taskType:"self_development",branch:LIVE.branch,startingCommit:LIVE.sha,maxSteps:32,maxRuntimeMinutes:120,metadata:{steps:types.map(type=>({type})),selfDevelopmentDeliveryAttestation:{approvalId:LIVE.approvalId,commitSha:LIVE.sha,deploymentId:LIVE.deploymentId,preCommitReviewHash:LIVE.preCommitReviewHash,finalCommitReviewHash:LIVE.finalCommitReviewHash}}});await base.createApproval({id:LIVE.approvalId,ownerId:OWNER,projectId:"nova-brain",runId:LIVE.taskId,tool:"git_push",arguments:{branch:LIVE.branch,commitSha:LIVE.sha}});await base.decideApproval(LIVE.approvalId,OWNER,"approved");await base.updateAutonomyTask(LIVE.taskId,OWNER,{status:"expired",errorCode:"max_runtime_reached",currentStep:16,currentCommit:LIVE.sha,completedAt:new Date().toISOString(),checkpoint:{completedSteps:completed},...task});for(const [index,type] of types.entries())await base.recordAutonomyStep({taskId:LIVE.taskId,stepId:`${index+1}:${type}`,stepType:type,capability:"verified",operationFingerprint:`${index}:${type}`,status:"completed",result:{commitSha:LIVE.sha,deploymentId:LIVE.deploymentId}});const storage=wrap?wrap(base):base,service=createSelfDevelopmentExpiryRecovery({storage,ownerId:OWNER,verifyDeployment:async()=>deployment(deploymentPatch)}),current=await base.getAutonomyTask(LIVE.taskId,OWNER);return{base,service,input:{taskId:LIVE.taskId,runtimeMinutes:15,expectedVersion:current.stateVersion}};}
async function rejects(code,options={},change={}){const f=await fixture(options),before=await f.base.getAutonomyTask(LIVE.taskId,OWNER);await assert.rejects(()=>f.service.recover({...f.input,...change}),error=>error.code===code);assert.equal((await f.base.getAutonomyTask(LIVE.taskId,OWNER)).status,before.status);}
test("exact expired Self-Development delivery recovers",async()=>{const f=await fixture(),result=await f.service.recover(f.input);assert.equal(result.task.status,"queued");assert.equal(result.task.currentStep,16);assert.equal(result.task.maxRuntimeMinutes,15);});
test("unrelated task is rejected",()=>rejects("task_mismatch",{},{taskId:"other"}));
test("wrong expiry reason is rejected",()=>rejects("task_state_mismatch",{task:{errorCode:"other"}}));
test("missing push checkpoint is rejected",()=>rejects("checkpoint_mismatch",{task:{checkpoint:{completedSteps:completed.filter(x=>x!=="15:push")}}}));
test("missing deploy checkpoint is rejected",()=>rejects("checkpoint_mismatch",{task:{checkpoint:{completedSteps:completed.filter(x=>x!=="16:deploy_preview")}}}));
for(const [name,stepId,code] of [["duplicate push","15:push","duplicate_push_checkpoint"],["duplicate deploy","16:deploy_preview","duplicate_deploy_checkpoint"]])test(`${name} is rejected`,()=>rejects(code,{wrap:base=>Object.freeze({...base,listAutonomySteps:async id=>{const rows=await base.listAutonomySteps(id),item=rows.find(x=>x.stepId===stepId);return[...rows,{...item,operationFingerprint:`duplicate:${stepId}`}];}})}));
test("wrong acceptance SHA is rejected",()=>rejects("sha_mismatch",{task:{currentCommit:"a".repeat(40)}}));
test("wrong deployment is rejected",()=>rejects("deployment_mismatch",{deploymentPatch:{id:"other"}}));
test("deployment not READY is rejected",()=>rejects("deployment_not_ready",{deploymentPatch:{status:"BUILDING"}}));
test("deployment SHA mismatch is rejected",()=>rejects("deployment_sha_mismatch",{deploymentPatch:{sha:"a".repeat(40)}}));
test("deployment branch mismatch is rejected",()=>rejects("deployment_branch_mismatch",{deploymentPatch:{branch:"other"}}));
test("active lease is rejected",()=>rejects("active_lease_conflict",{task:{leaseOwner:"worker",leaseToken:"lease",leaseExpiresAt:"2099-01-01T00:00:00Z"}}));
test("state version conflict is rejected",()=>rejects("version_conflict",{},{expectedVersion:0}));
test("Production target is rejected",()=>rejects("production_target_forbidden",{deploymentPatch:{target:"production"}}));
test("main branch target is rejected",()=>rejects("branch_mismatch",{task:{branch:"main"}}));
test("original expiry and exact audit action remain durable",async()=>{const f=await fixture();await f.service.recover(f.input);const task=await f.base.getAutonomyTask(LIVE.taskId,OWNER),activity=await f.base.listActivity(OWNER,{runId:LIVE.taskId});assert.equal(task.metadata.selfDevelopmentPostAttestationRecovery.previousStatus,"expired");assert.equal(activity[0].action,"self_development_post_attestation_recovered");});
test("bounded runtime and all previous checkpoints are preserved",async()=>{const f=await fixture(),result=await f.service.recover(f.input);assert.equal(result.task.maxRuntimeMinutes,15);assert.deepEqual(result.task.checkpoint.completedSteps,completed);});
test("review bindings and consumed approval are preserved",async()=>{const f=await fixture();await f.service.recover(f.input);const task=await f.base.getAutonomyTask(LIVE.taskId,OWNER),approval=await f.base.getApproval(LIVE.approvalId,OWNER);assert.equal(task.metadata.selfDevelopmentDeliveryAttestation.preCommitReviewHash,LIVE.preCommitReviewHash);assert.equal(task.metadata.selfDevelopmentDeliveryAttestation.finalCommitReviewHash,LIVE.finalCommitReviewHash);assert.equal(approval.status,"approved");});
test("remaining plan contains verification and summary only",async()=>{const f=await fixture();await f.service.recover(f.input);const task=await f.base.getAutonomyTask(LIVE.taskId,OWNER),remaining=task.metadata.steps.slice(task.currentStep);assert.deepEqual(remaining.map(x=>x.input?.tool||x.type),["deployment_status_existing","preview_verify_existing","preview_storage_verify_existing","summarize"]);assert.equal(remaining.some(x=>["git_push","preview_deploy"].includes(x.input?.tool)),false);});
test("terminal success cannot precede final verification and summary",async()=>{const f=await fixture(),result=await f.service.recover(f.input);assert.equal(result.task.status,"queued");assert.equal(result.task.currentStep,16);});
