import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createSelfDevelopmentImplementationPlanner} from "../src/autonomy/self-development-implementation-planner.js";
import {createWorkerRuntime} from "../src/autonomy/worker-runtime.js";

const OWNER="owner",BRANCH="feat/nova-brain-mvp-foundation",SHA="a".repeat(40),DOC="docs/planner-acceptance.md",TEST="test/planner-acceptance.test.js";
async function fixture(output){const storage=createInMemoryStorage();await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});await storage.createAutonomyTask({id:"selfdev-plan",ownerId:OWNER,projectId:"nova-brain",title:"Planner",objective:"Update harmless documentation",taskType:"self_development",branch:BRANCH,startingCommit:SHA,maxRuntimeMinutes:60,metadata:{steps:[],selfDevelopment:{userGoal:"Update harmless documentation",acceptanceCriteria:["Document is updated"]}}});for(const [index,[path,content]] of [[DOC,"old doc"],[TEST,"old test"]].entries())await storage.recordAutonomyStep({taskId:"selfdev-plan",stepId:`${index+1}:read_files`,stepType:"read_files",capability:"repo_read_remote",operationFingerprint:path,status:"completed",input:{arguments:{path}},result:{path,content,truncated:false}});let prompt;const modelProvider={async generate(input){prompt=input;return{type:"final",message:JSON.stringify(output||{files:[{path:DOC,content:"new doc",reason:"acceptance",intendedChanges:["update marker"]}],focusedTests:[TEST],acceptanceMapping:[{criterion:"Document is updated",files:[DOC]}],riskLevel:"medium",summary:"Bounded documentation update"})};}},planner=createSelfDevelopmentImplementationPlanner({modelProvider,storage,ownerId:OWNER});return{storage,planner,getPrompt:()=>prompt};}
test("Nova generates a structured patch solely from durable read evidence",async()=>{const f=await fixture(),result=await f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA});assert.equal(result.implementationPlan.files[0].content,"new doc");assert.equal(result.implementationPlan.files[0].expectedContent,"old doc");assert.match(f.getPrompt().message,/old doc/);assert.match(f.getPrompt().systemContext,/Use only candidateFiles/);});
test("planner rejects caller paths without complete durable evidence",async()=>{const f=await fixture();await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,"test/missing.test.js"],currentCommit:SHA}),e=>e.code==="implementation_evidence_incomplete");});
test("planner rejects protected Voice and runtime candidates",async()=>{for(const path of["assets/voice-control.js","src/autonomy/worker-runtime.js"]){const f=await fixture();await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[path,TEST],currentCommit:SHA}),e=>e.code==="protected_scope_requires_approval");}});
test("planner rejects model output outside the candidate set",async()=>{const f=await fixture({files:[{path:"src/unrelated.js",content:"x",reason:"x",intendedChanges:[]}],focusedTests:[TEST],acceptanceMapping:[],riskLevel:"medium",summary:"x"});await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),e=>e.code==="implementation_scope_violation");});
test("planner rejects malformed, tool-call, and swapped acceptance evidence",async()=>{const f=await fixture({files:[{path:DOC,content:"x",reason:"x",intendedChanges:[]}],focusedTests:[TEST],acceptanceMapping:[{criterion:"x",files:[TEST]}],riskLevel:"medium",summary:"x"});await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),e=>e.code==="implementation_plan_invalid");});
test("durable Worker passes Nova's generated patch to Hands and continues the same task",async()=>{const f=await fixture(),generated=await f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),calls=[];await f.storage.updateAutonomyTask("selfdev-plan",OWNER,{status:"queued",metadata:{steps:[{type:"plan_implementation",capability:"reasoning",input:{tool:"self_development_plan_implementation",arguments:{}},idempotencyIdentity:"plan"},{type:"apply_patch",capability:"repo_mutate_local",input:{tool:"repo_apply_patch",arguments:{files:"$IMPLEMENTATION_FILES"}},idempotencyIdentity:"apply"}],selfDevelopment:{userGoal:"Update harmless documentation",acceptanceCriteria:["Document is updated"]}}});const runtime=createWorkerRuntime({storage:f.storage,ownerId:OWNER,approvedBranch:BRANCH,capabilities:["reasoning","repo_mutate_local"],toolRegistry:{async execute(name,args){calls.push({name,args});return name==="self_development_plan_implementation"?generated:{ok:true,files:args.files.map(x=>x.path)};}}});await runtime.tickTask("selfdev-plan",{idempotencyKey:"plan"});await runtime.tickTask("selfdev-plan",{idempotencyKey:"apply"});assert.deepEqual(calls.map(x=>x.name),["self_development_plan_implementation","repo_apply_patch"]);assert.equal(calls[1].args.files[0].content,"new doc");assert.equal((await runtime.get("selfdev-plan")).currentStep,2);});
