import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createSelfDevelopmentImplementationPlanner,SELF_DEVELOPMENT_IMPLEMENTATION_PLAN_SCHEMA} from "../src/autonomy/self-development-implementation-planner.js";
import {createWorkerRuntime} from "../src/autonomy/worker-runtime.js";

const OWNER="owner",BRANCH="feat/nova-brain-mvp-foundation",SHA="a".repeat(40),DOC="docs/planner-acceptance.md",TEST="test/planner-acceptance.test.js";
const valid=()=>({files:[{path:DOC,operation:"replace",content:"new doc",reason:"acceptance",intendedChanges:["update marker"]}],focusedTests:[TEST],acceptanceMapping:[{criterion:"Document is updated",files:[DOC]}],riskLevel:"medium",summary:"Bounded documentation update"});
async function fixture(outputs=[valid()]){const storage=createInMemoryStorage();await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});await storage.createAutonomyTask({id:"selfdev-plan",ownerId:OWNER,projectId:"nova-brain",title:"Planner",objective:"Update harmless documentation",taskType:"self_development",branch:BRANCH,startingCommit:SHA,maxRuntimeMinutes:60,metadata:{steps:[],selfDevelopment:{userGoal:"Update harmless documentation",acceptanceCriteria:["Document is updated"]}}});for(const [index,[path,content]] of [[DOC,"old doc"],[TEST,"old test"]].entries())await storage.recordAutonomyStep({taskId:"selfdev-plan",stepId:`${index+1}:read_files`,stepType:"read_files",capability:"repo_read_remote",operationFingerprint:path,status:"completed",input:{arguments:{path}},result:{path,content,truncated:false}});let prompts=[],calls=0;const modelProvider={async generate(input){prompts.push(input);const output=outputs[Math.min(calls++,outputs.length-1)];return output?.type?output:{type:"final",message:typeof output==="string"?output:JSON.stringify(output)};}},planner=createSelfDevelopmentImplementationPlanner({modelProvider,storage,ownerId:OWNER});return{storage,planner,prompts,get calls(){return calls;}};}

test("canonical valid structured output produces the Hands replacement representation",async()=>{const f=await fixture(),result=await f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA});assert.equal(result.implementationPlan.files[0].operation,"replace");assert.equal(result.implementationPlan.files[0].expectedContent,"old doc");assert.deepEqual(f.prompts[0].responseFormat,{name:"nova_self_development_implementation_plan",schema:SELF_DEVELOPMENT_IMPLEMENTATION_PLAN_SCHEMA,strict:true});});
test("schema-imperfect output receives safe feedback and corrects within the same evidence",async()=>{const imperfect={files:[DOC],tests:[TEST],risk:"medium",summary:"x"},f=await fixture([imperfect,valid()]),result=await f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA});assert.equal(f.calls,2);assert.equal(result.implementationPlan.files[0].path,DOC);assert.match(f.prompts[1].message,/file_0_object_required/);assert.match(f.prompts[1].message,/acceptance_mapping_invalid/);});
test("identical malformed output is bounded and exposes only issue codes and a hash",async()=>{const malformed={files:[DOC],focusedTests:[TEST],acceptanceMapping:[],riskLevel:"medium",summary:"x"},f=await fixture([malformed,malformed]);await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),error=>error.code==="implementation_plan_invalid"&&error.safeDiagnostics.formatAttempts===2&&error.safeDiagnostics.validationIssues.includes("file_0_object_required")&&/^[a-f0-9]{64}$/.test(error.safeDiagnostics.outputShapeHash));assert.equal(f.calls,2);});
test("markdown JSON fence is harmless but explanatory prose is rejected deterministically",async()=>{const fenced=await fixture([`\`\`\`json\n${JSON.stringify(valid())}\n\`\`\``]);assert.ok((await fenced.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA})).ok);const prose=await fixture([`Here is the plan: ${JSON.stringify(valid())}`]);await assert.rejects(()=>prose.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),error=>error.code==="implementation_plan_invalid");});
test("missing fields, unknown paths, and protected or unread evidence fail closed",async()=>{const missing=await fixture([{files:[],focusedTests:[TEST],acceptanceMapping:[],riskLevel:"medium",summary:"x"}]);await assert.rejects(()=>missing.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),e=>e.code==="implementation_plan_invalid");const outside=valid();outside.files[0].path="src/unrelated.js";await assert.rejects(()=>fixture([outside]).then(f=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA})),e=>e.code==="implementation_scope_violation");const f=await fixture();await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,"test/missing.test.js"],currentCommit:SHA}),e=>e.code==="implementation_evidence_incomplete");await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:["assets/voice-control.js",TEST],currentCommit:SHA}),e=>e.code==="protected_scope_requires_approval");});
test("acceptance mapping cannot substitute an unmodified test file",async()=>{const output=valid();output.acceptanceMapping[0].files=[TEST];const f=await fixture([output]);await assert.rejects(()=>f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),e=>e.code==="implementation_plan_invalid");});
test("durable Worker passes only the validated Nova patch to Hands",async()=>{const f=await fixture(),generated=await f.planner.generate({taskId:"selfdev-plan",candidatePaths:[DOC,TEST],currentCommit:SHA}),calls=[];await f.storage.updateAutonomyTask("selfdev-plan",OWNER,{status:"queued",metadata:{steps:[{type:"plan_implementation",capability:"reasoning",input:{tool:"self_development_plan_implementation",arguments:{}},idempotencyIdentity:"plan"},{type:"apply_patch",capability:"repo_mutate_local",input:{tool:"repo_apply_patch",arguments:{files:"$IMPLEMENTATION_FILES"}},idempotencyIdentity:"apply"}],selfDevelopment:{userGoal:"Update harmless documentation",acceptanceCriteria:["Document is updated"]}}});const runtime=createWorkerRuntime({storage:f.storage,ownerId:OWNER,approvedBranch:BRANCH,capabilities:["reasoning","repo_mutate_local"],toolRegistry:{async execute(name,args){calls.push({name,args});return name==="self_development_plan_implementation"?generated:{ok:true,files:args.files.map(x=>x.path)};}}});await runtime.tickTask("selfdev-plan",{idempotencyKey:"plan"});await runtime.tickTask("selfdev-plan",{idempotencyKey:"apply"});assert.deepEqual(calls.map(x=>x.name),["self_development_plan_implementation","repo_apply_patch"]);assert.equal(calls[1].args.files[0].content,"new doc");assert.equal(calls[1].args.files[0].operation,"replace");});
