import test from "node:test";
import assert from "node:assert/strict";
import {activeContinuationExceeded,assertActiveImplementationPlan,bindImplementationPlan,canonicalContentHash,createActiveContinuation,planLifecycleMetadata,rebindEquivalentImplementationPlan} from "../src/autonomy/self-development-plan-lifecycle.js";

const SHA="a".repeat(40),NEXT="b".repeat(40);
const baseTask=(overrides={})=>({id:"selfdev_exact",currentCommit:SHA,currentStep:101,maxSteps:100,metadata:{implementationPlanGenerations:[]},...overrides});
const source="const value = 1;\n";
const makePlan=(task=baseTask(),content=source)=>{const plan={planHash:"plan-hash",files:[{path:"assets/voice-input.js",operation:"replace",expectedContent:content,content:"const value = 2;\n"}]};plan.provenance=bindImplementationPlan({task,plan,evidence:[{path:"assets/voice-input.js",content}],readStepIds:["81:read_files"]});return plan;};

test("active generation is bound to exact task commit and canonical evidence",()=>{const task=baseTask(),plan=makePlan(task),metadata=planLifecycleMetadata(task,plan),bound={...task,metadata};assert.equal(assertActiveImplementationPlan(bound,plan.files).currentCommit,SHA);assert.equal(plan.provenance.mutationPreconditions[0].expectedContentHash,canonicalContentHash(source));assert.throws(()=>assertActiveImplementationPlan({...bound,currentCommit:NEXT},plan.files),error=>error.code==="implementation_plan_stale");});

test("CRLF representation is canonical but a real content change is rejected",()=>{const task=baseTask(),plan=makePlan(task,"const value = 1;\r\n"),bound={...task,metadata:planLifecycleMetadata(task,plan)};assert.doesNotThrow(()=>assertActiveImplementationPlan(bound,[{...plan.files[0],expectedContent:source}]));assert.throws(()=>assertActiveImplementationPlan(bound,[{...plan.files[0],expectedContent:"const value = 9;\n"}]),error=>error.code==="implementation_plan_precondition_mismatch");});

test("new plan generation supersedes the old generation and rejects stale authority",()=>{const task=baseTask(),first=makePlan(task),firstMetadata=planLifecycleMetadata(task,first),second=makePlan({...task,metadata:firstMetadata},source+"// evidence\n"),metadata=planLifecycleMetadata({...task,metadata:firstMetadata},second),bound={...task,metadata};assert.equal(metadata.implementationPlanGenerations.filter(item=>item.authority==="active").length,1);assert.equal(metadata.implementationPlanGenerations[0].authority,"superseded");assert.equal(assertActiveImplementationPlan(bound,second.files).generationId,second.provenance.generationId);assert.throws(()=>assertActiveImplementationPlan({...bound,metadata:{...metadata,selfDevelopmentImplementationPlan:first}},first.files),error=>error.code==="implementation_plan_superseded");});

test("descendant rebind retains intent only with complete exact precondition equivalence",()=>{const originalTask=baseTask(),original=makePlan(originalTask),nextTask={...originalTask,currentCommit:NEXT};const rebound=rebindEquivalentImplementationPlan({task:nextTask,plan:original,evidence:[{path:"assets/voice-input.js",content:source.replaceAll("\n","\r\n")}],readStepIds:["106:read_files"]});assert.equal(rebound.provenance.currentCommit,NEXT);assert.notEqual(rebound.provenance.generationId,original.provenance.generationId);assert.throws(()=>rebindEquivalentImplementationPlan({task:nextTask,plan:original,evidence:[{path:"assets/voice-input.js",content:"changed\n"}]}),error=>error.code==="implementation_plan_equivalence_unproven");});

test("active continuation budget is independent of lifetime step numbering",()=>{const task=baseTask(),active=createActiveContinuation({task,startStep:101,plannedSteps:12,repairLimit:2,recoveryClass:"patch_conflict_plan_lifecycle"}),continued={...task,metadata:{activeContinuation:active}};assert.equal(active.maxSteps,16);assert.equal(activeContinuationExceeded(continued),false);assert.equal(activeContinuationExceeded({...continued,currentStep:116}),false);assert.equal(activeContinuationExceeded({...continued,currentStep:117}),true);assert.equal(activeContinuationExceeded({...task,currentStep:100,metadata:{}}),true);});
