import test from "node:test";
import assert from "node:assert/strict";
import { readConfig } from "../src/config/env.js";
import { createSpeakerExtractor, SpeakerExtractorError } from "../src/voice/speaker-extractor.js";

const environment={NOVA_SPEAKER_EXTRACTOR_URL:"https://worker.example",NOVA_SPEAKER_EXTRACTOR_TOKEN:"private-token",NOVA_SPEAKER_EXTRACTOR_MODEL:"ecapa-test"};
test("speaker embedding adapter sends ephemeral audio with server-side authentication and validates vectors",async()=>{
  let call;const extractor=createSpeakerExtractor({config:readConfig(environment),fetchImpl:async(url,options)=>{call={url,options};return new Response(JSON.stringify({embedding:Array(192).fill(0).map((_,i)=>i?0:1),compatibilityEmbedding:Array(192).fill(0).map((_,i)=>i===1?1:0),model:"ecapa-test",totalDurationSeconds:2.8,speechSeconds:2.2,silenceRatio:.214,sampleRate:48000,channelCount:1,preprocessingVersion:"decode-mono-16k-rms-vad-v3-compat",voicedSegmentCount:3,longestVoicedSegmentSeconds:1.2,clippingRatio:0,noiseFloorRms:.002,activeThresholdRms:.004,speechRms:.08,peakRms:.2,peakToNoiseDb:40,quality:"accepted"}),{status:200,headers:{"content-type":"application/json"}});}});
  const result=await extractor.extract({audioBase64:"YXVkaW8=",mimeType:"audio/webm",durationSeconds:2.2});
  assert.equal(result.sufficient,true);assert.equal(result.representation.length,192);assert.equal(result.representationVariants.length,2);assert.equal(result.representationVariants[1].label,"legacy_full_waveform");assert.equal(result.totalDurationSeconds,2.8);assert.equal(result.speechSeconds,2.2);assert.equal(result.silenceRatio,.214);assert.equal(result.preprocessingVersion,"decode-mono-16k-rms-vad-v3-compat");assert.equal(result.voicedSegmentCount,3);assert.equal(result.longestVoicedSegmentSeconds,1.2);assert.equal(result.peakToNoiseDb,40);assert.equal(call.url,"https://worker.example/embed");assert.equal(call.options.headers.Authorization,"Bearer private-token");assert.equal(JSON.parse(call.options.body).audioBase64,"YXVkaW8=");
});
test("short speech remains unknown without contacting the biometric worker",async()=>{let calls=0;const extractor=createSpeakerExtractor({config:readConfig(environment),fetchImpl:async()=>{calls++;}});const result=await extractor.extract({audioBase64:"YQ==",mimeType:"audio/webm",durationSeconds:.2});assert.deepEqual(result,{sufficient:false,reason:"insufficient_speech",durationSeconds:.2,extractorVersion:"ecapa-test"});assert.equal(calls,0);});
test("worker-measured short speech fails closed even when the recording wall time is long",async()=>{const extractor=createSpeakerExtractor({config:readConfig(environment),fetchImpl:async()=>new Response(JSON.stringify({embedding:Array(192).fill(0).map((_,i)=>i?0:1),model:"ecapa-test",speechSeconds:.35,quality:"accepted"}),{status:200,headers:{"content-type":"application/json"}})});const result=await extractor.extract({audioBase64:"YXVkaW8=",mimeType:"audio/webm",durationSeconds:2.5});assert.equal(result.sufficient,false);assert.equal(result.reason,"insufficient_speech");assert.equal(result.durationSeconds,.35);assert.equal("representation" in result,false);});
test("worker-rejected speech quality fails closed with its safe reason and diagnostics",async()=>{const extractor=createSpeakerExtractor({config:readConfig(environment),fetchImpl:async()=>new Response(JSON.stringify({model:"ecapa-test",totalDurationSeconds:2.5,speechSeconds:.3,silenceRatio:.88,sampleRate:48000,channelCount:1,preprocessingVersion:"decode-mono-16k-rms-vad-v2",quality:"rejected",reason:"insufficient_voiced_speech"}),{status:200,headers:{"content-type":"application/json"}})});const result=await extractor.extract({audioBase64:"YXVkaW8=",mimeType:"audio/webm",durationSeconds:2.5});assert.equal(result.sufficient,false);assert.equal(result.quality,"rejected");assert.equal(result.reason,"insufficient_voiced_speech");assert.equal(result.silenceRatio,.88);assert.equal(result.preprocessingVersion,"decode-mono-16k-rms-vad-v2");assert.equal("representation" in result,false);});
test("unconfigured and malformed worker responses fail closed",async()=>{const missing=createSpeakerExtractor({config:readConfig({})});await assert.rejects(()=>missing.extract({audioBase64:"YQ==",mimeType:"audio/webm",durationSeconds:2}),SpeakerExtractorError);const malformed=createSpeakerExtractor({config:readConfig(environment),fetchImpl:async()=>new Response(JSON.stringify({embedding:[1,2]}),{status:200})});await assert.rejects(()=>malformed.extract({audioBase64:"YQ==",mimeType:"audio/webm",durationSeconds:2}),/invalid embedding/i);});
