import test from "node:test";
import assert from "node:assert/strict";
import { createInMemoryStorage } from "../src/storage/in-memory-storage.js";
import { createSpeakerIdentity, contextPolicyForSpeaker } from "../src/voice/speaker-identity.js";

async function setup(){const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});return {storage,speakers:createSpeakerIdentity({storage,ownerId:"owner",threshold:0.86,ambiguityMargin:0.04})};}
const samples=(vector)=>[vector,vector.map((value,index)=>value+(index?0.002:-0.002)),vector.map((value,index)=>value+(index?-0.002:0.002))];

test("speaker enrollment requires explicit consent and never exposes representations",async()=>{const {storage,speakers}=await setup();await assert.rejects(()=>speakers.enroll({displayName:"Owner",relation:"owner",consent:false,consentActor:"owner",sampleRepresentations:samples([1,0,0])}),/consent/i);const profile=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner speaking",sampleRepresentations:samples([1,0,0])});assert.equal(profile.representation,undefined);assert.equal((await speakers.list())[0].representation,undefined);assert.equal((await storage.listMemories("owner")).length,0);});

test("recognition confirms enrolled owner and second speaker but conservatively rejects unknown and ambiguous probes",async()=>{const {speakers}=await setup();const owner=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0])});const second=await speakers.enroll({displayName:"Wife",relation:"family",consent:true,consentActor:"Wife",sampleRepresentations:samples([0,1,0])});assert.equal((await speakers.recognize([.99,.01,0])).speakerProfileId,owner.id);assert.equal((await speakers.recognize([.01,.99,0])).speakerProfileId,second.id);assert.equal((await speakers.recognize([0,0,1])).state,"unknown");assert.equal((await speakers.recognize([.7,.7,0])).state,"unknown");});

test("revoked and deleted profiles cannot be recognized and lifecycle is audited",async()=>{const {storage,speakers}=await setup();const profile=await speakers.enroll({displayName:"Member",relation:"family",consent:true,consentActor:"Member",sampleRepresentations:samples([1,0,0])});await speakers.revoke(profile.id);assert.equal((await speakers.recognize([1,0,0])).state,"unknown");const second=await speakers.enroll({displayName:"Second",relation:"family",consent:true,consentActor:"Second",sampleRepresentations:samples([0,1,0])});assert.equal(await speakers.delete(second.id),true);assert.equal((await speakers.recognize([0,1,0])).state,"unknown");const actions=(await storage.listActivity("owner",{limit:20})).map(({action})=>action);assert.ok(actions.includes("speaker_enrolled"));assert.ok(actions.includes("speaker_revoked"));assert.ok(actions.includes("speaker_deleted"));});

test("speaker context policy isolates owner-private memory",()=>{assert.equal(contextPolicyForSpeaker({state:"confirmed",relation:"owner"}),"owner_private");assert.equal(contextPolicyForSpeaker({state:"confirmed",relation:"family"}),"profile_scoped");assert.equal(contextPolicyForSpeaker({state:"unknown"}),"public_only");});

test("VoiceUtterance supports nullable speaker diarization without pretending unknown identity",async()=>{const {storage,speakers}=await setup();await storage.ensureConversation({id:"conversation",ownerId:"owner"});const utterance=await speakers.recordUtterance({conversationId:"conversation",speakerLabel:"unknown",confidence:.4,text:"Hello",startedAtMs:100,endedAtMs:700});assert.equal(utterance.speakerProfileId,null);assert.equal((await storage.listVoiceUtterances("conversation","owner"))[0].speakerLabel,"unknown");});

test("real-mode speaker representations are encrypted at rest and remain matchable",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",embeddingKey:"a-preview-encryption-key-with-at-least-32-bytes",requireEncryption:true});const enrolled=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0]),representationVersion:"ecapa-test"});const stored=(await storage.listSpeakerProfiles("owner",{includeRepresentation:true}))[0];assert.equal(stored.representation.algorithm,"aes-256-gcm");assert.equal(JSON.stringify(stored.representation).includes("[1,0,0]"),false);assert.equal((await speakers.recognize([1,0,0])).speakerProfileId,enrolled.id);});
