import test from "node:test";
import assert from "node:assert/strict";
import { createInMemoryStorage } from "../src/storage/in-memory-storage.js";
import { createSpeakerIdentity, contextPolicyForSpeaker } from "../src/voice/speaker-identity.js";

async function setup(){const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});return {storage,speakers:createSpeakerIdentity({storage,ownerId:"owner",threshold:0.86,ambiguityMargin:0.04})};}
const samples=(vector)=>[vector,vector.map((value,index)=>value+(index?0.002:-0.002)),vector.map((value,index)=>value+(index?-0.002:0.002))];

test("speaker enrollment requires explicit consent and never exposes representations",async()=>{const {storage,speakers}=await setup();await assert.rejects(()=>speakers.enroll({displayName:"Owner",relation:"owner",consent:false,consentActor:"owner",sampleRepresentations:samples([1,0,0])}),/consent/i);const profile=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner speaking",sampleRepresentations:samples([1,0,0])});assert.equal(profile.representation,undefined);assert.equal((await speakers.list())[0].representation,undefined);assert.equal((await storage.listMemories("owner")).length,0);});

test("recognition confirms enrolled owner and second speaker but conservatively rejects unknown probes",async()=>{const {speakers}=await setup();const owner=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0])});const second=await speakers.enroll({displayName:"Wife",relation:"family",consent:true,consentActor:"Wife",sampleRepresentations:samples([0,1,0])});const ownerMatch=await speakers.recognize([.99,.01,0]);assert.equal(ownerMatch.speakerProfileId,owner.id);assert.equal(ownerMatch.candidateCount,2);assert.equal((await speakers.recognize([.01,.99,0])).speakerProfileId,second.id);assert.equal((await speakers.recognize([0,0,1])).state,"unknown");assert.equal((await speakers.recognize([.7,.7,0])).state,"unknown");});

test("recognition reports uncertain when two strong candidates are too close",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",threshold:.8,ambiguityMargin:.05});await speakers.enroll({displayName:"First",relation:"owner",consent:true,consentActor:"First",sampleRepresentations:samples([1,0,0])});await speakers.enroll({displayName:"Second",relation:"family",consent:true,consentActor:"Second",sampleRepresentations:samples([.98,.2,0])});const match=await speakers.recognize([.995,.1,0]);assert.equal(match.state,"uncertain");assert.equal(match.candidateCount,2);});

test("approved Preview ECAPA boundary accepts observed owner scores and rejects lower scores",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",threshold:.35,ambiguityMargin:.05});const owner=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0])});const accepted=await speakers.recognize([.392,Math.sqrt(1-.392**2),0]);assert.equal(accepted.state,"confirmed");assert.equal(accepted.speakerProfileId,owner.id);assert.equal(accepted.threshold,.35);assert.equal(accepted.bestCandidateCategory,"owner");const rejected=await speakers.recognize([.349,Math.sqrt(1-.349**2),0]);assert.equal(rejected.state,"unknown");assert.equal(rejected.bestCandidateCategory,"owner");});

test("legacy enrollment compatibility can confirm without changing the threshold or stored owner profile",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",threshold:.35,ambiguityMargin:.05});const owner=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0])});const match=await speakers.recognizeMany([{label:"vad_v3",representation:[.341,Math.sqrt(1-.341**2),0]},{label:"legacy_full_waveform",representation:[.46,Math.sqrt(1-.46**2),0]}]);assert.equal(match.state,"confirmed");assert.equal(match.speakerProfileId,owner.id);assert.equal(match.threshold,.35);assert.equal(match.matchVariant,"legacy_full_waveform");assert.equal((await speakers.list()).length,1);});

test("revoked and deleted profiles cannot be recognized and lifecycle is audited",async()=>{const {storage,speakers}=await setup();const profile=await speakers.enroll({displayName:"Member",relation:"family",consent:true,consentActor:"Member",sampleRepresentations:samples([1,0,0])});await speakers.revoke(profile.id);assert.equal((await speakers.recognize([1,0,0])).state,"unknown");const second=await speakers.enroll({displayName:"Second",relation:"family",consent:true,consentActor:"Second",sampleRepresentations:samples([0,1,0])});assert.equal(await speakers.delete(second.id),true);assert.equal((await speakers.recognize([0,1,0])).state,"unknown");const actions=(await storage.listActivity("owner",{limit:20})).map(({action})=>action);assert.ok(actions.includes("speaker_enrolled"));assert.ok(actions.includes("speaker_revoked"));assert.ok(actions.includes("speaker_deleted"));});

test("speaker context policy isolates owner-private memory",()=>{assert.equal(contextPolicyForSpeaker({state:"confirmed",relation:"owner"}),"owner_private");assert.equal(contextPolicyForSpeaker({state:"confirmed",relation:"family"}),"profile_scoped");assert.equal(contextPolicyForSpeaker({state:"unknown"}),"public_only");});

test("VoiceUtterance supports nullable speaker diarization without pretending unknown identity",async()=>{const {storage,speakers}=await setup();await storage.ensureConversation({id:"conversation",ownerId:"owner"});const utterance=await speakers.recordUtterance({conversationId:"conversation",speakerLabel:"unknown",confidence:.4,text:"Hello",startedAtMs:100,endedAtMs:700});assert.equal(utterance.speakerProfileId,null);assert.equal((await storage.listVoiceUtterances("conversation","owner"))[0].speakerLabel,"unknown");});

test("real-mode speaker representations are encrypted at rest and remain matchable",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",embeddingKey:"a-preview-encryption-key-with-at-least-32-bytes",requireEncryption:true});const enrolled=await speakers.enroll({displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0]),representationVersion:"ecapa-test"});const stored=(await storage.listSpeakerProfiles("owner",{includeRepresentation:true}))[0];assert.equal(stored.representation.algorithm,"aes-256-gcm");assert.equal(JSON.stringify(stored.representation).includes("[1,0,0]"),false);assert.equal((await speakers.recognize([1,0,0])).speakerProfileId,enrolled.id);});

test("invalid owner enrollment purge deletes voiceprint, scrubs assertions data, and removes identifying audits",async()=>{const {storage,speakers}=await setup();const profile=await speakers.enroll({displayName:"Invalid Owner",relation:"owner",consent:true,consentActor:"invalid",sampleRepresentations:samples([1,0,0])});await storage.ensureConversation({id:"purge-conversation",ownerId:"owner"});await speakers.recordUtterance({conversationId:"purge-conversation",speakerProfileId:profile.id,speakerLabel:"owner",confidence:.99,text:"invalid",startedAtMs:0,endedAtMs:2000});const purged=await speakers.purgeInvalidOwnerEnrollment();assert.equal(purged.profilesDeleted,1);assert.deepEqual(await speakers.privacyStatus(),{ownerProfiles:0,encryptedVoiceprints:0,linkedUtterances:0,identifyingAuditReferences:0,rawAudioObjects:0});assert.equal((await speakers.recognize([1,0,0])).state,"unknown");assert.equal((await storage.listVoiceUtterances("purge-conversation","owner"))[0].speakerLabel,"unknown");});

test("replaying one enrollment attempt returns exactly one profile and one voiceprint",async()=>{const {storage,speakers}=await setup();const input={displayName:"Owner",relation:"owner",consent:true,consentActor:"Owner",sampleRepresentations:samples([1,0,0]),enrollmentAttemptId:"11111111-1111-4111-8111-111111111111"};const first=await speakers.enroll(input);const replay=await speakers.enroll(input);assert.equal(replay.id,first.id);assert.equal((await speakers.list()).length,1);assert.equal((await storage.listSpeakerProfiles("owner",{includeRepresentation:true})).filter((item)=>item.representation).length,1);assert.equal((await storage.listActivity("owner",{limit:20})).filter((item)=>item.action==="speaker_enrolled").length,1);});

test("anonymous familiarity requires consent, creates once, then recognizes the recurring voice",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",familiarityThreshold:.8,familiarityAmbiguityMargin:.05,embeddingKey:"a-preview-encryption-key-with-at-least-32-bytes",requireEncryption:true});assert.equal((await speakers.rememberAnonymous({representation:[1,0,0],representationVersion:"ecapa",consent:false})).state,"consent_required");assert.equal((await speakers.listAnonymous()).length,0);const first=await speakers.rememberAnonymous({representation:[1,0,0],representationVersion:"ecapa",consent:true,consentActor:"Guest",selfReportedName:"Ahmad"});assert.equal(first.state,"first_time_unknown");assert.equal(first.selfReportedName,"Ahmad");const recurring=await speakers.rememberAnonymous({representation:[.99,.01,0],representationVersion:"ecapa",consent:true,consentActor:"Guest"});assert.equal(recurring.state,"known_anonymous");assert.equal(recurring.anonymousSpeakerId,first.anonymousSpeakerId);assert.equal((await speakers.listAnonymous())[0].encounterCount,2);const stored=(await storage.listAnonymousSpeakerProfiles("owner",{includeRepresentation:true}))[0];assert.equal(stored.representation.algorithm,"aes-256-gcm");assert.equal(JSON.stringify(stored.representation).includes("[1,0,0]"),false);assert.equal("audio" in stored,false);});

test("anonymous matching uses a separate conservative threshold and never forces a weak match",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",familiarityThreshold:.8,familiarityAmbiguityMargin:.05});const first=await speakers.rememberAnonymous({representation:[1,0,0],representationVersion:"ecapa",consent:true,consentActor:"One"});const next=await speakers.rememberAnonymous({representation:[.7,Math.sqrt(1-.7**2),0],representationVersion:"ecapa",consent:true,consentActor:"Two"});assert.equal(next.state,"first_time_unknown");assert.notEqual(next.anonymousSpeakerId,first.anonymousSpeakerId);});

test("close anonymous candidates remain uncertain without updating or creating a profile",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",familiarityThreshold:.8,familiarityAmbiguityMargin:.08});await speakers.rememberAnonymous({representation:[1,0,0],representationVersion:"ecapa",consent:true,consentActor:"One"});await speakers.rememberAnonymous({representation:[.5,.866,0],representationVersion:"ecapa",consent:true,consentActor:"Two"});const before=await speakers.listAnonymous();const result=await speakers.rememberAnonymous({representation:[.866,.5,0],representationVersion:"ecapa",consent:true,consentActor:"Three"});assert.equal(result.state,"uncertain");assert.equal(result.anonymousSpeakerId,null);assert.equal((await speakers.listAnonymous()).length,before.length);});

test("forgetting an anonymous speaker destroys its derived representation and prevents reuse",async()=>{const storage=createInMemoryStorage();await storage.initialize({owner:{id:"owner",fullName:"Owner"}});const speakers=createSpeakerIdentity({storage,ownerId:"owner",familiarityThreshold:.8});const created=await speakers.rememberAnonymous({representation:[1,0,0],representationVersion:"ecapa",consent:true,consentActor:"Guest"});assert.equal(await speakers.isActiveAnonymous(created.anonymousSpeakerId),true);assert.equal(await speakers.deleteAnonymous(created.anonymousSpeakerId),true);assert.equal(await speakers.isActiveAnonymous(created.anonymousSpeakerId),false);assert.deepEqual(await speakers.listAnonymous(),[]);const stored=[...storage.__debug?.anonymousSpeakerProfiles||[]];assert.equal(stored.length,0);const actions=(await storage.listActivity("owner",{limit:20})).map(({action})=>action);assert.ok(actions.includes("anonymous_speaker_deleted"));});
