import test from "node:test";
import assert from "node:assert/strict";
import { createSpeakerEngineCoordinator, createSpeakerEngineResult, speakerFromAuthoritativeResult, SPEAKER_ENGINE_EVIDENCE } from "../src/voice/speaker-engine.js";
import { createEagleShadowEngine } from "../src/voice/eagle-speaker-engine.js";
import { createSpeakerAssertions } from "../src/voice/speaker-assertion.js";

const engine=(id,result,{authoritative=false,fail=false}={})=>({id,version:`${id}-v1`,authoritative,configured:true,async readiness(){return{available:true};},async recognize(){if(fail)throw Object.assign(new Error("secret raw audio YXVkaW8="),{code:"failed"});return createSpeakerEngineResult({engineId:id,engineVersion:`${id}-v1`,...result});}});

test("ECAPA remains the authoritative engine by default and browser input cannot choose an engine",async()=>{const ecapa=engine("ecapa",{status:"confirmed",candidateProfileId:"owner",category:"owner",confidence:.5},{authoritative:true});const eagle=engine("eagle",{status:"unknown",confidence:.1});const coordinator=createSpeakerEngineCoordinator({authoritativeEngine:ecapa,shadowEngines:[eagle],logger:{info(){}}});const report=await coordinator.recognize({speakerEngine:"eagle"},{requestId:"r"});assert.equal(coordinator.authoritativeEngineId,"ecapa");assert.equal(report.authoritative.engineId,"ecapa");assert.equal(speakerFromAuthoritativeResult(report.authoritative).authenticated_identity,"owner");});

test("shadow owner result and disagreement cannot authenticate or override authoritative unknown",async()=>{const report=await createSpeakerEngineCoordinator({authoritativeEngine:engine("ecapa",{status:"unknown",confidence:.2},{authoritative:true}),shadowEngines:[engine("eagle",{status:"confirmed",candidateProfileId:"owner",category:"owner",confidence:.99})],logger:{info(){}}}).recognize({},{});const speaker=speakerFromAuthoritativeResult(report.authoritative);assert.equal(speaker.authenticated_identity,"none");assert.equal(report.comparison[0].agreement,"disagree");});

test("signed assertions contain only authoritative identity",async()=>{const report=await createSpeakerEngineCoordinator({authoritativeEngine:engine("ecapa",{status:"unknown",confidence:.2},{authoritative:true}),shadowEngines:[engine("eagle",{status:"confirmed",candidateProfileId:"shadow-owner",category:"owner",confidence:.99})],logger:{info(){}}}).recognize({},{});const assertions=createSpeakerAssertions({key:"speaker-engine-test-assertion-key-with-32-bytes"});const verified=assertions.verify(assertions.issue(speakerFromAuthoritativeResult(report.authoritative)));assert.equal(verified.authenticated_identity,"none");assert.equal(verified.speaker_profile_id,null);assert.equal(JSON.stringify(verified).includes("shadow-owner"),false);});

test("shadow failure is isolated while authoritative failure fails closed",async()=>{const healthy=await createSpeakerEngineCoordinator({authoritativeEngine:engine("ecapa",{status:"confirmed",candidateProfileId:"owner",category:"owner",confidence:.5},{authoritative:true}),shadowEngines:[engine("eagle",{}, {fail:true})],logger:{info(){}}}).recognize({},{});assert.equal(speakerFromAuthoritativeResult(healthy.authoritative).authenticated_identity,"owner");assert.equal(healthy.shadow[0].status,"failure");const failed=await createSpeakerEngineCoordinator({authoritativeEngine:engine("ecapa",{}, {authoritative:true,fail:true}),logger:{info(){}}}).recognize({},{});assert.equal(speakerFromAuthoritativeResult(failed.authoritative).authenticated_identity,"none");});

test("comparison telemetry and serialized contracts exclude audio and biometric evidence",async()=>{const logs=[];const result=createSpeakerEngineResult({engineId:"ecapa",engineVersion:"v1",status:"unknown",representationId:"vad_v3",diagnostics:{voicedDurationSeconds:2,embedding:[1,2],audioBase64:"YXVkaW8="},evidence:{representation:[1,2],audioBase64:"YXVkaW8="}});const coordinator=createSpeakerEngineCoordinator({authoritativeEngine:{...engine("ecapa",result,{authoritative:true}),async recognize(){return result;}},logger:{info(...args){logs.push(args);}}});const report=await coordinator.recognize({audioBase64:"YXVkaW8="},{});assert.equal(report.authoritative[SPEAKER_ENGINE_EVIDENCE].representation.length,2);assert.equal(report.authoritative.representationId,"vad_v3");assert.doesNotMatch(JSON.stringify({report,logs}),/YXVkaW8|embedding|\[1,2\]/);});

test("Eagle adapter is disabled without key runtime and independent profiles",async()=>{const eagle=createEagleShadowEngine();assert.equal(eagle.authoritative,false);assert.equal((await eagle.readiness()).status,"Disabled");assert.equal((await eagle.recognize()).error.code,"not_configured");});
