import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {authorizeWorkerAdmin,createTaskMigrationService} from "../src/autonomy/task-migration.js";

const OWNER="owner",BRANCH="feat/nova-brain-mvp-foundation",OLD="a".repeat(40),TARGET="b".repeat(40),ID="f72ee91d-4e06-4824-a395-0ef376f3e96a";
const request=(overrides={})=>({taskId:ID,migrationType:"repair_worker_runtime_v1_continuation",expectedBranch:BRANCH,expectedCommit:OLD,targetCommit:TARGET,runtimeMinutes:90,planVersion:"worker-runtime-v1-live-continuation",...overrides});
async function fixture(){const storage=createInMemoryStorage({clock:()=>new Date("2026-09-06T00:00:00Z")});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});await storage.createAutonomyTask({id:ID,ownerId:OWNER,projectId:"nova-brain",title:"Acceptance",objective:"Validate handoff",branch:BRANCH,startingCommit:OLD,maxSteps:5,maxRuntimeMinutes:10,metadata:{steps:[{type:"inspect_repo"}],claimKey:"preserved"}});await storage.updateAutonomyTask(ID,OWNER,{status:"waiting_for_worker",currentStep:1,currentPhase:"inspect_repo",checkpoint:{completedSteps:["1:inspect_repo"],findings:[],latestResult:{ok:true}},metadata:{steps:[{type:"inspect_repo"}],claimKey:"preserved",idempotencyHistory:["one"]}});await storage.recordAutonomyStep({taskId:ID,stepId:"1:inspect_repo",stepType:"inspect_repo",capability:"repo_read_remote",operationFingerprint:"inspect",status:"completed",result:{ok:true}});await storage.appendActivity({ownerId:OWNER,projectId:"nova-brain",runId:ID,action:"existing_history",status:"completed",summary:"Preserved history."});return{storage,service:createTaskMigrationService({storage,ownerId:OWNER,approvedBranch:BRANCH,clock:()=>new Date("2026-09-06T00:00:00Z")})};}

test("scoped administrator authentication is constant-time and fail closed",()=>{assert.deepEqual(authorizeWorkerAdmin({headers:{authorization:"Bearer scoped"}},"scoped"),{actorType:"scoped_server_admin"});for(const [token,code] of [[undefined,"migration_not_allowed"],["expected","unauthorized"]])assert.throws(()=>authorizeWorkerAdmin({headers:{authorization:"Bearer wrong"}},token),error=>error.code===code);});

test("authorized inspect is bounded and does not expose plan, secrets, or lease token",async()=>{const f=await fixture();const task=await f.service.inspect(ID);assert.equal(task.id,ID);assert.deepEqual(task.metadata,{planVersion:null,requiredCapability:null,stepCount:1});assert.equal(task.leaseToken,null);assert.doesNotMatch(JSON.stringify(task),/claimKey|idempotencyHistory|DATABASE_URL/);await assert.rejects(()=>f.service.inspect("missing"),error=>error.code==="task_not_found");});

test("allowlisted migration preserves identity checkpoint history and idempotency metadata",async()=>{const f=await fixture();const before=await f.storage.getAutonomyTask(ID,OWNER),beforeActivity=await f.storage.listActivity(OWNER,{runId:ID});const result=await f.service.migrate(request());assert.equal(result.idempotent,false);const task=await f.storage.getAutonomyTask(ID,OWNER);assert.equal(task.id,ID);assert.equal(task.ownerId,OWNER);assert.equal(task.projectId,"nova-brain");assert.equal(task.currentCommit,TARGET);assert.equal(task.startingCommit,TARGET);assert.equal(task.maxRuntimeMinutes,90);assert.equal(task.status,"queued");assert.equal(task.stateVersion,before.stateVersion+1);assert.deepEqual(task.checkpoint.completedSteps,["1:inspect_repo"]);assert.equal(task.metadata.claimKey,"preserved");assert.deepEqual(task.metadata.idempotencyHistory,["one"]);assert.equal(task.metadata.steps[1].input.arguments.files.length,1);assert.ok(task.metadata.steps[1].input.arguments.files[0].content.length>0);assert.equal((await f.storage.listAutonomySteps(ID)).length,1);const activity=await f.storage.listActivity(OWNER,{runId:ID});assert.equal(activity.length,beforeActivity.length+1);assert.equal(activity[0].action,"autonomy_task_migrated");assert.equal(activity[0].metadata.actorType,"scoped_server_admin");assert.equal(activity[0].metadata.expectedVersion,before.stateVersion);assert.equal(activity[0].metadata.newVersion,task.stateVersion);assert.doesNotMatch(JSON.stringify(activity[0]),/password|token|secret/i);});

test("duplicate migration is idempotent and writes no duplicate audit",async()=>{const f=await fixture();await f.service.migrate(request());const count=(await f.storage.listActivity(OWNER,{runId:ID})).length;const replay=await f.service.migrate(request());assert.equal(replay.idempotent,true);assert.equal((await f.storage.listActivity(OWNER,{runId:ID})).length,count);});

test("bounded handoff protocol failure resumes at the existing next step",async()=>{const f=await fixture();await f.storage.updateAutonomyTask(ID,OWNER,{status:"failed",currentStep:3,errorCode:"invalid_handoff_result",metadata:{steps:[{type:"inspect_repo"}],migrationPlanVersion:"worker-runtime-v1-live-continuation"},checkpoint:{completedSteps:["1:inspect_repo","2:apply_patch","3:run_focused_tests"]}});const result=await f.service.migrate(request({targetCommit:OLD}));assert.equal(result.idempotent,false);const task=await f.storage.getAutonomyTask(ID,OWNER);assert.equal(task.status,"queued");assert.equal(task.currentStep,3);assert.equal(task.metadata.requiredCapability,"test_local");assert.deepEqual(task.checkpoint.completedSteps,["1:inspect_repo","2:apply_patch","3:run_focused_tests"]);});

test("failed full-suite handoff can retry only with its exact completed checkpoint chain",async()=>{const f=await fixture();await f.storage.updateAutonomyTask(ID,OWNER,{status:"failed",currentStep:3,errorCode:"test_failed",metadata:{steps:[{type:"inspect_repo"},{type:"apply_patch"},{type:"run_focused_tests"},{type:"run_full_tests"}]},checkpoint:{completedSteps:["1:inspect_repo","2:apply_patch","3:run_focused_tests"]}});const result=await f.service.migrate(request());assert.equal(result.idempotent,false);assert.equal(result.task.status,"queued");assert.equal(result.task.currentStep,3);});

test("failed tests outside the exact full-suite continuation cannot use handoff recovery",async()=>{for(const changes of [{errorCode:"test_failed"},{currentStep:2,errorCode:"test_failed",metadata:{steps:[{type:"inspect_repo"},{type:"apply_patch"},{type:"run_focused_tests"}]},checkpoint:{completedSteps:["1:inspect_repo","2:apply_patch"]}},{currentStep:3,errorCode:"test_failed",metadata:{steps:[{type:"inspect_repo"},{type:"apply_patch"},{type:"run_focused_tests"},{type:"run_full_tests"}]},checkpoint:{completedSteps:["1:inspect_repo"]}}]){const f=await fixture();await f.storage.updateAutonomyTask(ID,OWNER,{status:"failed",...changes});await assert.rejects(()=>f.service.migrate(request()),error=>error.code==="task_state_mismatch");}});

test("branch commit lease state and completed-step preconditions fail closed",async()=>{for(const [prepare,input,code] of [[null,request({expectedBranch:"main"}),"production_target_forbidden"],[null,request({expectedBranch:"other"}),"production_target_forbidden"],[null,request({expectedCommit:"c".repeat(40)}),"commit_binding_mismatch"],[async f=>f.storage.updateAutonomyTask(ID,OWNER,{status:"running"}),request(),"task_state_mismatch"],[async f=>f.storage.updateAutonomyTask(ID,OWNER,{leaseToken:"lease",leaseExpiresAt:"2026-09-06T00:01:00Z"}),request(),"active_lease_conflict"],[async f=>f.storage.updateAutonomyTask(ID,OWNER,{checkpoint:{completedSteps:[]}}),request(),"invalid_migration_plan"]]){const f=await fixture();if(prepare)await prepare(f);await assert.rejects(()=>f.service.migrate(input),error=>error.code===code);}});

test("runtime and schema are bounded and arbitrary mutation is rejected",async()=>{for(const input of [request({runtimeMinutes:14}),request({runtimeMinutes:121}),request({migrationType:"sql"}),request({planVersion:"arbitrary"}),request({rawSql:"DROP TABLE"})]){const f=await fixture();await assert.rejects(()=>f.service.migrate(input),error=>["invalid_migration_plan","migration_not_allowed"].includes(error.code));assert.equal((await f.storage.getAutonomyTask(ID,OWNER)).currentCommit,OLD);}});

test("optimistic conflict rolls back without audit or partial task mutation",async()=>{const f=await fixture(),count=(await f.storage.listActivity(OWNER,{runId:ID})).length,conflicted=Object.freeze({...f.storage,migrateAutonomyTask:async()=>null}),service=createTaskMigrationService({storage:conflicted,ownerId:OWNER,approvedBranch:BRANCH});await assert.rejects(()=>service.migrate(request()),error=>error.code==="task_state_mismatch");assert.equal((await f.storage.getAutonomyTask(ID,OWNER)).currentCommit,OLD);assert.equal((await f.storage.listActivity(OWNER,{runId:ID})).length,count);});

test("timestamp precision differences do not cause a false migration conflict",async()=>{const f=await fixture(),task=await f.storage.getAutonomyTask(ID,OWNER);const migrated=await f.storage.migrateAutonomyTask({taskId:ID,ownerId:OWNER,expectedVersion:task.stateVersion,expectedUpdatedAt:"2026-09-06T00:00:00.123456Z",expectedBranch:BRANCH,expectedCommit:OLD,targetCommit:TARGET,runtimeMinutes:90,plan:[{type:"inspect_repo"},{type:"apply_patch"}],planVersion:"worker-runtime-v1-live-continuation",actorType:"scoped_server_admin",oldRuntimeMinutes:10,oldPlanVersion:null});assert.equal(migrated.currentCommit,TARGET);assert.equal(migrated.stateVersion,task.stateVersion+1);});

test("a concurrent mutation after migration read is rejected by task version",async()=>{const f=await fixture(),count=(await f.storage.listActivity(OWNER,{runId:ID})).length;let raced=false;const concurrent=Object.freeze({...f.storage,migrateAutonomyTask:async input=>{if(!raced){raced=true;await f.storage.updateAutonomyTask(ID,OWNER,{resultSummary:"concurrent mutation"});}return f.storage.migrateAutonomyTask(input);}}),service=createTaskMigrationService({storage:concurrent,ownerId:OWNER,approvedBranch:BRANCH});await assert.rejects(()=>service.migrate(request()),error=>error.code==="version_conflict");const task=await f.storage.getAutonomyTask(ID,OWNER);assert.equal(task.currentCommit,OLD);assert.equal(task.resultSummary,"concurrent mutation");assert.equal((await f.storage.listActivity(OWNER,{runId:ID})).length,count);});

test("all in-memory Worker task mutations monotonically advance state version",async()=>{let now=Date.parse("2026-09-06T00:00:00Z");const storage=createInMemoryStorage({clock:()=>new Date(now)});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova-brain",name:"Nova"}]});let task=await storage.createAutonomyTask({ownerId:OWNER,title:"Version",objective:"Version",branch:BRANCH,startingCommit:OLD,metadata:{requiredCapability:"repo_read_remote"}});assert.equal(task.stateVersion,1);task=await storage.updateAutonomyTask(task.id,OWNER,{status:"queued"});assert.equal(task.stateVersion,2);task=await storage.claimAutonomyTask({ownerId:OWNER,workerId:"worker",capabilities:["repo_read_remote"],leaseMs:1000,idempotencyKey:"claim"});assert.equal(task.stateVersion,3);assert.equal(await storage.releaseAutonomyLease(task.id,OWNER,task.leaseToken),true);assert.equal((await storage.getAutonomyTask(task.id,OWNER)).stateVersion,4);now+=2000;});

test("repaired plan preserves inspection and ends local continuation at exact push approval",async()=>{const f=await fixture();await f.service.migrate(request());const task=await f.storage.getAutonomyTask(ID,OWNER),types=task.metadata.steps.map(step=>step.type);assert.deepEqual(types,["inspect_repo","apply_patch","run_focused_tests","run_full_tests","inspect_diff","commit","push","deploy_preview","wait","verify_preview","summarize"]);assert.equal(task.metadata.steps[6].input.arguments.commitSha,"$CURRENT_COMMIT");assert.equal(task.metadata.steps[6].input.arguments.branch,BRANCH);assert.equal(task.metadata.steps[7].input.arguments.branch,BRANCH);});
