import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createWorkerRuntime} from "../src/autonomy/worker-runtime.js";

const OWNER="owner",BRANCH="feat/nova-brain-mvp-foundation",SHA="a".repeat(40);
const plan=(type="inspect_repo",input={tool:"repo_list",arguments:{path:"src"}})=>({type,input});
async function fixture({capabilities=["repo_read_remote","repo_mutate_local"],execute,wrap}={}){let now=new Date("2026-01-01T00:00:00Z");const base=createInMemoryStorage({clock:()=>new Date(now)});await base.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova",name:"Nova"}]});const storage=wrap?wrap(base):base,calls=[];const runtime=createWorkerRuntime({storage,ownerId:OWNER,clock:()=>new Date(now),workerId:"bound-worker",capabilities,leaseMs:1000,toolRegistry:{async execute(name,input,context){calls.push({name,input,context});return execute?execute(name,input,context):{ok:true,name};}}});const create=(steps=[plan()],extra={})=>runtime.create({title:"Bound task",objective:"Bound execution",projectId:"nova",branch:BRANCH,startingCommit:SHA,metadata:{steps},...extra});return{base,storage,runtime,calls,create,advance(ms){now=new Date(now.getTime()+ms);}};}
const rejects=(promise,code)=>assert.rejects(promise,error=>error.code===code);

test("requested eligible task advances",async()=>{const f=await fixture(),task=await f.create();const result=await f.runtime.tickTask(task.id,{idempotencyKey:"exact-1"});assert.equal(result.claimed,true);assert.equal((await f.runtime.get(task.id)).currentStep,1);});
test("another queued eligible task is not touched",async()=>{const f=await fixture(),requested=await f.create(),other=await f.create();await f.runtime.tickTask(requested.id);assert.equal((await f.runtime.get(other.id)).currentStep,0);assert.equal((await f.runtime.get(other.id)).status,"queued");});
test("missing requested task fails closed",async()=>{const f=await fixture();await rejects(f.runtime.tickTask("missing"),"task_not_found");});
test("ineligible requested task fails closed",async()=>{const f=await fixture(),task=await f.create();await f.runtime.control(task.id,"pause");await rejects(f.runtime.tickTask(task.id),"task_not_eligible");});
test("requested task waiting for approval fails closed",async()=>{const f=await fixture(),task=await f.create();await f.base.updateAutonomyTask(task.id,OWNER,{status:"waiting_for_approval"});await rejects(f.runtime.tickTask(task.id),"approval_required");});
test("requested task with incompatible capability fails closed",async()=>{const f=await fixture({capabilities:["repo_read_remote"]}),task=await f.create([plan("apply_patch",{tool:"repo_apply_patch",arguments:{branch:BRANCH,files:[]}})]);await rejects(f.runtime.tickTask(task.id),"capability_mismatch");assert.equal(f.calls.length,0);});
test("active incompatible lease fails closed",async()=>{const f=await fixture(),task=await f.create();await f.base.updateAutonomyTask(task.id,OWNER,{leaseOwner:"other",leaseToken:"lease",leaseExpiresAt:"2099-01-01T00:00:00Z"});await rejects(f.runtime.tickTask(task.id),"task_lease_conflict");});
test("state version conflict fails safely",async()=>{let base;const f=await fixture({wrap:store=>{base=store;return Object.freeze({...store,claimAutonomyTask:async input=>{await base.updateAutonomyTask(input.taskId,input.ownerId,{resultSummary:"concurrent"});return null;}});}}),task=await f.create();await rejects(f.runtime.tickTask(task.id),"version_conflict");assert.equal((await f.base.getAutonomyTask(task.id,OWNER)).currentStep,0);});
test("no fallback to another task occurs",async()=>{const f=await fixture(),requested=await f.create(),other=await f.create();await f.runtime.control(requested.id,"pause");await rejects(f.runtime.tickTask(requested.id),"task_not_eligible");assert.equal((await f.runtime.get(other.id)).currentStep,0);});
test("repository branch lock behavior remains correct",async()=>{const f=await fixture(),task=await f.create([plan("apply_patch",{tool:"repo_apply_patch",arguments:{branch:BRANCH,files:[]}})]);assert.equal(await f.base.acquireAutonomyLock({lockKey:`nova:${BRANCH}`,taskId:"other",leaseToken:"other",expiresAt:"2099-01-01T00:00:00Z"}),true);const result=await f.runtime.tickTask(task.id);assert.equal(result.code,"branch_locked");assert.equal(f.calls.length,0);});
test("one bounded step per task tick remains enforced",async()=>{const f=await fixture(),task=await f.create([plan(),plan("read_files",{tool:"repo_read",arguments:{path:"README.md"}})]);await f.runtime.tickTask(task.id);assert.equal((await f.runtime.get(task.id)).currentStep,1);assert.equal(f.calls.length,1);});
test("Activity step events reference only the requested task",async()=>{const f=await fixture(),requested=await f.create(),other=await f.create();await f.runtime.tickTask(requested.id);const activity=await f.base.listActivity(OWNER,{limit:50}),steps=activity.filter(x=>x.action.startsWith("autonomy_step_"));assert.ok(steps.length>0);assert.ok(steps.every(x=>x.runId===requested.id));assert.equal(activity.some(x=>x.action.startsWith("autonomy_step_")&&x.runId===other.id),false);});
test("task-bound execution redacts secrets",async()=>{const f=await fixture({execute:()=>({ok:true,token:"never-return"})}),task=await f.create([plan("inspect_repo",{tool:"repo_list",arguments:{path:"src",apiToken:"never-log"}})]);const result=await f.runtime.tickTask(task.id);const activity=await f.base.listActivity(OWNER,{runId:task.id,limit:50});assert.doesNotMatch(JSON.stringify({result,activity,task:await f.runtime.get(task.id)}),/never-log|never-return/);});
test("existing queue-wide tick behavior remains unchanged",async()=>{const f=await fixture(),low=await f.create([plan()],{priority:1}),high=await f.create([plan()],{priority:10});await f.runtime.tick();assert.equal((await f.runtime.get(high.id)).currentStep,1);assert.equal((await f.runtime.get(low.id)).currentStep,0);});
test("main and Production execution remain forbidden",async()=>{const f=await fixture(),task=await f.create();await f.base.updateAutonomyTask(task.id,OWNER,{branch:"main",metadata:{steps:[plan("deploy_preview",{tool:"preview_deploy",arguments:{branch:"main",commitSha:SHA,target:"production"}})]}});await rejects(f.runtime.tickTask(task.id),"branch_not_allowed");assert.equal(f.calls.length,0);});

