import test from "node:test";
import assert from "node:assert/strict";
import { createVoiceMode } from "../assets/voice-mode.js";

function setup({sendTurn=async(text)=>({message:`Reply to ${text}`}),speakStarts=true}={}){const events=[];let completion;const mode=createVoiceMode({startRecognition:()=>events.push("listen"),stopRecognition:()=>events.push("stop-listen"),stopSpeech:()=>events.push("stop-speech"),sendTurn:async(text)=>{events.push(`send:${text}`);return sendTurn(text);},speakResponse:(text,options)=>{events.push(`speak:${text}`);completion=options;return speakStarts;},onState:({state})=>events.push(`state:${state}`),onError:(message)=>events.push(`error:${message}`)});return{mode,events,complete:()=>completion.onComplete(),speechError:()=>completion.onError()};}

test("Start Voice enters listening and a final transcript auto-sends exactly once",async()=>{const flow=setup();flow.mode.start();assert.equal(flow.mode.getState(),"listening");assert.equal(await flow.mode.acceptFinal("Hello"),true);assert.equal(await flow.mode.acceptFinal("Hello"),false);assert.equal(flow.events.filter((item)=>item==="send:Hello").length,1);assert.equal(flow.mode.getState(),"speaking");});
test("empty or interim-only transcript does not send",async()=>{const flow=setup();flow.mode.start();assert.equal(await flow.mode.acceptFinal(" "),false);assert.equal(flow.events.some((item)=>item.startsWith("send:")),false);});
test("Nova response speaks then completion automatically listens again",async()=>{const flow=setup();flow.mode.start();await flow.mode.acceptFinal("Next");flow.complete();assert.equal(flow.mode.getState(),"listening");assert.equal(flow.events.filter((item)=>item==="listen").length,2);});
test("End Voice stops recognition and speech and prevents automatic restart",async()=>{const flow=setup();flow.mode.start();await flow.mode.acceptFinal("Stop after this");flow.mode.end();const listens=flow.events.filter((item)=>item==="listen").length;flow.complete();assert.equal(flow.mode.isActive(),false);assert.equal(flow.events.filter((item)=>item==="listen").length,listens);assert.deepEqual(flow.events.slice(-3,-1),["stop-listen","stop-speech"]);});
test("explicit interruption stops speech before listening",async()=>{const flow=setup();flow.mode.start();await flow.mode.acceptFinal("Long reply");const before=flow.events.length;assert.equal(flow.mode.interrupt(),true);assert.deepEqual(flow.events.slice(before,before+4),["stop-speech","stop-listen","stop-speech","state:listening"]);assert.equal(flow.events.at(-1),"listen");});
test("failed reply speech enters a visible error state without background listening",async()=>{const flow=setup({speakStarts:false});flow.mode.start();assert.equal(await flow.mode.acceptFinal("Hello"),false);assert.equal(flow.mode.getState(),"error");assert.equal(flow.events.filter((item)=>item==="listen").length,1);});
test("recognition ending without speech restarts while active but not after End Voice",()=>{const flow=setup();flow.mode.start();flow.mode.recognitionEnded({hadFinal:false});assert.equal(flow.events.filter((item)=>item==="listen").length,2);flow.mode.end();flow.mode.recognitionEnded({hadFinal:false});assert.equal(flow.events.filter((item)=>item==="listen").length,2);});
