import test from "node:test";
import assert from "node:assert/strict";
import { createVoiceMode } from "../assets/voice-mode.js";
import { createVoiceOutput } from "../assets/voice-output.js";

function setup({sendTurn=async(text)=>({message:`Reply to ${text}`}),speakStarts=true}={}){
  const events=[];const timers=[];let completion;
  const mode=createVoiceMode({
    startRecognition:()=>events.push("listen"),stopRecognition:()=>events.push("stop-listen"),stopSpeech:()=>events.push("stop-speech"),
    sendTurn:async(text)=>{events.push(`send:${text}`);return sendTurn(text);},
    speakResponse:(text,options)=>{events.push(`speak:${text}`);completion=options;return speakStarts;},
    onState:({state,delay})=>events.push(`state:${state}${delay?`:${delay}`:""}`),onError:(message)=>events.push(`error:${message}`),onNotice:(message)=>events.push(`notice:${message}`),
    schedule:(callback,delay)=>{const timer={callback,delay,cancelled:false};timers.push(timer);return timer;},cancelSchedule:(timer)=>{timer.cancelled=true;}
  });
  return{mode,events,timers,complete:()=>completion.onComplete(),speechError:()=>completion.onError(),runTimer:(index=timers.length-1)=>{const timer=timers[index];if(!timer.cancelled)timer.callback();}};
}

test("Start Voice enters listening and a final transcript auto-sends exactly once",async()=>{const flow=setup();flow.mode.start();assert.equal(flow.mode.getState(),"listening");assert.equal(await flow.mode.acceptFinal("Hello"),true);assert.equal(await flow.mode.acceptFinal("Hello"),false);assert.equal(flow.events.filter((item)=>item==="send:Hello").length,1);assert.equal(flow.mode.getState(),"speaking");});
test("empty or interim-only transcript does not send",async()=>{const flow=setup();flow.mode.start();assert.equal(await flow.mode.acceptFinal(" "),false);assert.equal(flow.events.some((item)=>item.startsWith("send:")),false);});
test("Nova response speaks then completion automatically listens again",async()=>{const flow=setup();flow.mode.start();await flow.mode.acceptFinal("Next");flow.complete();assert.equal(flow.mode.getState(),"listening");assert.equal(flow.events.filter((item)=>item==="listen").length,2);});
test("End Voice stops recognition and speech and prevents automatic restart",async()=>{const flow=setup();flow.mode.start();await flow.mode.acceptFinal("Stop after this");flow.mode.end();const listens=flow.events.filter((item)=>item==="listen").length;flow.complete();assert.equal(flow.mode.isActive(),false);assert.equal(flow.events.filter((item)=>item==="listen").length,listens);assert.deepEqual(flow.events.slice(-3,-1),["stop-listen","stop-speech"]);});
test("explicit interruption stops speech before listening",async()=>{const flow=setup();flow.mode.start();await flow.mode.acceptFinal("Long reply");const before=flow.events.length;assert.equal(flow.mode.interrupt(),true);assert.deepEqual(flow.events.slice(before,before+4),["stop-speech","stop-listen","stop-speech","state:listening"]);assert.equal(flow.events.at(-1),"listen");});
test("failed reply speech enters a visible error state without background listening",async()=>{const flow=setup({speakStarts:false});flow.mode.start();assert.equal(await flow.mode.acceptFinal("Hello"),false);assert.equal(flow.mode.getState(),"error");assert.equal(flow.events.filter((item)=>item==="listen").length,1);});
test("no-speech keeps Voice Mode active and safely restarts after a delay",()=>{const flow=setup();flow.mode.start();assert.equal(flow.mode.recognitionError({code:"no-speech",recoverable:true}),true);assert.equal(flow.mode.isActive(),true);assert.equal(flow.mode.getState(),"retrying");assert.equal(flow.timers[0].delay,700);assert.equal(flow.events.some((item)=>item.startsWith("error:")),false);flow.runTimer(0);assert.equal(flow.mode.getState(),"listening");assert.equal(flow.events.filter((item)=>item==="listen").length,2);});
test("recognition end without an error uses the same safe silence retry",()=>{const flow=setup();flow.mode.start();flow.mode.recognitionEnded({hadFinal:false});assert.equal(flow.mode.getState(),"retrying");flow.runTimer();assert.equal(flow.events.filter((item)=>item==="listen").length,2);});
test("End Voice cancels pending no-speech retry",()=>{const flow=setup();flow.mode.start();flow.mode.recognitionError({code:"no-speech"});const timer=flow.timers[0];flow.mode.end();assert.equal(timer.cancelled,true);flow.runTimer(0);assert.equal(flow.events.filter((item)=>item==="listen").length,1);assert.equal(flow.mode.isActive(),false);});
test("repeated no-speech retries use bounded backoff",()=>{const flow=setup();flow.mode.start();const delays=[];for(let index=0;index<6;index+=1){flow.mode.recognitionError({code:"no-speech"});delays.push(flow.timers.at(-1).delay);flow.runTimer();}assert.deepEqual(delays,[700,1200,2000,3000,3000,3000]);assert.equal(flow.mode.isActive(),true);});
test("aborted recognition is recoverable while permission and audio errors are fatal",()=>{const aborted=setup();aborted.mode.start();assert.equal(aborted.mode.recognitionError({code:"aborted"}),true);assert.equal(aborted.mode.isActive(),true);for(const error of [{code:"not-allowed",message:"Microphone permission was denied."},{code:"audio-capture",message:"No working microphone was found."}]){const flow=setup();flow.mode.start();assert.equal(flow.mode.recognitionError(error),false);assert.equal(flow.mode.isActive(),false);assert.equal(flow.mode.getState(),"error");assert.match(flow.events.at(-1),/error:/);}});
test("Voice Mode restarts listening only after the final TTS chunk",async()=>{const spoken=[];const queued=[];const listens=[];class Utterance{constructor(text){this.text=text;}}const synthesis={paused:false,cancel(){},getVoices:()=>[{name:"GB",lang:"en-GB",default:true}],speak:(utterance)=>spoken.push(utterance),addEventListener(){}};const output=createVoiceOutput({synthesis,Utterance,schedule:(callback,delay)=>queued.push({callback,delay}),startDelay:0,chunkDelay:35});const mode=createVoiceMode({startRecognition:()=>listens.push("listen"),stopRecognition(){},stopSpeech:()=>output.stop(),sendTurn:async()=>({message:"First sentence. Second sentence."}),speakResponse:(text,options)=>output.speak(text,options)});mode.start();await mode.acceptFinal("Tell me two things");queued.shift().callback();spoken[0].onstart();spoken[0].onend();assert.equal(listens.length,1);queued.shift().callback();spoken[1].onstart();spoken[1].onend();assert.equal(listens.length,2);assert.equal(mode.getState(),"listening");});
