import test from "node:test";
import assert from "node:assert/strict";
import { createVoiceOutput, detectSpeechLocale, MAX_SPEECH_CHARACTERS, sanitiseSpeechText, selectSpeechVoice, speechChunks } from "../assets/voice-output.js";

function localState(initial={}) { const values=new Map(Object.entries(initial)); return {getItem:(key)=>values.get(key)??null,setItem:(key,value)=>values.set(key,value),value:(key)=>values.get(key)}; }
function speechEnvironment(voices=[{name:"British",voiceURI:"gb",lang:"en-GB",default:true}]) {
  const spoken=[];let cancellations=0;let listener;
  class Utterance { constructor(text){this.text=text;} }
  const synthesis={getVoices:()=>voices,speak:(utterance)=>spoken.push(utterance),cancel:()=>{cancellations+=1;},addEventListener:(name,fn)=>{if(name==="voiceschanged")listener=fn;}};
  return {synthesis,Utterance,spoken,get cancellations(){return cancellations;},voicesChanged:()=>listener?.()};
}

test("voice output is optional and unsupported browsers remain safe",()=>{const output=createVoiceOutput();assert.equal(output.supported,false);assert.equal(output.speak("Hello"),false);assert.doesNotThrow(()=>output.stop());});
test("speaking one response publishes active and completed states",()=>{const env=speechEnvironment();const states=[];const output=createVoiceOutput({...env,onState:(state)=>states.push(state)});assert.equal(output.speak("Hello Nova.",{id:"one"}),true);assert.equal(output.activeId(),"one");env.spoken[0].onend();assert.equal(output.isSpeaking(),false);assert.deepEqual(states.map(({speaking})=>speaking),[true,false]);});
test("stop and second Speak cancel the complete previous queue",()=>{const env=speechEnvironment();const output=createVoiceOutput(env);output.speak("First sentence. Second sentence.",{id:"one"});output.speak("Replacement.",{id:"two"});assert.equal(output.activeId(),"two");const before=env.spoken.length;env.spoken[0].onend();assert.equal(env.spoken.length,before);output.stop();assert.equal(output.isSpeaking(),false);assert.ok(env.cancellations>=3);});
test("speech errors reset state and leave output reusable",()=>{const env=speechEnvironment();const states=[];const output=createVoiceOutput({...env,onState:(state)=>states.push(state)});output.speak("One",{id:"one"});env.spoken[0].onerror();assert.equal(output.isSpeaking(),false);assert.equal(states.at(-1).error,true);assert.equal(output.speak("Two",{id:"two"}),true);});
test("Auto Speak defaults off and persists locally",()=>{const storage=localState();const output=createVoiceOutput({...speechEnvironment(),storage});assert.equal(output.getAutoSpeak(),false);output.setAutoSpeak(true);assert.equal(storage.value("nova.voice.autoSpeak"),"true");assert.equal(createVoiceOutput({...speechEnvironment(),storage}).getAutoSpeak(),true);});
test("preferred voice persists and disappearing choices fall back",()=>{const storage=localState();const voices=[{name:"Arabic",voiceURI:"ar",lang:"ar-SA"},{name:"English",voiceURI:"en",lang:"en-GB",default:true}];const output=createVoiceOutput({...speechEnvironment(voices),storage});output.setPreferredVoice("ar");assert.equal(output.getPreferredVoice(),"ar");assert.equal(selectSpeechVoice(voices,"en-GB","missing").voiceURI,"en");});
test("voice matching prefers exact British English then same-language fallback",()=>{const voices=[{name:"US",lang:"en-US"},{name:"GB",lang:"en-GB"},{name:"Arabic",lang:"ar-SA"}];assert.equal(selectSpeechVoice(voices,"en-GB").name,"GB");assert.equal(selectSpeechVoice(voices.filter((v)=>v.name!=="GB"),"en-GB").name,"US");});
test("Arabic and additional-language voices match BCP-47 prefixes",()=>{const voices=[{name:"French",lang:"fr-FR"},{name:"Arabic",lang:"ar-AE"}];assert.equal(selectSpeechVoice(voices,"ar-SA").name,"Arabic");assert.equal(selectSpeechVoice(voices,"fr-CA").name,"French");});
test("missing language falls back gracefully",()=>{const voices=[{name:"Default",lang:"en-US",default:true},{name:"Other",lang:"de-DE"}];assert.equal(selectSpeechVoice(voices,"ja-JP").name,"Default");assert.equal(selectSpeechVoice([],"ar"),null);});
test("dominant and mixed scripts choose a deterministic safe locale",()=>{assert.equal(detectSpeechLocale("Hello Nova and OpenAI"),"en-GB");assert.equal(detectSpeechLocale("مرحبا بك، هذا رد عربي موثوق من Nova API"),"ar");assert.equal(detectSpeechLocale("Bonjour et merci pour vous"),"fr");});
test("speech sanitisation removes Markdown, URLs, secrets, decoration, and large code blocks",()=>{const clean=sanitiseSpeechText("# Heading\n- **Bold** [site](https://example.com) https://long.example/path sk-do-not-speak\n```js\nsecret()\n```");assert.match(clean,/Heading/);assert.match(clean,/Bold site link/);assert.match(clean,/Code block omitted/);assert.match(clean,/sensitive value omitted/);assert.doesNotMatch(clean,/https|\*\*|secret\(\)|sk-do-not-speak|```/);});
test("long speech is bounded and chunked at readable boundaries",()=>{const source=("A readable sentence with several words. ").repeat(1000);const chunks=speechChunks(source);assert.ok(chunks.length<=80);assert.ok(chunks.every((chunk)=>chunk.length<=220));assert.ok(chunks.join(" ").length<=MAX_SPEECH_CHARACTERS+80);});
test("voice list refresh supports asynchronous voiceschanged",()=>{const env=speechEnvironment();let published=[];createVoiceOutput({...env,onVoices:(voices)=>{published=voices;}});env.voicesChanged();assert.equal(published[0].lang,"en-GB");});
