import test from "node:test";
import assert from "node:assert/strict";
import {createInMemoryStorage} from "../src/storage/in-memory-storage.js";
import {createWorkerRuntime,WorkerError,AUTONOMY_STATUSES} from "../src/autonomy/worker-runtime.js";
import {ApprovalRequiredError} from "../src/policy/action-policy.js";

const OWNER="owner",BRANCH="feat/nova-brain-mvp-foundation";
async function fixture({capabilities,execute,clockStart="2026-01-01T00:00:00.000Z"}={}){let instant=new Date(clockStart);const clock=()=>new Date(instant);const storage=createInMemoryStorage({clock});await storage.initialize({owner:{id:OWNER,fullName:"Owner"},projects:[{id:"nova",name:"Nova"}]});const calls=[];const toolRegistry={async execute(name,input,context){calls.push({name,input,context});return execute?execute(name,input,context,calls):{ok:true,name};}};const runtime=createWorkerRuntime({storage,ownerId:OWNER,toolRegistry,clock,workerId:"worker-a",capabilities:capabilities||["repo_read_remote","repo_mutate_local","test_local","github_write","vercel_preview","reasoning","scheduler"],leaseMs:1000});return{storage,runtime,calls,advance(ms){instant=new Date(instant.getTime()+ms);}};}
const task=(runtime,steps,extra={})=>runtime.create({title:"Repair Preview",objective:"Fix synthetic failure",taskType:"developer",projectId:"nova",branch:BRANCH,startingCommit:"a".repeat(40),metadata:{steps},...extra});
const step=(type,tool=undefined,args={})=>({type,input:{...(tool?{tool}:{}),arguments:args}});

test("task model creates queues lists and exposes every required status",async()=>{const f=await fixture();const created=await task(f.runtime,[step("inspect_repo","repo_list",{})],{priority:9,maxSteps:5,maxRetries:2,maxRuntimeMinutes:4});assert.equal(created.status,"queued");assert.equal(created.priority,9);assert.equal((await f.runtime.get(created.id)).objective,"Fix synthetic failure");assert.equal((await f.runtime.list({})).length,1);for(const status of["queued","planning","running","waiting","waiting_for_approval","retrying","blocked","completed","failed","cancelled","expired"])assert.ok(AUTONOMY_STATUSES.includes(status));await assert.rejects(()=>task(f.runtime,[],{branch:"main"}),e=>e.code==="branch_not_allowed");});

test("durable claim leases prevent duplicates and abandoned leases recover",async()=>{const f=await fixture();const created=await task(f.runtime,[step("inspect_repo")]);const first=await f.storage.claimAutonomyTask({ownerId:OWNER,workerId:"one",capabilities:["repo_read_remote"],leaseMs:1000,idempotencyKey:"one"});assert.equal(first.id,created.id);assert.equal(await f.storage.claimAutonomyTask({ownerId:OWNER,workerId:"two",capabilities:["repo_read_remote"],leaseMs:1000,idempotencyKey:"two"}),null);f.advance(1001);const recovered=await f.storage.claimAutonomyTask({ownerId:OWNER,workerId:"two",capabilities:["repo_read_remote"],leaseMs:1000,idempotencyKey:"two"});assert.equal(recovered.id,created.id);assert.equal(recovered.leaseOwner,"two");});

test("priority next_run scheduling pause resume and cancellation are durable",async()=>{const f=await fixture();const later=await task(f.runtime,[step("inspect_repo")],{priority:10,nextRunAt:"2026-01-01T00:01:00.000Z"});const now=await task(f.runtime,[step("inspect_repo")],{priority:1});assert.equal((await f.runtime.tick()).claimed,true);await f.runtime.tick();await f.runtime.control(later.id,"pause");assert.equal((await f.runtime.tick()).claimed,false);await f.runtime.control(later.id,"resume");assert.equal((await f.runtime.tick()).claimed,true);await f.runtime.control(later.id,"cancel");assert.equal((await f.runtime.get(later.id)).status,"cancelled");assert.equal((await f.runtime.get(now.id)).currentStep,1);});

test("step fingerprints make completed actions idempotent",async()=>{const f=await fixture();const created=await task(f.runtime,[step("inspect_repo","repo_list",{})]);await f.runtime.tick({idempotencyKey:"claim-1"});await f.storage.updateAutonomyTask(created.id,OWNER,{status:"queued",currentStep:0,nextRunAt:"2026-01-01T00:00:00.000Z"});const replay=await f.runtime.tick({idempotencyKey:"claim-2"});assert.equal(replay.idempotent,true);assert.equal(f.calls.length,1);assert.equal((await f.runtime.steps(created.id)).length,1);});

test("retryable failures back off and stop at max retries while non-retryable failures stop immediately",async()=>{let failures=0;const f=await fixture({execute(){failures++;const error=new WorkerError("network_error","temporary");throw error;}});const created=await task(f.runtime,[step("inspect_repo")],{maxRetries:1});let result=await f.runtime.tick();assert.equal(result.status,"retrying");f.advance(1000);result=await f.runtime.tick();assert.equal(result.status,"failed");assert.equal((await f.runtime.get(created.id)).retryCount,1);const g=await fixture({execute(){throw new WorkerError("invalid_patch","bad",{retryable:false});}});await task(g.runtime,[step("apply_patch")]);assert.equal((await g.runtime.tick()).status,"failed");assert.equal(g.calls.length,1);});

test("max steps and runtime budgets hard stop",async()=>{const f=await fixture();const max=await task(f.runtime,[step("inspect_repo"),step("read_files")],{maxSteps:1});await f.runtime.tick();assert.equal((await f.runtime.tick()).status,"failed");assert.equal((await f.runtime.get(max.id)).errorCode,"max_steps_reached");const g=await fixture();const expired=await task(g.runtime,[step("inspect_repo")],{maxRuntimeMinutes:1});await g.storage.updateAutonomyTask(expired.id,OWNER,{startedAt:"2025-12-31T23:58:00.000Z"});assert.equal((await g.runtime.tick()).status,"expired");});

test("approval pauses once resumes exact action and invalidates changed commit",async()=>{let approved=false;const approval={id:"approval-1",tool:"git_push",arguments:{branch:BRANCH,commitSha:"a".repeat(40)},status:"pending"};const f=await fixture({execute(name){if(name==="git_push"&&!approved)throw new ApprovalRequiredError(approval);return{ok:true};}});const created=await task(f.runtime,[step("push","git_push",approval.arguments)]);let result=await f.runtime.tick();assert.equal(result.status,"waiting_for_approval");assert.equal(f.calls.length,1);approved=true;await f.runtime.resumeApproval(created.id,{...approval,status:"approved"});await f.runtime.tick();assert.equal(f.calls.length,2);assert.equal((await f.runtime.steps(created.id)).length,1);const g=await fixture({execute(){throw new ApprovalRequiredError(approval);}});const changed=await task(g.runtime,[step("push","git_push",approval.arguments)]);await g.runtime.tick();await g.storage.updateAutonomyTask(changed.id,OWNER,{currentCommit:"b".repeat(40)});await assert.rejects(()=>g.runtime.resumeApproval(changed.id,{...approval,status:"approved"}),e=>e.code==="approval_invalidated");});

test("capability routing waits for a capable worker and mutation locks exclude another task",async()=>{const f=await fixture({capabilities:["repo_read_remote"]});const created=await task(f.runtime,[step("apply_patch")]);assert.equal((await f.runtime.tick()).status,"waiting_for_worker");assert.match((await f.runtime.get(created.id)).blockedReason,/repo_mutate_local/);assert.equal(await f.storage.acquireAutonomyLock({lockKey:`nova:${BRANCH}`,taskId:"a",leaseToken:"one",expiresAt:"2026-01-01T00:01:00Z"}),true);assert.equal(await f.storage.acquireAutonomyLock({lockKey:`nova:${BRANCH}`,taskId:"b",leaseToken:"two",expiresAt:"2026-01-01T00:01:00Z"}),false);assert.equal(await f.storage.releaseAutonomyLocks("a","one"),1);});

test("waits do not busy loop and checkpoints survive a runtime restart",async()=>{const f=await fixture();const created=await task(f.runtime,[{type:"wait",input:{delayMs:30000}},step("inspect_repo")]);const waited=await f.runtime.tick();assert.equal(waited.status,"waiting");assert.equal((await f.runtime.tick()).claimed,false);f.advance(31000);const restarted=createWorkerRuntime({storage:f.storage,ownerId:OWNER,toolRegistry:{execute:async()=>({ok:true})},clock:()=>new Date("2026-01-01T00:00:31Z"),capabilities:["scheduler","repo_read_remote"]});await restarted.tick();assert.equal((await restarted.get(created.id)).currentStep,2);assert.equal((await restarted.steps(created.id)).length,2);});

test("activity is complete and secret fields are redacted",async()=>{const f=await fixture();const created=await task(f.runtime,[step("inspect_repo","repo_read",{path:"README.md",apiKey:"never-log"})]);await f.runtime.tick();const events=await f.storage.listActivity(OWNER,{limit:20});assert.ok(events.some(x=>x.action==="autonomy_task_created"));assert.ok(events.some(x=>x.action==="autonomy_step_started"));assert.ok(events.some(x=>x.action==="autonomy_step_completed"));assert.doesNotMatch(JSON.stringify(events),/never-log/);assert.equal((await f.runtime.get(created.id)).checkpoint.latestResult.ok,true);});

test("end-to-end repair task executes bounded steps, approval, Preview polling and completion without duplicate push or deploy",async()=>{let pushApproved=false;const counts={};const f=await fixture({execute(name,input){counts[name]=(counts[name]||0)+1;if(name==="git_commit")return{ok:true,commitSha:"b".repeat(40)};if(name==="git_push"&&!pushApproved)throw new ApprovalRequiredError({id:"push-approval",tool:name,arguments:input,status:"pending"});if(name==="preview_deploy")return{ok:true,deploymentId:"dpl_test",url:"preview.test",status:"READY"};return{ok:true};}});const steps=[step("inspect_repo","repo_list",{}),step("search_code","repo_search",{query:"bug"}),step("read_files","repo_read",{path:"bug.js"}),step("diagnose","diagnose",{}),step("apply_patch","repo_apply_patch",{branch:BRANCH,files:[]}),step("run_focused_tests","test_run",{files:["test.js"]}),step("run_full_tests","test_run_full",{}),step("inspect_diff","repo_diff",{}),step("commit","git_commit",{branch:BRANCH,message:"fix",paths:["bug.js"]}),step("push","git_push",{branch:BRANCH,commitSha:"b".repeat(40)}),step("deploy_preview","preview_deploy",{branch:BRANCH,commitSha:"b".repeat(40)}),{type:"wait",input:{delayMs:1000}},step("verify_preview","preview_verify",{deploymentId:"dpl_test",path:"/api/health",expectedStatus:200,commitSha:"b".repeat(40)}),{type:"summarize",input:{summary:"Synthetic repair complete."}}];const created=await task(f.runtime,steps,{maxSteps:20});for(let i=0;i<10;i++)await f.runtime.tick();assert.equal((await f.runtime.get(created.id)).status,"waiting_for_approval");pushApproved=true;await f.runtime.resumeApproval(created.id,{status:"approved"});for(let i=0;i<3;i++)await f.runtime.tick();f.advance(1000);for(let i=0;i<3;i++)await f.runtime.tick();const done=await f.runtime.get(created.id);assert.equal(done.status,"completed");assert.equal(done.resultSummary,"Synthetic repair complete.");assert.equal(counts.git_push,2);assert.equal(counts.preview_deploy,1);assert.equal((await f.runtime.steps(created.id)).filter(x=>x.stepType==="push").length,1);});

test("verification failure takes one repair retry path and reaches repair_limit_reached deterministically",async()=>{let attempts=0;const f=await fixture({execute(name){if(name==="preview_verify"&&attempts++===0)throw new WorkerError("preview_unavailable","not ready");return{ok:true};}});const created=await task(f.runtime,[step("verify_preview","preview_verify",{}),step("retry_repair","retry_repair",{}),{type:"summarize",input:{summary:"Recovered."}}],{maxRetries:1});let result=await f.runtime.tick();assert.equal(result.status,"retrying");f.advance(1000);await f.runtime.tick();await f.runtime.tick();await f.runtime.tick();assert.equal((await f.runtime.get(created.id)).status,"completed");const stopped=await f.runtime.create({title:"Limit",objective:"Bound repair",projectId:"nova",branch:BRANCH,maxSteps:5,metadata:{maxRepairIterations:1,steps:[step("retry_repair"),step("retry_repair")]}});await f.runtime.tick();assert.equal((await f.runtime.tick()).task.errorCode,"repair_limit_reached");});

test("persisted plans resolve the exact current commit only at execution",async()=>{const seen=[];const f=await fixture({execute(name,input){seen.push({name,input});if(name==="git_commit")return{ok:true,commitSha:"c".repeat(40)};return{ok:true};}});const created=await task(f.runtime,[step("commit","git_commit",{branch:BRANCH,message:"acceptance",paths:["marker.md"]}),step("push","git_push",{branch:BRANCH,commitSha:"$CURRENT_COMMIT"})]);await f.runtime.tick();await f.runtime.tick();assert.equal(seen[1].input.commitSha,"c".repeat(40));assert.equal((await f.runtime.get(created.id)).currentCommit,"c".repeat(40));});
