param([Parameter(Mandatory=$true)][ValidateSet('install','uninstall','status')][string]$Action,[string]$PreviewUrl)
$ErrorActionPreference='Stop'; $name='NovaBrain Persistent Local Worker'
if($Action -eq 'status'){ $task=Get-ScheduledTask -TaskName $name -ErrorAction SilentlyContinue; if($null -eq $task){[Console]::Out.Write('not_installed')}else{[Console]::Out.Write('installed')}; exit }
if($Action -eq 'uninstall'){ Unregister-ScheduledTask -TaskName $name -Confirm:$false -ErrorAction SilentlyContinue; [Console]::Out.Write('uninstalled'); exit }
if($PreviewUrl -notmatch '^https://[a-z0-9.-]+\.vercel\.app/?$'){throw 'A protected HTTPS Vercel Preview URL is required.'}
$node=(Get-Command node.exe).Source; $git=(Get-Command git.exe -ErrorAction Stop).Source; if(-not [System.IO.Path]::IsPathRooted($git) -or [System.IO.Path]::GetFileName($git) -ne 'git.exe'){throw 'A validated Git executable is required.'}; $script=(Resolve-Path (Join-Path $PSScriptRoot 'persistent-local-worker.js')).Path; $root=(Resolve-Path (Join-Path $PSScriptRoot '..')).Path
$runtime=Join-Path $env:LOCALAPPDATA 'NovaBrain\PersistentWorker'; New-Item -ItemType Directory -Path $runtime -Force | Out-Null; $helper=Join-Path $runtime 'NovaCredentialHelper.exe'; if(-not (Test-Path -LiteralPath $helper -PathType Leaf)){throw 'The prevalidated Windows credential helper is required at the stable runtime path.'}; $credentialPrefix='NovaBrain/LocalWorker/'; $novaTarget=$credentialPrefix+('NOVA_LOCAL_WORKER_'+'TOKEN'); $vercelTarget=$credentialPrefix+('VERCEL_AUTOMATION_'+'BYPASS'); $novaStatus=& $helper status $novaTarget; if($LASTEXITCODE -ne 0 -or $novaStatus -notin @('configured','missing')){throw 'The stable Windows credential helper failed its bounded status probe.'}; $vercelStatus=& $helper status $vercelTarget; if($LASTEXITCODE -ne 0 -or $vercelStatus -notin @('configured','missing')){throw 'The stable Windows credential helper failed its bounded status probe.'}
$arguments='"'+$script+'" --preview-url "'+$PreviewUrl.TrimEnd('/')+'" --git-executable "'+$git+'" --credential-helper "'+$helper+'"'; $taskAction=New-ScheduledTaskAction -Execute $node -Argument $arguments -WorkingDirectory $root
$trigger=New-ScheduledTaskTrigger -AtLogOn -User $env:USERNAME
$settings=New-ScheduledTaskSettingsSet -ExecutionTimeLimit ([TimeSpan]::Zero) -RestartCount 999 -RestartInterval (New-TimeSpan -Minutes 1) -MultipleInstances IgnoreNew -AllowStartIfOnBatteries -DontStopIfGoingOnBatteries
Register-ScheduledTask -TaskName $name -Action $taskAction -Trigger $trigger -Settings $settings -Description 'Bounded Nova Self-Development worker; credentials load from Windows Credential Manager.' -Force | Out-Null
$installedAction=(Get-ScheduledTask -TaskName $name -ErrorAction Stop).Actions | Select-Object -First 1; if($installedAction.Execute -ne $node -or $installedAction.Arguments -notlike ('*--credential-helper "'+$helper+'"*')){throw 'The Scheduled Task credential-helper binding could not be verified.'}
[Console]::Out.Write('installed')
