export const SCHEMA_VERSION = 23;

export const SCHEMA_STATEMENTS = Object.freeze([
  `CREATE TABLE IF NOT EXISTS nova_schema_migrations (version integer PRIMARY KEY, applied_at timestamptz NOT NULL DEFAULT now())`,
  `CREATE TABLE IF NOT EXISTS nova_owners (
    id text PRIMARY KEY,
    full_name text NOT NULL,
    preferred_name text,
    arabic_name text,
    facts jsonb NOT NULL DEFAULT '{}'::jsonb,
    preferences jsonb NOT NULL DEFAULT '{}'::jsonb,
    goals jsonb NOT NULL DEFAULT '[]'::jsonb,
    contextual_info jsonb NOT NULL DEFAULT '{}'::jsonb,
    provenance text NOT NULL,
    privacy text NOT NULL DEFAULT 'private',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_projects (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    name text NOT NULL,
    description text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_conversations (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    title text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_messages (
    sequence bigserial PRIMARY KEY,
    id text UNIQUE NOT NULL,
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    role text NOT NULL CHECK (role IN ('user', 'assistant')),
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_messages_conversation_order_idx ON nova_messages (conversation_id, sequence)`,
  `CREATE TABLE IF NOT EXISTS nova_conversation_live_state (
    conversation_id text PRIMARY KEY REFERENCES nova_conversations(id) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    context_version bigint NOT NULL DEFAULT 0 CHECK (context_version >= 0),
    rolling_summary text NOT NULL DEFAULT '' CHECK (octet_length(rolling_summary) <= 65536),
    unresolved_state jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(unresolved_state::text) <= 16384),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_project_sources (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    project_id text NOT NULL REFERENCES nova_projects(id) ON DELETE CASCADE,
    source_type text NOT NULL CHECK (source_type IN ('owner_statement','owner_document','public_url','github','vercel','neon','stripe')),
    label text NOT NULL CHECK (octet_length(label) BETWEEN 1 AND 500),
    locator text,
    content_hash text,
    access_mode text NOT NULL DEFAULT 'reference_only' CHECK (access_mode IN ('reference_only','read_only')),
    status text NOT NULL DEFAULT 'active' CHECK (status IN ('proposed','active','revoked')),
    permissions jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(permissions::text) <= 8192),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    revoked_at timestamptz,
    UNIQUE(owner_id,project_id,source_type,content_hash)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_project_sources_scope_idx ON nova_project_sources (owner_id,project_id,status,created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_conversation_events (
    sequence bigserial PRIMARY KEY, id text UNIQUE NOT NULL,
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    turn_id text, message_id text, event_type text NOT NULL, status text NOT NULL,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(metadata::text) <= 65536),
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_conversation_events_order_idx ON nova_conversation_events (owner_id,conversation_id,sequence)`,
  `CREATE TABLE IF NOT EXISTS nova_memories (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    category text NOT NULL,
    content text NOT NULL,
    provenance text NOT NULL,
    privacy text NOT NULL DEFAULT 'private',
    sensitivity text NOT NULL DEFAULT 'normal',
    scope text NOT NULL DEFAULT 'global',
    project_id text REFERENCES nova_projects(id) ON DELETE SET NULL,
    confidence numeric,
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(evidence::text) <= 32768),
    status text NOT NULL DEFAULT 'active',
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    deleted_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS nova_memories_owner_active_idx ON nova_memories (owner_id, status, updated_at DESC)`,
  `CREATE INDEX IF NOT EXISTS nova_memories_project_idx ON nova_memories (owner_id, project_id)`,
  `ALTER TABLE nova_memories ADD COLUMN IF NOT EXISTS evidence jsonb NOT NULL DEFAULT '{}'::jsonb`,
  `DO $$ BEGIN IF NOT EXISTS (SELECT 1 FROM pg_constraint WHERE conname='nova_memories_evidence_size') THEN ALTER TABLE nova_memories ADD CONSTRAINT nova_memories_evidence_size CHECK (octet_length(evidence::text) <= 32768); END IF; END $$`,
  `CREATE TABLE IF NOT EXISTS nova_memory_candidates (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    project_id text REFERENCES nova_projects(id) ON DELETE SET NULL,
    conversation_id text REFERENCES nova_conversations(id) ON DELETE SET NULL,
    source_message_id text,
    source_run_id text,
    source_task_id text,
    source_kind text NOT NULL CHECK (source_kind IN ('typed_conversation','completed_task','failed_task')),
    candidate_type text NOT NULL CHECK (candidate_type IN ('verified_fact','owner_claim','preference','project_decision','hypothesis','unresolved_question','completed_task_outcome','failed_task_lesson','correction')),
    content text NOT NULL CHECK (octet_length(content) BETWEEN 1 AND 8192),
    evidence jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(evidence::text) <= 32768),
    provenance text NOT NULL,
    privacy text NOT NULL DEFAULT 'private' CHECK (privacy IN ('private','restricted')),
    scope text NOT NULL DEFAULT 'global' CHECK (scope IN ('global','system','project')),
    status text NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','accepted','rejected','superseded')),
    fingerprint text NOT NULL,
    supersedes_memory_id text REFERENCES nova_memories(id) ON DELETE SET NULL,
    accepted_memory_id text REFERENCES nova_memories(id) ON DELETE SET NULL,
    decision_reason text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    decided_at timestamptz,
    UNIQUE(owner_id,fingerprint)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_memory_candidates_owner_status_idx ON nova_memory_candidates (owner_id,status,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS nova_memory_candidates_task_idx ON nova_memory_candidates (owner_id,source_task_id) WHERE source_task_id IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_profiles (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    display_name text NOT NULL, relation text NOT NULL, scope text NOT NULL,
    enrollment_status text NOT NULL, status text NOT NULL,
    representation jsonb, representation_version text NOT NULL,
    consent_at timestamptz NOT NULL, consent_actor text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS nova_speaker_profiles_owner_active_idx ON nova_speaker_profiles (owner_id, status, updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_channel_calibrations (
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    speaker_profile_id text NOT NULL REFERENCES nova_speaker_profiles(id) ON DELETE CASCADE,
    channel text NOT NULL,
    status text NOT NULL CHECK (status IN ('pending_consent','collecting','ready','revoked')),
    representation_version text NOT NULL,
    owner_match_threshold numeric,
    ambiguity_margin numeric,
    sample_count integer NOT NULL DEFAULT 0 CHECK (sample_count >= 0),
    session_count integer NOT NULL DEFAULT 0 CHECK (session_count >= 0),
    conditions jsonb NOT NULL DEFAULT '[]'::jsonb,
    consent_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), revoked_at timestamptz,
    PRIMARY KEY(owner_id,speaker_profile_id,channel)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_speaker_channel_calibrations_owner_idx ON nova_speaker_channel_calibrations (owner_id,channel,status,updated_at DESC)`,
  `ALTER TABLE nova_speaker_profiles ADD COLUMN IF NOT EXISTS enrollment_attempt_id text`,
  `CREATE UNIQUE INDEX IF NOT EXISTS nova_speaker_profiles_owner_attempt_idx ON nova_speaker_profiles (owner_id, enrollment_attempt_id) WHERE enrollment_attempt_id IS NOT NULL`,
  `CREATE TABLE IF NOT EXISTS nova_anonymous_speaker_profiles (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    stable_label text NOT NULL, representation jsonb NOT NULL, representation_version text NOT NULL,
    status text NOT NULL DEFAULT 'active', consent_at timestamptz NOT NULL, consent_actor text NOT NULL,
    self_reported_name text, first_seen_at timestamptz NOT NULL, last_seen_at timestamptz NOT NULL,
    encounter_count integer NOT NULL DEFAULT 1 CHECK (encounter_count > 0),
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), deleted_at timestamptz,
    UNIQUE(owner_id, stable_label)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_anonymous_speakers_owner_active_idx ON nova_anonymous_speaker_profiles (owner_id, status, last_seen_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_voice_utterances (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE CASCADE,
    speaker_profile_id text REFERENCES nova_speaker_profiles(id) ON DELETE SET NULL,
    speaker_label text NOT NULL, confidence numeric, text text NOT NULL,
    started_at_ms integer, ended_at_ms integer, created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_voice_utterances_conversation_idx ON nova_voice_utterances (conversation_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_execution_runs (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    project_id text REFERENCES nova_projects(id) ON DELETE SET NULL, conversation_id text REFERENCES nova_conversations(id) ON DELETE SET NULL,
    goal text NOT NULL, status text NOT NULL, current_step integer NOT NULL DEFAULT 0,
    result jsonb, error text, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS nova_runs_owner_recent_idx ON nova_execution_runs (owner_id, updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_autonomy_tasks (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    project_id text REFERENCES nova_projects(id) ON DELETE SET NULL, title text NOT NULL, objective text NOT NULL,
    task_type text NOT NULL, status text NOT NULL, priority integer NOT NULL DEFAULT 0,
    current_phase text NOT NULL DEFAULT 'queued', current_step integer NOT NULL DEFAULT 0,
    max_steps integer NOT NULL, max_retries integer NOT NULL, max_runtime_minutes integer NOT NULL,
    branch text, starting_commit text, current_commit text, checkpoint jsonb NOT NULL DEFAULT '{}'::jsonb,
    approval_state jsonb, blocked_reason text, result_summary text, error_code text, next_run_at timestamptz,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb, lease_owner text, lease_token text, lease_expires_at timestamptz,
    retry_count integer NOT NULL DEFAULT 0, repair_iteration integer NOT NULL DEFAULT 0, state_version bigint NOT NULL DEFAULT 1,
    created_at timestamptz NOT NULL DEFAULT now(), started_at timestamptz, updated_at timestamptz NOT NULL DEFAULT now(), completed_at timestamptz
  )`,
  `ALTER TABLE nova_autonomy_tasks ADD COLUMN IF NOT EXISTS state_version bigint NOT NULL DEFAULT 1`,
  `CREATE INDEX IF NOT EXISTS nova_autonomy_queue_idx ON nova_autonomy_tasks (status, next_run_at, priority DESC, created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_execution_attempts (
    id text PRIMARY KEY,
    task_id text NOT NULL REFERENCES nova_autonomy_tasks(id) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    handoff_id text NOT NULL,
    worker_id text NOT NULL,
    generation integer NOT NULL CHECK (generation > 0),
    fence_token text NOT NULL,
    status text NOT NULL CHECK (status IN ('preparing','executing','interrupted','completed','failed','cancelled','superseded')),
    phase text NOT NULL,
    executor_started boolean NOT NULL DEFAULT false,
    claimed_at timestamptz NOT NULL,
    last_heartbeat_at timestamptz NOT NULL,
    last_progress_at timestamptz,
    lease_expires_at timestamptz NOT NULL,
    ended_at timestamptz,
    terminal_reason text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    UNIQUE(task_id,generation),
    UNIQUE(task_id,handoff_id)
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS nova_execution_attempts_one_active_idx ON nova_execution_attempts (task_id) WHERE status IN ('preparing','executing')`,
  `CREATE INDEX IF NOT EXISTS nova_execution_attempts_owner_active_idx ON nova_execution_attempts (owner_id,status,lease_expires_at)`,
  `CREATE TABLE IF NOT EXISTS nova_task_report_outbox (
    report_key text PRIMARY KEY,
    task_id text NOT NULL REFERENCES nova_autonomy_tasks(id) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE CASCADE,
    terminal_state_version bigint NOT NULL,
    terminal_status text NOT NULL CHECK (terminal_status IN ('completed','failed','blocked','cancelled','expired')),
    message_id text UNIQUE NOT NULL,
    content text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now(),
    delivered_at timestamptz,
    UNIQUE(task_id,terminal_state_version)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_task_report_outbox_pending_idx ON nova_task_report_outbox (owner_id, delivered_at, created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_autonomy_steps (
    task_id text NOT NULL REFERENCES nova_autonomy_tasks(id) ON DELETE CASCADE, step_id text NOT NULL,
    step_type text NOT NULL, capability text NOT NULL, operation_fingerprint text NOT NULL,
    status text NOT NULL, attempt integer NOT NULL DEFAULT 0, input jsonb NOT NULL DEFAULT '{}'::jsonb,
    result jsonb, error_code text, started_at timestamptz, completed_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(task_id,step_id), UNIQUE(task_id,operation_fingerprint)
  )`,
  `CREATE TABLE IF NOT EXISTS nova_autonomy_locks (
    lock_key text PRIMARY KEY, task_id text NOT NULL REFERENCES nova_autonomy_tasks(id) ON DELETE CASCADE,
    lease_token text NOT NULL, expires_at timestamptz NOT NULL, created_at timestamptz NOT NULL DEFAULT now()
  )`,
  // Private diagnostic storage, deliberately separate from tasks and activity.
  `CREATE TABLE IF NOT EXISTS nova_rejected_review_evidence (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    task_id text NOT NULL REFERENCES nova_autonomy_tasks(id) ON DELETE CASCADE,
    execution_id text NOT NULL, attempt integer NOT NULL CHECK (attempt > 0),
    continuation_generation_id text NOT NULL,
    envelope jsonb NOT NULL CHECK (octet_length(envelope::text) <= 98304),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(owner_id,task_id,execution_id,attempt,continuation_generation_id)
  )`,
  `CREATE TABLE IF NOT EXISTS nova_gmail_oauth_states (
    state_hash text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    session_hash text NOT NULL,
    encrypted_code_verifier jsonb NOT NULL,
    expires_at timestamptz NOT NULL,
    consumed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_gmail_oauth_states_owner_expiry_idx ON nova_gmail_oauth_states (owner_id, expires_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_gmail_connections (
    owner_id text PRIMARY KEY REFERENCES nova_owners(id) ON DELETE CASCADE,
    email text NOT NULL,
    scopes jsonb NOT NULL,
    encrypted_access_token jsonb,
    access_token_expires_at timestamptz,
    encrypted_refresh_token jsonb NOT NULL,
    connected_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_gmail_drafts (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    to_recipients jsonb NOT NULL,
    cc_recipients jsonb NOT NULL DEFAULT '[]'::jsonb,
    bcc_recipients jsonb NOT NULL DEFAULT '[]'::jsonb,
    subject text NOT NULL,
    body text NOT NULL,
    thread_id text,
    in_reply_to text,
    references_header text,
    intent_hash text NOT NULL,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_gmail_send_intents (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    draft_id text NOT NULL REFERENCES nova_gmail_drafts(id) ON DELETE RESTRICT,
    intent_hash text NOT NULL,
    message_id text NOT NULL,
    status text NOT NULL CHECK (status IN ('sending','sent','uncertain','failed')),
    provider_message_id text,
    provider_thread_id text,
    error_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(owner_id, draft_id)
  )`,
  `CREATE TABLE IF NOT EXISTS nova_phone_call_intents (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE CASCADE,
    prepared_run_id text REFERENCES nova_execution_runs(id) ON DELETE SET NULL,
    call_conversation_id text NOT NULL,
    envelope jsonb NOT NULL CHECK (octet_length(envelope::text) <= 32768),
    envelope_hash text NOT NULL,
    status text NOT NULL CHECK (status IN ('prepared','waiting_for_approval','approved','dialing','in_progress','completed','failed','uncertain')),
    approval_id text,
    attempt_count integer NOT NULL DEFAULT 0 CHECK (attempt_count >= 0 AND attempt_count <= 1),
    submission_key text UNIQUE,
    provider_call_sid text UNIQUE,
    provider_stream_sid text UNIQUE,
    provider_status text,
    session_token_hash text,
    session_token_expires_at timestamptz,
    session_token_used_at timestamptz,
    outcome text,
    summary text,
    error_code text,
    expires_at timestamptz NOT NULL,
    started_at timestamptz,
    ended_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_phone_calls_conversation_idx ON nova_phone_call_intents (owner_id,conversation_id,created_at DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS nova_phone_one_active_call_idx ON nova_phone_call_intents (owner_id) WHERE status IN ('dialing','in_progress')`,
  `CREATE TABLE IF NOT EXISTS nova_phone_call_events (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    call_intent_id text NOT NULL REFERENCES nova_phone_call_intents(id) ON DELETE CASCADE,
    event_key text NOT NULL,
    event_type text NOT NULL,
    provider_call_sid text,
    provider_stream_sid text,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(metadata::text) <= 16384),
    created_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(owner_id,call_intent_id,event_key)
  )`,
  `CREATE TABLE IF NOT EXISTS nova_phone_call_turns (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    call_intent_id text NOT NULL REFERENCES nova_phone_call_intents(id) ON DELETE CASCADE,
    input_hash text NOT NULL,
    caller_text text NOT NULL CHECK (octet_length(caller_text) <= 32768),
    nova_text text,
    control text,
    run_id text REFERENCES nova_execution_runs(id) ON DELETE SET NULL,
    status text NOT NULL CHECK (status IN ('processing','completed','failed')),
    error_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now(),
    UNIQUE(owner_id,call_intent_id,id)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_phone_turns_call_idx ON nova_phone_call_turns (owner_id,call_intent_id,created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_owner_contact_policies (
    owner_id text PRIMARY KEY REFERENCES nova_owners(id) ON DELETE CASCADE,
    version integer NOT NULL CHECK (version > 0),
    enabled boolean NOT NULL DEFAULT false,
    allowed_reasons jsonb NOT NULL DEFAULT '[]'::jsonb,
    quiet_hours jsonb NOT NULL DEFAULT '{}'::jsonb,
    cooldown_minutes integer NOT NULL CHECK (cooldown_minutes BETWEEN 1 AND 240),
    daily_limit integer NOT NULL CHECK (daily_limit BETWEEN 1 AND 5),
    maximum_calls integer NOT NULL CHECK (maximum_calls BETWEEN 1 AND 5),
    used_calls integer NOT NULL DEFAULT 0 CHECK (used_calls >= 0),
    expires_at timestamptz NOT NULL,
    paused_at timestamptz,
    revoked_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_owner_callback_eligibilities (
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    task_id text NOT NULL REFERENCES nova_autonomy_tasks(id) ON DELETE CASCADE,
    terminal_state_version integer NOT NULL,
    conversation_id text REFERENCES nova_conversations(id) ON DELETE SET NULL,
    reason text NOT NULL CHECK (reason IN ('task_completed','task_blocked_owner_required')),
    status text NOT NULL CHECK (status IN ('eligible','ineligible')),
    decision_code text NOT NULL,
    policy_version integer,
    created_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(owner_id,task_id,terminal_state_version)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_owner_callback_eligibilities_owner_idx ON nova_owner_callback_eligibilities (owner_id,status,created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_approvals (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    project_id text REFERENCES nova_projects(id) ON DELETE SET NULL, run_id text REFERENCES nova_execution_runs(id) ON DELETE SET NULL,
    tool text NOT NULL, reason text NOT NULL, risk_level text NOT NULL, arguments jsonb NOT NULL DEFAULT '{}'::jsonb,
    status text NOT NULL DEFAULT 'pending', decision text, created_at timestamptz NOT NULL DEFAULT now(), decided_at timestamptz
  )`,
  `CREATE INDEX IF NOT EXISTS nova_approvals_owner_pending_idx ON nova_approvals (owner_id, status, created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_enrollment_consents (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    purpose text NOT NULL, consent_version text NOT NULL, consent_actor text NOT NULL,
    channel text NOT NULL, provenance text NOT NULL, status text NOT NULL CHECK (status IN ('active','revoked')),
    consented_at timestamptz NOT NULL, revoked_at timestamptz, created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE UNIQUE INDEX IF NOT EXISTS nova_speaker_enrollment_active_consent_idx ON nova_speaker_enrollment_consents (owner_id,purpose,channel) WHERE status='active'`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_enrollment_sessions (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    consent_id text NOT NULL REFERENCES nova_speaker_enrollment_consents(id) ON DELETE RESTRICT,
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE RESTRICT,
    session_number integer NOT NULL CHECK (session_number IN (1,2)), expected_samples integer NOT NULL CHECK (expected_samples=3),
    condition_label text NOT NULL, phrase_plan jsonb NOT NULL CHECK (jsonb_array_length(phrase_plan)=3),
    status text NOT NULL CHECK (status IN ('prepared','waiting_for_approval','approved','collecting','completed','failed','revoked')),
    accepted_count integer NOT NULL DEFAULT 0 CHECK (accepted_count BETWEEN 0 AND 3), total_required integer NOT NULL DEFAULT 6 CHECK (total_required=6),
    call_intent_id text UNIQUE REFERENCES nova_phone_call_intents(id) ON DELETE SET NULL,
    approval_id text UNIQUE REFERENCES nova_approvals(id) ON DELETE SET NULL,
    expires_at timestamptz NOT NULL, completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_speaker_enrollment_sessions_owner_idx ON nova_speaker_enrollment_sessions (owner_id,status,created_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_enrollment_samples (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    session_id text NOT NULL REFERENCES nova_speaker_enrollment_sessions(id) ON DELETE CASCADE,
    ordinal integer NOT NULL CHECK (ordinal BETWEEN 1 AND 3), submission_key text NOT NULL,
    prompt_id text NOT NULL, language text NOT NULL, condition_label text NOT NULL,
    status text NOT NULL CHECK (status IN ('accepted','retry')),
    quality jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(quality::text)<=8192),
    encrypted_representation jsonb, representation_version text,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id,session_id,submission_key)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_speaker_enrollment_samples_session_idx ON nova_speaker_enrollment_samples (owner_id,session_id,ordinal,created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_control_sessions (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    participant_code text NOT NULL CHECK (participant_code IN ('control-01','control-02','control-03')),
    conversation_id text NOT NULL REFERENCES nova_conversations(id) ON DELETE RESTRICT,
    plan jsonb NOT NULL CHECK (jsonb_array_length(plan)=4), consent_version text NOT NULL,
    consent_disclosure text NOT NULL, consent_status text NOT NULL DEFAULT 'pending' CHECK (consent_status IN ('pending','granted','refused')),
    status text NOT NULL CHECK (status IN ('prepared','waiting_for_approval','approved','awaiting_consent','collecting','completed','refused','failed','revoked')),
    accepted_count integer NOT NULL DEFAULT 0 CHECK (accepted_count BETWEEN 0 AND 4),
    cost_cap_usd numeric NOT NULL CHECK (cost_cap_usd > 0 AND cost_cap_usd <= 5),
    call_intent_id text UNIQUE REFERENCES nova_phone_call_intents(id) ON DELETE SET NULL,
    approval_id text UNIQUE REFERENCES nova_approvals(id) ON DELETE SET NULL,
    expires_at timestamptz NOT NULL, consented_at timestamptz, refused_at timestamptz, completed_at timestamptz,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_speaker_control_sessions_owner_idx ON nova_speaker_control_sessions (owner_id,status,created_at DESC)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS nova_speaker_control_sessions_one_active_slot_idx ON nova_speaker_control_sessions (owner_id,participant_code) WHERE status NOT IN ('failed','refused','revoked')`,
  `CREATE TABLE IF NOT EXISTS nova_speaker_control_samples (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    session_id text NOT NULL REFERENCES nova_speaker_control_sessions(id) ON DELETE CASCADE,
    participant_code text NOT NULL, ordinal integer NOT NULL CHECK (ordinal BETWEEN 1 AND 4), submission_key text NOT NULL,
    prompt_id text NOT NULL, language text NOT NULL CHECK (language IN ('arabic','english','mixed')),
    condition_label text NOT NULL CHECK (condition_label IN ('normal_handset','speakerphone')),
    status text NOT NULL CHECK (status IN ('accepted','retry')),
    quality jsonb NOT NULL DEFAULT '{}'::jsonb CHECK (octet_length(quality::text)<=8192),
    score numeric, representation_version text, preprocessing_version text,
    created_at timestamptz NOT NULL DEFAULT now(), UNIQUE(owner_id,session_id,submission_key)
  )`,
  `CREATE INDEX IF NOT EXISTS nova_speaker_control_samples_session_idx ON nova_speaker_control_samples (owner_id,session_id,ordinal,created_at)`,
  `CREATE UNIQUE INDEX IF NOT EXISTS nova_speaker_control_samples_one_accepted_ordinal_idx ON nova_speaker_control_samples (owner_id,session_id,ordinal) WHERE status='accepted'`,
  `CREATE TABLE IF NOT EXISTS nova_activity_events (
    sequence bigserial PRIMARY KEY, id text UNIQUE NOT NULL, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    project_id text REFERENCES nova_projects(id) ON DELETE SET NULL, run_id text REFERENCES nova_execution_runs(id) ON DELETE SET NULL,
    action text NOT NULL, tool text, status text NOT NULL, summary text NOT NULL, metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_activity_owner_recent_idx ON nova_activity_events (owner_id, sequence DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_whatsapp_inbound_messages (
    message_sid text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    conversation_id text NOT NULL,
    contact_id text NOT NULL,
    contact_ciphertext text NOT NULL,
    body_hash text NOT NULL,
    status text NOT NULL CHECK (status IN ('queued','processing','replied','failed')),
    attempt_count integer NOT NULL DEFAULT 0,
    next_attempt_at timestamptz,
    lease_owner text,
    lease_token text,
    lease_expires_at timestamptz,
    run_id text,
    assistant_message_id text,
    error_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_whatsapp_inbound_owner_contact_idx ON nova_whatsapp_inbound_messages (owner_id,contact_id,created_at DESC)`,
  `CREATE INDEX IF NOT EXISTS nova_whatsapp_inbound_queue_idx ON nova_whatsapp_inbound_messages (owner_id,status,next_attempt_at,created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_whatsapp_outbound_messages (
    inbound_sid text PRIMARY KEY REFERENCES nova_whatsapp_inbound_messages(message_sid) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    body_hash text NOT NULL,
    status text NOT NULL CHECK (status IN ('sending','submitted','queued','sent','delivered','read','undelivered','failed','uncertain')),
    provider_message_sid text UNIQUE,
    error_code text,
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_whatsapp_outbound_owner_status_idx ON nova_whatsapp_outbound_messages (owner_id,status,updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_developer_sessions (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    record jsonb NOT NULL CHECK (octet_length(record::text) <= 262144),
    created_at timestamptz NOT NULL DEFAULT now(),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_developer_sessions_owner_recent_idx ON nova_developer_sessions (owner_id, updated_at DESC)`,
  `CREATE TABLE IF NOT EXISTS nova_voice_benchmark_sessions (
    id text PRIMARY KEY, owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    budget_usd numeric NOT NULL CHECK (budget_usd > 0 AND budget_usd <= 2), created_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_voice_benchmark_results (
    id text PRIMARY KEY, session_id text NOT NULL REFERENCES nova_voice_benchmark_sessions(id) ON DELETE CASCADE,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE, kind text NOT NULL CHECK (kind IN ('stt','tts')),
    provider_id text NOT NULL, sample_id text NOT NULL, label text NOT NULL, status text NOT NULL,
    estimated_cost_usd numeric NOT NULL DEFAULT 0, latency_ms integer, transcript text, metrics jsonb, ratings jsonb,
    model text, voice text, metadata jsonb NOT NULL DEFAULT '{}'::jsonb, revealed boolean NOT NULL DEFAULT false, error text,
    created_at timestamptz NOT NULL DEFAULT now(), updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE TABLE IF NOT EXISTS nova_voice_benchmark_budgets (
    owner_id text PRIMARY KEY REFERENCES nova_owners(id) ON DELETE CASCADE,
    reserved_usd numeric NOT NULL DEFAULT 0 CHECK (reserved_usd >= 0),
    cap_usd numeric NOT NULL CHECK (cap_usd > 0 AND cap_usd <= 2),
    updated_at timestamptz NOT NULL DEFAULT now()
  )`,
  `CREATE INDEX IF NOT EXISTS nova_voice_benchmark_owner_cost_idx ON nova_voice_benchmark_results (owner_id, created_at)`,
  `CREATE INDEX IF NOT EXISTS nova_voice_benchmark_session_idx ON nova_voice_benchmark_results (session_id, created_at)`,
  `CREATE TABLE IF NOT EXISTS nova_model_cost_budgets (
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    budget_id text NOT NULL,
    spent_nano_usd bigint NOT NULL DEFAULT 0 CHECK (spent_nano_usd >= 0),
    reserved_nano_usd bigint NOT NULL DEFAULT 0 CHECK (reserved_nano_usd >= 0),
    task_totals jsonb NOT NULL DEFAULT '{}'::jsonb,
    updated_at timestamptz NOT NULL DEFAULT now(),
    PRIMARY KEY(owner_id,budget_id)
  )`,
  `CREATE TABLE IF NOT EXISTS nova_model_cost_reservations (
    id text PRIMARY KEY,
    owner_id text NOT NULL REFERENCES nova_owners(id) ON DELETE CASCADE,
    budget_id text NOT NULL,
    task_id text,
    run_id text,
    stage text NOT NULL,
    model text NOT NULL,
    status text NOT NULL CHECK (status IN ('reserved','settled','released','uncertain')),
    reserved_nano_usd bigint NOT NULL CHECK (reserved_nano_usd >= 0),
    actual_nano_usd bigint CHECK (actual_nano_usd >= 0),
    usage jsonb,
    metadata jsonb NOT NULL DEFAULT '{}'::jsonb,
    created_at timestamptz NOT NULL DEFAULT now(),
    settled_at timestamptz,
    FOREIGN KEY(owner_id,budget_id) REFERENCES nova_model_cost_budgets(owner_id,budget_id) ON DELETE CASCADE
  )`,
  `CREATE INDEX IF NOT EXISTS nova_model_cost_task_idx ON nova_model_cost_reservations (owner_id,budget_id,task_id,created_at)`,
  `INSERT INTO nova_schema_migrations (version) VALUES (1), (2), (3), (4), (5), (6), (7), (8), (9), (10), (11), (12), (13), (14), (15), (16), (17), (18), (19), (20), (21), (22) ON CONFLICT (version) DO NOTHING`
]);
