import { readdir, readFile } from "node:fs/promises";
import { resolve, relative, sep } from "node:path";
import { execFile } from "node:child_process";
import { promisify } from "node:util";
import { RISK_LEVELS } from "../policy/action-policy.js";

const runFile = promisify(execFile);
const secretName = /(^|[\\/])(\.env|\.git|node_modules)([\\/]|$)|secret|credential|token|key/i;
function safePath(root, input = ".") { const target = resolve(root, input); if (target !== root && !target.startsWith(`${root}${sep}`)) throw new Error("Path is outside the approved repository."); if (secretName.test(relative(root,target))) throw new Error("Protected path."); return target; }
function stringArg(input, name, max = 500) { if (typeof input[name] !== "string" || !input[name].trim() || input[name].length > max) throw new Error(`${name} is required.`); }
async function files(root, directory = root, output = []) { for (const entry of await readdir(directory,{withFileTypes:true})) { if ([".git","node_modules",".vercel"].includes(entry.name)) continue; const path=resolve(directory,entry.name); if(entry.isDirectory()) await files(root,path,output); else output.push(relative(root,path).replaceAll("\\","/")); if(output.length>=500)break; } return output; }
const definition = (tool) => ({ category:"developer", capability:"read", configurationStatus:"ready", available:true, riskLevel:RISK_LEVELS.READ_ONLY, ...tool });

export function registerDeveloperTools(registry, { root = process.cwd(), environment = process.env } = {}) {
  const remote=Boolean(environment.VERCEL);const repository=environment.NOVA_BRAIN_GITHUB_REPOSITORY||"hshanbour/nova-brain";const branch=environment.NOVA_BRAIN_DEVELOPMENT_BRANCH||"feat/nova-brain-mvp-foundation";
  const githubGet=async(path)=>{const response=await fetch(`https://api.github.com/repos/${repository}/${path}`,{headers:{Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28",...(environment.NOVA_BRAIN_GITHUB_TOKEN?{Authorization:`Bearer ${environment.NOVA_BRAIN_GITHUB_TOKEN}`}:{})}});if(!response.ok)throw new Error(`Repository read failed with status ${response.status}.`);return response.json();};
  registry.register(definition({ name:"repo_list", description:"List files in the approved Nova Brain repository.", inputSchema:{type:"object",properties:{path:{type:"string"}},additionalProperties:false}, async execute({path="."}) { if(remote){const payload=await githubGet(`git/trees/${encodeURIComponent(branch)}?recursive=1`);const prefix=path==="."?"":`${path.replace(/\/$/,"")}/`;return {files:(payload.tree||[]).filter((item)=>item.type==="blob"&&item.path.startsWith(prefix)&&!secretName.test(item.path)).slice(0,500).map((item)=>item.path)};}const base=safePath(root,path);return {files:await files(root,base)}; } }));
  registry.register(definition({ name:"repo_read", description:"Read a UTF-8 source file from the approved repository.", inputSchema:{type:"object",properties:{path:{type:"string"}},required:["path"],additionalProperties:false}, validate:(input)=>{stringArg(input,"path");safePath(root,input.path);}, async execute({path}) { let content;if(remote){const payload=await githubGet(`contents/${path.split("/").map(encodeURIComponent).join("/")}?ref=${encodeURIComponent(branch)}`);content=Buffer.from(payload.content||"","base64").toString("utf8");}else content=await readFile(safePath(root,path),"utf8");return {path,content:content.slice(0,50_000),truncated:content.length>50_000}; } }));
  registry.register(definition({ name:"repo_search", description:"Search source files for a literal text query.", available:!remote, configurationStatus:remote?"unavailable_without_search_adapter":"ready", inputSchema:{type:"object",properties:{query:{type:"string"}},required:["query"],additionalProperties:false}, validate:(input)=>stringArg(input,"query",200), async execute({query}) { const matches=[]; for(const path of await files(root)){if(secretName.test(path))continue;let content;try{content=await readFile(resolve(root,path),"utf8");}catch{continue;} content.split(/\r?\n/).forEach((line,index)=>{if(matches.length<100&&line.toLowerCase().includes(query.toLowerCase()))matches.push({path,line:index+1,text:line.slice(0,300)});});} return {matches,truncated:matches.length===100}; } }));
  for (const name of ["git_status","repo_diff"]) registry.register(definition({ name, available:!remote, configurationStatus:remote?"unavailable_in_serverless":"ready", description:name==="git_status"?"Inspect the approved repository Git status.":"Inspect uncommitted changes in the approved repository.", async execute(){const args=name==="git_status"?["status","--short","--branch"]:["diff","--","."];const {stdout}=await runFile("git",args,{cwd:root,timeout:10_000,maxBuffer:200_000});return {output:stdout.slice(0,100_000),truncated:stdout.length>100_000};} }));
  registry.register(definition({name:"test_run",description:"Run the allowlisted Nova Brain Node test suite.",capability:"execute",available:!environment.VERCEL,configurationStatus:environment.VERCEL?"unavailable_in_serverless":"ready",async execute(){const {stdout,stderr}=await runFile(process.platform==="win32"?"npm.cmd":"npm",["test"],{cwd:root,timeout:120_000,maxBuffer:500_000});return {output:`${stdout}\n${stderr}`.slice(-100_000)};}}));
  const githubReady=Boolean(environment.NOVA_BRAIN_GITHUB_TOKEN&&environment.NOVA_BRAIN_GITHUB_REPOSITORY&&environment.NOVA_BRAIN_DEVELOPMENT_BRANCH);
  registry.register({name:"repo_apply_patch",description:"Replace one source file and create a commit on the approved development branch using its expected blob SHA.",category:"developer",capability:"write",riskLevel:RISK_LEVELS.LOW_RISK_WRITE,branchBound:true,autonomous:true,available:githubReady,configurationStatus:githubReady?"ready":"configuration_required",inputSchema:{type:"object",properties:{path:{type:"string"},content:{type:"string"},expectedSha:{type:"string"},message:{type:"string"},branch:{type:"string"}},required:["path","content","expectedSha","message","branch"],additionalProperties:false},validate(input){for(const field of ["path","content","expectedSha","message","branch"])stringArg(input,field,field==="content"?200_000:500);safePath(root,input.path);if(input.branch!==environment.NOVA_BRAIN_DEVELOPMENT_BRANCH||["main","master"].includes(input.branch))throw new Error("Branch is not approved for development writes.");},async execute(input){const endpoint=`https://api.github.com/repos/${encodeURI(environment.NOVA_BRAIN_GITHUB_REPOSITORY)}/contents/${input.path.split("/").map(encodeURIComponent).join("/")}`;const response=await fetch(endpoint,{method:"PUT",headers:{Authorization:`Bearer ${environment.NOVA_BRAIN_GITHUB_TOKEN}`,Accept:"application/vnd.github+json","X-GitHub-Api-Version":"2022-11-28","Content-Type":"application/json"},body:JSON.stringify({message:input.message,content:Buffer.from(input.content).toString("base64"),sha:input.expectedSha,branch:input.branch})});if(!response.ok)throw new Error(`GitHub write failed with status ${response.status}.`);const payload=await response.json();return {path:input.path,branch:input.branch,commitSha:payload.commit?.sha||null};}});
  registry.register({name:"git_commit",description:"Commits are created atomically by repo_apply_patch; a separate unrestricted commit operation is intentionally unavailable.",category:"developer",capability:"write",riskLevel:RISK_LEVELS.LOW_RISK_WRITE,available:false,configurationStatus:"not_required_use_repo_apply_patch",async execute(){throw new Error("Use repo_apply_patch.");}});
  const vercelReady=Boolean(environment.NOVA_BRAIN_VERCEL_TOKEN&&environment.NOVA_BRAIN_VERCEL_PROJECT_ID);
  for(const name of ["deployment_status","deployment_logs","preview_verify"]) registry.register({name,description:"Inspect the configured Vercel Preview deployment.",category:"deployment",capability:"read",riskLevel:RISK_LEVELS.READ_ONLY,available:false,configurationStatus:vercelReady?"adapter_not_implemented":"configuration_required",async execute(){throw new Error("Vercel adapter is unavailable.");}});
}

export function registerSystemTools(registry,{storage,ownerId}) {
  registry.register({name:"project_list",description:"List Nova's durable owner projects.",category:"projects",capability:"read",riskLevel:RISK_LEVELS.READ_ONLY,available:true,configurationStatus:"ready",async execute(){return {projects:await storage.listProjects(ownerId)};}});
  registry.register({name:"memory_forget",description:"Forget one specific durable memory after owner approval.",category:"memory",capability:"write",riskLevel:RISK_LEVELS.SENSITIVE,available:true,configurationStatus:"ready",approvalReason:"Nova wants to forget a specific durable memory.",inputSchema:{type:"object",properties:{memoryId:{type:"string"}},required:["memoryId"],additionalProperties:false},validate(input){stringArg(input,"memoryId",128);},async execute({memoryId}){const deleted=await storage.deleteMemory(memoryId,ownerId);return {deleted,memoryId};}});
}
